### ISSUE TITLE
Current client - discrepancy between package version and build number are confusing 

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus#10]
Released version is `4.0.0`.
Release notes reference "build" `3.0.50870.2`.

![image](https://cloud.githubusercontent.com/assets/1309622/24033555/1d0dbd8a-0ab3-11e7-8009-2e77736f1391.png)

**Comment by SeanFeldman** [comment]
The build number is actually the file/product version, which is not aligned with the package version.

When upgrading ASB package, this is obvious
```xml
<Reference Include="Microsoft.ServiceBus, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL">
      <HintPath>..\..\..\..\..\packages\WindowsAzure.ServiceBus.4.0.0\lib\net45-full\Microsoft.ServiceBus.dll</HintPath>
      <Private>True</Private>
    </Reference>
```
Version should be set `4.0.0.0`

**Comment by SeanFeldman** [comment]
adding @jtaubensee

**Comment by EldertGrootenboer** [comment]
If this issue still occurs, please let us know and we can re-open the issue.
