### ISSUE TITLE
ManagingTopicRules example fails to compile

### ISSUE THREAD

**Issue by mickjjfs** [Azure/azure-service-bus#104]
# Description
The ManagingTopicRules example fails to compile lines 65-69 
https://github.com/Azure/azure-service-bus/blob/master/samples/Java/azure-servicebus/ManagingTopicRules/src/main/java/com/microsoft/azure/servicebus/samples/managingtopicrules/ManagingTopicRules.java#L65-L69
The simple fix is to add a '.' so allMessagessubscriptionClientgetRules becomes allMessagessubscriptionClient.getRules on L64 and getRules removed on L66 and L69

It does run correctly after these changes

**Comment by binzywu** [comment]
Thanks for reporting this. Updated @ 7575c5fe2ce7a7de62efd45d96120c9bdc9f8cc4
