### ISSUE TITLE
OnMessage doesn't throw when a Shared Access Key changes

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus#105]
## Actual Behavior
1. `OnMessageAsync` is registered running with a connection string that is using the original shared access key.
1. `OnMessageOptions.ExceptionReceived` is registered with callback.
1. Shared access key is re-generated
1. OnMessage callback doesn't throw an exception and endpoint appears to be working as usual.

## Expected Behavior
When shared access key used with connection string is changed, exception should be raised as endpoint is not able to receive anything and looks like "stack" with a connection that is a zombie.

## Versions  
Windows, ASB client v4.1.3

**Comment by SeanFeldman** [comment]
Exhibits same behavior as the [new client](https://github.com/Azure/azure-service-bus-dotnet/issues/357)

**Comment by nemakam** [comment]
Repeating what @clemensv mentioned [here](https://github.com/Azure/azure-service-bus-dotnet/issues/357#issuecomment-339353648):
"The access check is performed when the link to the entity is established. If the token is validly signed at the instant the check is performed, access is granted for the token validity period and for as long as the link is maintained.

If you're obtaining an identity token from an identity provider (AAD, etc) using some identity and credential, and then obtain an access token based on some token trade rule, the access token also remains valid for the issued period, even if your credential in AAD gets revoked or the account gets deleted altogether.

The mitigation is to make tokens shorter lived. The service does observe token expiration."
