### ISSUE TITLE
System.Threading.Tasks.TaskCanceledException: 'A task was canceled.' while processing queue messages

### ISSUE THREAD

**Issue by nick-goloborodko** [Azure/azure-service-bus#106]
Hi,

I'm encountering an extremely frustrating and odd error message while attempting to use ServiceBus Queue client.

Steps to reproduce:
1) Create a blank .NET Core 2.0 console app.
2) Add NuGet package reference to Microsoft.Azure.ServiceBus v2.0
3) Copy the content of Program.cs from the BasicSendReceiveUsingQueueClient sample
4) Run

The exception will be thrown at the end of ProcessMessagesAsync method when processing the first message.

![image](https://user-images.githubusercontent.com/28851326/31978286-2621be14-b99d-11e7-81d1-49cdcde947f2.png)

What makes this issue even more bizare - upgrading the BasicSendReceiveUsingQueueClient project to .NET Core 2.0 and the Microsoft.Azure.ServiceBus to 2.0 - still works fine...

Any help would be greatly appreciated.

Kind regards,
Nick Goloborodko

**Comment by SeanFeldman** [comment]
@nick-goloborodko I just tried to create a new netcoreapp2.0 console application with Microsoft.Azure.ServiceBus client 2.0 running the same code as the sample (BasicSendReceiveUsingQueueClient) and it's all fine.

You could clone the repo, update the sample, and let others review the code. Maybe it's something else as code looks fine. Cheers.

**Comment by nemakam** [comment]
@nick-goloborodko Could you paste the stack trace here?

**Comment by nick-goloborodko** [comment]
Thanks for the feedback!

The Exception Stack Trace is fairly limited:

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

The Call stack in VS is as follows:
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task task)	Unknown	No symbols loaded.
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task task)	Unknown	No symbols loaded.
 	Microsoft.Azure.ServiceBus.dll!Microsoft.Azure.ServiceBus.MessageReceivePump.RenewMessageLockTask(Microsoft.Azure.ServiceBus.Message message, System.Threading.CancellationToken renewLockCancellationToken) Line 192	C#	Symbols loaded.
 	[Resuming Async Method]		Annotated Frame
 	System.Private.CoreLib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown	No symbols loaded.
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.OutputAsyncCausalityEvents.AnonymousMethod__0()	Unknown	No symbols loaded.
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__0()	Unknown	No symbols loaded.
 	System.Private.CoreLib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action action, bool allowInlining, ref System.Threading.Tasks.Task currentTask)	Unknown	No symbols loaded.
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task.RunContinuations(object continuationObject)	Unknown	No symbols loaded.
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task<System.Threading.Tasks.VoidTaskResult>.TrySetCanceled(System.Threading.CancellationToken tokenToRecord, object cancellationException)	Unknown	No symbols loaded.
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task.DelayPromise.Complete()	Unknown	No symbols loaded.
 	System.Private.CoreLib.dll!System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(bool throwOnFirstException)	Unknown	No symbols loaded.
 	Microsoft.Azure.ServiceBus.dll!Microsoft.Azure.ServiceBus.MessageReceivePump.MessageDispatchTask(Microsoft.Azure.ServiceBus.Message message) Line 126	C#	Symbols loaded.
 	[Resuming Async Method]		Annotated Frame
 	System.Private.CoreLib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown	No symbols loaded.
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.OutputAsyncCausalityEvents.AnonymousMethod__0()	Unknown	No symbols loaded.
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__0()	Unknown	No symbols loaded.
 	System.Private.CoreLib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action action, bool allowInlining, ref System.Threading.Tasks.Task currentTask)	Unknown	No symbols loaded.
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task.RunContinuations(object continuationObject)	Unknown	No symbols loaded.
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task<System.Threading.Tasks.VoidTaskResult>.TrySetResult(System.Threading.Tasks.VoidTaskResult result)	Unknown	No symbols loaded.
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.SetExistingTaskResult(System.Threading.Tasks.VoidTaskResult result)	Unknown	No symbols loaded.
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.SetResult(System.Threading.Tasks.Task<System.Threading.Tasks.VoidTaskResult> completedTask)	Unknown	No symbols loaded.
>	Metroglass.Hubspot.Integration.Console.dll!Metroglass.Hubspot.Integration.Console.Program.ProcessMessagesAsync(Microsoft.Azure.ServiceBus.Message message, System.Threading.CancellationToken token) Line 76	C#	Non-user code. Symbols loaded.
 	[Resuming Async Method]		Annotated Frame
 	System.Private.CoreLib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown	No symbols loaded.
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.OutputAsyncCausalityEvents.AnonymousMethod__0()	Unknown	No symbols loaded.
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__0()	Unknown	No symbols loaded.
 	System.Private.CoreLib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action action, bool allowInlining, ref System.Threading.Tasks.Task currentTask)	Unknown	No symbols loaded.
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task.RunContinuations(object continuationObject)	Unknown	No symbols loaded.
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task<System.Threading.Tasks.VoidTaskResult>.TrySetResult(System.Threading.Tasks.VoidTaskResult result)	Unknown	No symbols loaded.
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.SetExistingTaskResult(System.Threading.Tasks.VoidTaskResult result)	Unknown	No symbols loaded.
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.SetResult(System.Threading.Tasks.Task<System.Threading.Tasks.VoidTaskResult> completedTask)	Unknown	No symbols loaded.
 	Microsoft.Azure.ServiceBus.dll!Microsoft.Azure.ServiceBus.Core.MessageReceiver.CompleteAsync(System.Collections.Generic.IEnumerable<string> lockTokens) Line 441	C#	Non-user code. Symbols loaded.
 	[Resuming Async Method]		Annotated Frame
 	System.Private.CoreLib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown	No symbols loaded.
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.OutputAsyncCausalityEvents.AnonymousMethod__0()	Unknown	No symbols loaded.
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__0()	Unknown	No symbols loaded.
 	System.Private.CoreLib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action action, bool allowInlining, ref System.Threading.Tasks.Task currentTask)	Unknown	No symbols loaded.
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task.RunContinuations(object continuationObject)	Unknown	No symbols loaded.
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task<System.Threading.Tasks.VoidTaskResult>.TrySetResult(System.Threading.Tasks.VoidTaskResult result)	Unknown	No symbols loaded.
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.SetExistingTaskResult(System.Threading.Tasks.VoidTaskResult result)	Unknown	No symbols loaded.
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.SetResult(System.Threading.Tasks.Task<System.Threading.Tasks.VoidTaskResult> completedTask)	Unknown	No symbols loaded.
 	Microsoft.Azure.ServiceBus.dll!Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(System.Func<System.Threading.Tasks.Task> operation, System.TimeSpan operationTimeout) Line 106	C#	Non-user code. Symbols loaded.
 	[Resuming Async Method]		Annotated Frame
 	System.Private.CoreLib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown	No symbols loaded.
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.OutputAsyncCausalityEvents.AnonymousMethod__0()	Unknown	No symbols loaded.
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__0()	Unknown	No symbols loaded.
 	System.Private.CoreLib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action action, bool allowInlining, ref System.Threading.Tasks.Task currentTask)	Unknown	No symbols loaded.
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task.RunContinuations(object continuationObject)	Unknown	No symbols loaded.
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task<System.Threading.Tasks.VoidTaskResult>.TrySetResult(System.Threading.Tasks.VoidTaskResult result)	Unknown	No symbols loaded.
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.SetExistingTaskResult(System.Threading.Tasks.VoidTaskResult result)	Unknown	No symbols loaded.
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.SetResult(System.Threading.Tasks.Task<System.Threading.Tasks.VoidTaskResult> completedTask)	Unknown	No symbols loaded.
 	Microsoft.Azure.ServiceBus.dll!Microsoft.Azure.ServiceBus.Core.MessageReceiver.DisposeMessagesAsync(System.Collections.Generic.IEnumerable<System.Guid> lockTokens, Microsoft.Azure.Amqp.Framing.Outcome outcome) Line 1217	C#	Non-user code. Symbols loaded.
 	[Resuming Async Method]		Annotated Frame
 	System.Private.CoreLib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown	No symbols loaded.
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.OutputAsyncCausalityEvents.AnonymousMethod__0()	Unknown	No symbols loaded.
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__0()	Unknown	No symbols loaded.
 	System.Private.CoreLib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action action, bool allowInlining, ref System.Threading.Tasks.Task currentTask)	Unknown	No symbols loaded.
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task.RunContinuations(object continuationObject)	Unknown	No symbols loaded.
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task<System.__Canon>.TrySetResult(System.__Canon result)	Unknown	No symbols loaded.
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task.WhenAllPromise<Microsoft.Azure.Amqp.Framing.Outcome>.Invoke(System.Threading.Tasks.Task ignored)	Unknown	No symbols loaded.
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task.RunContinuations(object continuationObject)	Unknown	No symbols loaded.
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task<System.__Canon>.TrySetResult(System.__Canon result)	Unknown	No symbols loaded.
 	System.Private.CoreLib.dll!System.Threading.Tasks.TaskFactory<System.__Canon>.FromAsyncCoreLogic(System.IAsyncResult iar, System.Func<System.IAsyncResult, System.__Canon> endFunction, System.Action<System.IAsyncResult> endAction, System.Threading.Tasks.Task<System.__Canon> promise, bool requiresSynchronization)	Unknown	No symbols loaded.
 	System.Private.CoreLib.dll!System.Threading.Tasks.TaskFactory<Microsoft.Azure.Amqp.Framing.Outcome>.FromAsyncImpl.AnonymousMethod__0(System.IAsyncResult iar)	Unknown	No symbols loaded.
 	Microsoft.Azure.Amqp.dll!Microsoft.Azure.Amqp.AsyncResult.TryComplete(bool didCompleteSynchronously, System.Exception exception)	Unknown	No symbols loaded.
 	Microsoft.Azure.Amqp.dll!Microsoft.Azure.Amqp.AsyncResult.Complete(bool didCompleteSynchronously, System.Exception e)	Unknown	No symbols loaded.
 	System.Private.CoreLib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown	No symbols loaded.
 	System.Private.CoreLib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch()	Unknown	No symbols loaded.
 	[Async Call]		Annotated Frame
 	Microsoft.Azure.ServiceBus.dll!Microsoft.Azure.ServiceBus.Primitives.TaskExtensionHelper.Schedule.AnonymousMethod__0() Line 17	C#	Symbols loaded.

**Comment by nick-goloborodko** [comment]
UPDATE:

Deleteing .vs folder from the solution folder resolved the issue.
