### ISSUE TITLE
Number of concurrent connections doc

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus#11]
## Description

There's some discrepancy with the documentation about the number of concurrent connections on a  queues/topics/subscription.

[One source](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-quotas) states

>Capped by the limit of concurrent connections per namespace.

[Another source](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-faq#quotas) says

> The number of concurrent TCP connections on a queue/topic/subscription is limited to 100.

## Required actions

1. Clarify and update the doco
1. Should [FAQ document](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-faq) provide quota details or rather redirect to the [quotas document](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-quotas)?

Thank you.

**Comment by SeanFeldman** [comment]
cc @sethmanheim @jtaubensee

**Comment by jtaubensee** [comment]
@sethmanheim - @SeanFeldman is correct, there is not actually a limit on the number of connections to a particular entity. Can you remove this part in the Quotas page:

> Number of concurrent connections on a queue/topic/subscription entity

I think that actually makes things more confusing, as the gist is that we only limit the number of connections at the namespace level.

**Comment by sethmanheim** [comment]
@jtaubensee Sure, I can do that -- what about the FAQ entry? Shouldn't that also be removed?

**Comment by jtaubensee** [comment]
Yes please. Actually @SeanFeldman has a good point. Let's just have the FAQ forward to the quotas page. Thank you!

**Comment by sethmanheim** [comment]
Closing as this work is done.
