### ISSUE TITLE
[server-side batching] message lost risk?

### ISSUE THREAD

**Issue by mloho** [Azure/azure-service-bus#110]
[Reference](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-performance-improvements#batching-store-access)
>If batching is enabled for an entity, Service Bus delays a store write operation regarding that entity by up to 20ms.

Is there a risk in losing messages if the Service Bus instance dies before it could write to the internal store at the end of a 20ms batching interval?

**Comment by ChristianWolf42** [comment]
@mloho There is no risk for message loss with batching. This article is outdated. We will update it soon.

**Comment by sethmanheim** [comment]
Adding a note to this article:

There is no risk of losing messages with batching, even if there is a Service Bus failure at the end of a 20ms batching interval.

**Comment by SeanFeldman** [comment]
@sethmanheim just a suggestion - to close issues when an appropreate PR is merged. Happened to me in the past that I was planning to make a change, but didn't get to it 🙂 It's also could be closed with a link to the commit that fixed the issue.

**Comment by sethmanheim** [comment]
@SeanFeldman Don't worry, that will never happen. :-) You'll see it in the live docs by tomorrow probably.

**Comment by SeanFeldman** [comment]
@sethmanheim haha, never say never 😉
Jokes aside, having a a link in the closing message to the commit that fixed the issue is always nice.

**Comment by sethmanheim** [comment]
You are right. I will try -- it's just a little tricky playing between public repo issues and our internal bug tracking. Not your problem though -- I'll try to keep these updated.

**Comment by SeanFeldman** [comment]
I know I'm somewhat of a PITA @sethmanheim. Sorry for that. Hope that one time when that link will become useful will excuse my stubborness 😆

**Comment by sethmanheim** [comment]
I have Aussie friends too: "no worries mate," please keep the feedback coming! :-)
