### ISSUE TITLE
Domain names possible for Azure Service Bus endpoints

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus#111]
A well known domain name is `servicebus.windows.net`. Everything else is not listed anywhere.
E.g. `servicebus.usgovcloudapi.net`, `servicebus.cloudapi.de` or `servicebus.chinacloudapi.cn`.

Could you please post a complete list and perhaps document it?
/cc @sethmanheim

**Comment by ChristianWolf42** [comment]
@SeanFeldman I will see if I can get a blog out in the next few days.

**Comment by sethmanheim** [comment]
Filed doc bug 1182804.

**Comment by ChristianWolf42** [comment]
@sethmanheim and @SeanFeldman here is the domains:
Black forest: servicebus.cloudapi.de
China: servicebus.chinacloudapi.cn
US Government: servicebus.usgovcloudapi.net
Public cloud: servicebus.windows.net
That is all we have externally accessible right now.

**Comment by sethmanheim** [comment]
Thanks -- I'll add that info here: https://docs.microsoft.com/en-us/rest/api/servicebus/.

**Comment by sethmanheim** [comment]
Done.
