### ISSUE TITLE
Unable to complete a message. 

### ISSUE THREAD

**Issue by Bo-Yee-Woods** [Azure/azure-service-bus#113]
My project is a UWP application. I follow the guideline of this link. URL: 
https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/BasicSessionSendReceiveUsingQueueClient. 

Then I got a problem. The Message does not complete when I call 'session.CompleteAsync'. Message is still in queue until it runs out of its maximum delivery count.

        private async Task ProcessSessionMessagesAsync(IMessageSession session, Message message, CancellationToken token)
        {
               var sessionId = session.SessionId;
               var sequenceNumber = message.SystemProperties.SequenceNumber;
               var messageId = message.MessageId;
               var messageBody = Encoding.UTF8.GetString(message.Body);
               await session.CompleteAsync(message.SystemProperties.LockToken);
        }

**Comment by ChristianWolf42** [comment]
@Bo-Yee-Woods we will look into this and get back to you. Is there any exception message you get which you could share with us when you call complete?

**Comment by axisc** [comment]
@Bo-Yee-Woods please consider updating to the latest version of the SDK and please create a new issue if the issue persists.
