### ISSUE TITLE
How to test code that handles incoming messages?

### ISSUE THREAD

**Issue by rytmis** [Azure/azure-service-bus#114]
I'm writing some infrastructure code that receives Service Bus messages via an ISubscriptionClient. In order to complete, abandon or deadletter the messages, the code needs a lock token, and I'd like to verify that the code is passing in the lock token from the message. 

Problem is, I can't create a message that has a lock token, because the relevant setters are internal, and trying to even read the token for a message I've constructed myself will cause an exception.

I can sort-of work around this by having the receiver be aware of messages that haven't been received, and then passing in a fake lock token, but it's far from ideal.

**Comment by clemensv** [comment]
This is a case where the client library intentionally uses "internal" to prevent developers from doing what you're trying to do. The system properties communicate information that is exclusively set by the broker, and it were confusing (read: causing support calls) if we made those properties settable for regular user code.

What would you propose as a fix?

**Comment by rytmis** [comment]
Yeah, I figured that would be the case. 

Other than having some sort of factory method explicitly named so you'd know it's for testing purposes, I don't know -- I was hoping there'd already be a solution thought up by someone smarter than me. 😉

**Comment by SeanFeldman** [comment]
@rytmis that factory would not be a part of the main package as it would be solely for a testing purpose. Personally, I'd like to see a clean separation between production and testing code.

**Comment by rytmis** [comment]
Sure, yes, that makes sense. How likely do you think such a package would be? I mean, if I'm reading this correctly, at this point it would be solely for that single factory, which seems a bit much to ask from you guys. :) Of course, I can always kludge around this by having a factory of my own that reflects for the underlying lock token field and sets it to something -- not pretty, but doable.

**Comment by clemensv** [comment]
The risk with a separate package that can see the internals of the main package that this "test package" will inevitably end up in some genius's production code if it's too useful :)

**Comment by rytmis** [comment]
Welp, I suppose that means I'll take the reflection route for my tests. Thanks for taking the time to answer. :)

**Comment by SeanFeldman** [comment]
> The risk with a separate package that can see the internals of the main package that this "test package" will inevitably end up in some genius's production code if it's too useful :)

@clemensv you're 100% correct. Nothing would prevent the same genious from following a reflection path @rytmis has mentioned. I guess for myself, if I'd see something named `Microsoft.Azure.ServiceBus.Testing` in production deployment would raise alarms 😃
