### ISSUE TITLE
Transaction Message Limit Inconsistancies

### ISSUE THREAD

**Issue by JustinWilliams-VSCM** [Azure/azure-service-bus#115]
# Description
Only 100 messages are allowed per transaction when writing to the service bus using Send(), but this limit isn't enforced when using SendAsync(). 

## Actual Behavior
1. sender.Send() throws exception after 100 messages have been sent
2. sender.SendAsync() does not throw and exception after 100 messages have been sent

## Expected Behavior
1. No limit should be enforced or both functions enforce this behavior

**Comment by SeanFeldman** [comment]
@JustinWilliams-VSCM could you share your repro code?

**Comment by SeanFeldman** [comment]
Also, what version of the client you're using.

**Comment by JustinWilliams-VSCM** [comment]
I am currently using v4.1.6 and I'll try to get a repo put together.

Can you answer why there is a limit of 100 messages per transaction?

**Comment by SeanFeldman** [comment]
> Can you answer why there is a limit of 100 messages per transaction?

I can't. That's a design decision taken by the product team. /cc @ ChristianWolf42 @clemensv 

This is a broker related feature, which is [not documented](https://weblogs.asp.net/sfeldman/azure-service-bus-number-of-messages-in-a-single-transaction) that well IMO. Has most likely to do with how [transport transactions](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-transactions) are handled on the broker side. When you use a transaction, you're staging all the sent messages on a transfer queue. This is probably not an easy task. The more messages you get, the higher risk (I wildly assume here) of complexity and things failing.

**Comment by ChristianWolf42** [comment]
@JustinWilliams-VSCM, we actually do have a limit in our service for 100 messages max per transaction. Both functions should throw the same error. If you don't see that can it be that you are still awaiting the send at some point while using sendasync?
Can you please share the code you use to reproduce for us? We want to make sure we do the exact same steps then you.

**Comment by JustinWilliams-VSCM** [comment]
@ChristianWolf42  and @SeanFeldman,

Please take a look at https://github.com/JustinWilliams-VSCM/Service-Bus-Transaction-Example

1. ServiceBusSample.sln contains all the code linked as existing projects
2. You will need to put your own connection strings
3. I did try to refactor the code in the above example but that lead to speed and transaction size issues

I apologize for the late response, I went on vacation right after I opened this issue.

**Comment by SeanFeldman** [comment]
@JustinWilliams-VSCM I'm gone for my vacation, but will be back on 23rd. if no one picks it up by then I can look into that.

**Comment by sethmanheim** [comment]
Don't see any documentation issues here so removing that tag. Please update if you have more information.

**Comment by sethmanheim** [comment]
OK, filed PG team bug 2114789. I'll also add this to the quotas doc (https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-quotas).
