### ISSUE TITLE
"default" subscription for unmatched messages

### ISSUE THREAD

**Issue by jtaubensee** [Azure/azure-service-bus#12]
# Description
Feature request to provide a default "catch all" subscription for Service Bus that will match any messages that are not matched by other subscriptions. This is different than the default true filter which will match all messages. Instead this will only catch messages that aren't matched by anything else.

**Comment by SeanFeldman** [comment]
Feature name: wiretap 😃 

Some questions related to the feature:
1. Will those message have an auto-retention period and automatically get removed?
1. Will it be opt-in or opt-out model?

**Comment by EldertGrootenboer** [comment]
This request is similar to https://github.com/Azure/azure-service-bus/issues/277, so will close this one. We have added the requested feature to the backlog, and are tracking this on the linked issue.
