### ISSUE TITLE
WindowsAzure.ServiceBus 4.2.0-preview

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus#125]
Current release notes contain the following:
> EventHubs/ServiceBus: (Preview) support Role-Based Access Control and Managed Service Identity.

Would it be possible to link nuget package release note to the documentation?
The old package is closed source and it's hard to determine what was added API wise.
Thank you.

**Comment by ChristianWolf42** [comment]
@SeanFeldman so that goes back to our discussion the other day of labeling and describing fixes and packages better for our old library?

**Comment by SeanFeldman** [comment]
Correct.
This one is for the old client library though.

**Comment by ChristianWolf42** [comment]
@SeanFeldman discussing with the team and will get back to you.
