### ISSUE TITLE
Tracking issue for backend issue with AuthComponent open fix

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus#136]
A workaround is required for [MSI sample](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.ServiceBus.Messaging/ManagedServiceIdentity) to run.

```c#
// TODO - Remove after backend is patched with the AuthComponent open fix
messagingFactorySettings.AmqpTransportSettings.EnableLinkRedirect = false;
```

Once backend issue is resolved this tracking issue can be closed.

**Comment by ChristianWolf42** [comment]
Will verify for SB and then get back to this thread

**Comment by ChristianWolf42** [comment]
This is fixed in service bus. Updating sample.

**Comment by SeanFeldman** [comment]
It's a matter of personal preferences. Personally, I'd create a PR for sample that says "Fixes issue <this issue>" and close this issue when PR is merged 😃

**Comment by ChristianWolf42** [comment]
Well, merged it is :)

**Comment by SeanFeldman** [comment]
🎉
