### ISSUE TITLE
Microsoft.Azure.ServiceBus - Rules Creation for Topic Subscriptions

### ISSUE THREAD

**Issue by arunkumaresan** [Azure/azure-service-bus#138]
## Actual Behavior
1. Creating Rules in Topic Subscription needs Topic in Enabled Mode
## Expected Behavior
1. Rules creating should be allowed when Topic Subscriptions are in Disabled mode also. Mostly preferred for business cases

**Comment by binzywu** [comment]
@arunkumaresan  mind to elaborating a little more of business cases?

**Comment by arunkumaresan** [comment]
For eg:
Microsoft.ServiceBus.Messaging in WindowsAzure.ServiceBus would allow creating rules for Topic Subscriptions even they are Disabled. The Microsoft.Azure.ServiceBus will not allow the same. The Topic Subscription should be in Enabled mode.

The former scenario is much liked, as the admin can create rules after disabling the entity and then enable it. This gives more control.

Am I overlooking something in terms of implementation in the new client? There are not enough documentation in such scenario, if the architecture is being changed

**Comment by EldertGrootenboer** [comment]
Could not be replicated with latest SDK, therefor closing this issue.
