### ISSUE TITLE
Receive messages for specific session in Active Replication

### ISSUE THREAD

**Issue by info4gourav** [Azure/azure-service-bus#142]
I am working on Active Replication. It works fine  for Default Queue (No Partition, No Session Enabled).
But when I use PartitonQueue(Session Enabled) then I am not getting messages in order(FIFO) for a specific session. I am using ResgisterSessionHandler for two queueclients.

How can I maintain message order(using Queue - Session Enabled) in Active Replication.

**Comment by ChristianWolf42** [comment]
@info4gourav can you send us code to reproduce the issue please?

**Comment by nemakam** [comment]
@info4gourav 
Just to be on the same page,
All messages with the same sessionID will be in order. Messages across different sessionID will not necessarily be in order.

**Comment by sxd63870** [comment]
@nemakam 
Do you have any sample example to Listen to messages to with same sessionID using subscription client.
e.g 
Instance1
messageSession = subscriptionClient.AcceptMessageSession("session1")
messageSession.OnMessage(callback,options) - this callback will listen to messages with particular sessionID (session1)
Instance2
messageSession = subscriptionClient.AcceptMessageSession("session2")
messageSession.OnMessage(callback,options) - this callback will listen to messages with particular sessionID (session2)
