### ISSUE TITLE
Optimizing PrefetchCount with ReceiveBatch Size

### ISSUE THREAD

**Issue by ElliotSchmelliot** [Azure/azure-service-bus#143]
Is it beneficial to use PrefetchCount when using ReceiveBatch? I am not seeing any documentation on how to determine a recommended PrefetchCount in relation to ReceiveBatch size.

From the [Prefetching optimization](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-performance-improvements#prefetching) docs:
> When using the default lock expiration of 60 seconds, a good value for SubscriptionClient.PrefetchCount is 20 times the maximum processing rates of all receivers of the factory. For example, a factory creates 3 receivers, and each receiver can process up to 10 messages per second. The prefetch count should not exceed 20 X 3 X 10 = 600. By default, QueueClient.PrefetchCount is set to 0, which means that no additional messages are fetched from the service.

Due to the fact that ReceiveBatch is not guaranteed to return an exact number of messages and that the number returned can vary greatly, I am finding it difficult to determine the receiver's "messages per second."

**Comment by SeanFeldman** [comment]
@ChristianWolf42 this is kind of documentation/guidance that is missing ATM.

**Comment by ChristianWolf42** [comment]
We are refreshing our documentation right now. I put this thread on the todo list.

**Comment by batizar** [comment]
@ChristianWolf42 any updates regarding this? cheers

**Comment by ChristianWolf42** [comment]
Adding @axisc the new Service Bus PM

**Comment by SeanFeldman** [comment]
And @axisc's free time is over as of this moment.

**Comment by axisc** [comment]
Apologies for the delay on this.

To start with the basics, Prefetch is a configuration (or mode) on the client and Receive is an operation (that has request-response semantics). They are different concepts that can be looped in together.

Thumb rule
   * Prefetch should be greater than or equal to the number of messages you are expecting to receive from ReceiveBatch.
   * Prefetch can be upto n/3 times the per second message count, where n is the default lock duration (i.e. 60 seconds, which is how we got to 20 seconds)

To be honest, these are mainly empirical values and I recommend trying out different configurations of 'Prefetch' and 'ReceiveBatch(int)' to see what gives you the best result.

@ElliotSchmelliot - to your original question on not being able to identify the number of messages receiver can process per second, this is based on your application process (i.e. function of compute and not of the broker).

I'll add these to the doc too.

**Comment by axisc** [comment]
made the changes to the doc - will be updated in the next push
