### ISSUE TITLE
Library does not appear compatible with messages sent using WindowsAzure.ServiceBus

### ISSUE THREAD

**Issue by apariciom** [Azure/azure-service-bus#144]
# Description

I'm using WindowsAzure.ServiceBus to send messages to a Service Bus queue. 

I'm listening to the queue using the library, Microsoft.Azure.ServiceBus

Getting string from body returns

## Actual Behavior
1. @string3http://schemas.microsoft.com/2003/10/Serialization/�){"key":"value"}

## Expected Behavior
1.  {"key":"value"}

Note: this also happens when using a job in Azure Scheduler to push messages onto a Service Bus queue.

**Comment by nemakam** [comment]
@apariciom 
Take a look at this solution https://github.com/Azure/azure-service-bus-dotnet/issues/239#issuecomment-320820562
