### ISSUE TITLE
Azure Service Bus IQueueClient.registerSessionHandler: Unable to consume messages continuously from Queue/Topic

### ISSUE THREAD

**Issue by abhikt48** [Azure/azure-service-bus#146]
***Requirement***: I need to get all the messages from all the sessions from the queue. `registerSessionHandler` should consume messages as soon as they appear in the queue.

***Issue***: the code accepts the messages that are pertaining to one of the session id (xyz) and then it just waits. And even when more messages are pushed with that session id (xyz), it fails to consume it.

> Any suggestions - what obvious thing I am missing here.

 

I have `registerSessionHandler` for receiving session messages continuously from the queue. Whenever i start new session, i am getting message of only one `sessionID`. 

*Test Queue*: In this queue, there are 20 messages available with 4 different sessionIDs. Whenever i run Java application (`QueueSessionReceiveTest.java`), i get only 5 messages which is associated with single session ID. 

>MAVEN - azure-servicebus - 1.1.1

> RECEIVE CODE:

    import java.time.Duration;
    import com.microsoft.azure.servicebus.IMessage;
    import com.microsoft.azure.servicebus.IQueueClient;
    import com.microsoft.azure.servicebus.QueueClient;
    import com.microsoft.azure.servicebus.ReceiveMode;
    import com.microsoft.azure.servicebus.SessionHandlerOptions;
    import com.microsoft.azure.servicebus.primitives.ConnectionStringBuilder;
    public class QueueSessionReceiveTest {
    	private static final String connectionString = "Endpoint=sb://XXXXXX";
        private static final String queueName = "test";
        private static IQueueClient queueClient;
        public static void main(String[] args) throws Exception {
        	queueClient = new QueueClient(new ConnectionStringBuilder(connectionString, queueName), ReceiveMode.PEEKLOCK);
        	queueClient.registerSessionHandler(new QueueMessageSessionHandler(), new SessionHandlerOptions(1, false, Duration.ofMinutes(1)));        	
        	}}

> SESSION HANDLER CODE:

    import java.util.concurrent.CompletableFuture;
    import com.microsoft.azure.servicebus.ExceptionPhase;
    import com.microsoft.azure.servicebus.IMessage;
    import com.microsoft.azure.servicebus.IMessageSession;
    import com.microsoft.azure.servicebus.IQueueClient;
    import com.microsoft.azure.servicebus.ISessionHandler;
    public class QueueMessageSessionHandler implements ISessionHandler {
    	@Override
    	public CompletableFuture<Void> onMessageAsync(IMessageSession session, IMessage iMessage) {
    		return session.completeAsync(iMessage.getLockToken()).thenRunAsync(() -> Logger.debug("some log") );
    	}
    	@Override
    	public CompletableFuture<Void> OnCloseSessionAsync(IMessageSession session) {
    		return null;
    	}
    	@Override
    	public void notifyException(Throwable exception, ExceptionPhase exceptionPhase) {
            // Do nothing
    	}}

**Comment by nemakam** [comment]
@abhikt48 
From the interface perspective, the moment you give `new SessionHandlerOptions(1, false, Duration.ofMinutes(1))` it would not try to accept more than 1 session at any time and it would wait for at least `operationTimeout` time before it can attempt receiving from next session. 

How long do you wait before you conclude that you are not receiving the messages? If you need to receive the message immediately, one of the easiest way is to increase the concurrent session count. 

Since this is specific to java client, Could you please move the issue to https://github.com/Azure/azure-service-bus-java if you still have more questions?

**Comment by abhikt48** [comment]
@nemakam  Thanks for your reply.  I opened New Issue Link - https://github.com/Azure/azure-service-bus-java/issues/187
