### ISSUE TITLE
QueueClient.Peek() should not work when ServiceBus is unavailable

### ISSUE THREAD

**Issue by mjeson** [Azure/azure-service-bus#147]
# Description
Steps to reproduce:
1. Make a queue unavailable (e.g. disable it)
2. Run the following code (using Microsoft.ServiceBus.Messaging)
```
        QueueClient queueClient = QueueClient.CreateFromConnectionString(ConnectionString);
        BrokeredMessage message = queueClient.Peek(); //works
        message = queueClient.Receive(TimeSpan.Zero); //throws an exception
```

I am using WindowsAzure.ServiceBus.4.1.7

## Actual Behavior
1. Peek() does not throw exception
2. Receive() throws exception

## Expected Behavior
1. Both Peek() and Receive() should throw exception when ServiceBus is unavailable. Peek() intuitively promise to behave similar to Receive() minus dequeueing it. Having Peek() works but Receive() does not is confusing. 

2. Alternatively, provide a separate method to check for ServiceBus availability.

**Comment by binzywu** [comment]
Peek is browsing not receive without dequeue. What is your scenario here? To get service bus entity status you could just get entity info.

**Comment by binzywu** [comment]
In fact, in our new open source library, this method is named as browse now.

**Comment by mjeson** [comment]
My scenario is to create a method to check whether an ASB queue is online. More info here:  https://stackoverflow.com/questions/48816878/how-to-check-azureservicebus-availability

Do you have the link or example to use browse method ?

**Comment by SeanFeldman** [comment]
@binzywu management operations are not available with the new client. Unless you refer to the future `NamespaceManager` replacement library.

**Comment by jayasri341** [comment]
How to read the message from the service bus dead-letter queue? I'm able to read message-id and a sequence number of the message, but I need the actual message. Can someone help me with this?
Is it possible to read the actual message?

**Comment by SeanFeldman** [comment]
@jayasri341 wrong repository. Please review `README.md`.
