### ISSUE TITLE
SubscriptionClient creation can be very slow behind firewalls

### ISSUE THREAD

**Issue by pseabury** [Azure/azure-service-bus#151]
Package : WindowsAzure.ServiceBus 
Version: 4.1.6
Class: Microsoft.ServiceBus.Messaging.SubscriptionClient

Calling `SubscriptionClient.CreateFromConnectionString(...)` when in a network environment that only allows outbound http/s takes roughly 20s to complete the connection setup.  My guess is that this is due to the transport probing/fallback mechanism related to the `ConnectivityMode.AutoDetect`.  In this environment, if I set `ServiceBusEnvironment.SystemConnectivity.Mode = ConnectivityMode.Https;` explicitly, then the client creation takes roughly 1s.  

Can the AutoDetect probing be improved in this scenario to fail fast over to the other transports?  20s seems like a long time.

See https://stackoverflow.com/questions/44239942/azure-service-bus-long-time-to-create-a-client 

Paul

**Comment by ChristianWolf42** [comment]
@pseabury that is expected behavior. Without explicit connection setting we have to do probing which takes time. The workaround is exactly what you do (setting the connectivity mode as you know it based of your network setup.)
