### ISSUE TITLE
Prefetching and message lock

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus#152]
This is more of a question / discussion. Not sure if this is a client issue or not, so will post it here first.

When messages are prefetched by ASB client, they are "cached" on the receiver side. When a client callback (OnMessage API) is getting to a message, there's a chance that lock duration has elapsed and message will go through callback processing just to get `LockLostException`. What's also making things somewhat confusing is the AutoRenewTimeout which _only_ applies to a message passed into client callback **and** its lock wasn't lost yet.

Is there a way to indicate that a message passed into a client callback either lost its lock or `LockDuration` soon to elapse? Brokered message has a `LockedUntilUtc` system property, but I'm not sure if that would contain a value from the moment a message left the broker or from the moment it was passed to the callback.

**Comment by nemakam** [comment]
> When messages are prefetched by ASB client, they are "cached" on the receiver side. 

Correct.

> When a client callback (OnMessage API) is getting to a message, there's a chance that lock duration has elapsed and message will go through callback processing just to get LockLostException. 

In the new client, the client should filter out expired messages before giving the message to the user. 

> What's also making things somewhat confusing is the AutoRenewTimeout which only applies to a message passed into client callback and its lock wasn't lost yet.

Correct. This is required to avoid situations where people might have configured insane value of prefetch  and hence the messages won't even be delivered to the other receivers. 

> Is there a way to indicate that a message passed into a client callback either lost its lock or LockDuration soon to elapse? Brokered message has a LockedUntilUtc system property, but I'm not sure if that would contain a value from the moment a message left the broker or from the moment it was passed to the callback.

Yes. `LockedUntilUtc` is the right property to take a look at. It is stamped by the broker. As name suggests it is the UTC value till when the message lock is valid. 

Ideally, I'd say if you are ending up in situation where lot of locks are being lost, that generally means you have a prefetch value greater than what your service can handle.

**Comment by SeanFeldman** [comment]
> In the new client, the client should filter out expired messages before giving the message to the user.

Does that mean `DeliveryCount` of those messages will be incremented or that's not the case?

@nemakam if I understand correctly, you're saying that in the **new** client, user callback will never be given a message that has lost its lock. Is that correct?

**Comment by nemakam** [comment]
@SeanFeldman 
Sorry for the confusion. We have **removed** the functionality of filtering out expired messages. See https://github.com/Azure/azure-service-bus-dotnet/pull/351 
So as of now, it is the user's responsibility to not work on it if the messages are already expired by the time it has been delivered. 

And yes, when the lock expires, `DeliveryCount` is increased

**Comment by SeanFeldman** [comment]
Thanks @nemakam. I can see how this filtering could be a negative affect. Especially when delivery count is incremented while client callback is not executed. Evaluating `LockedUntilUtc` early in the client callback seems to be an option to at least identify potential issues.

Thank you.

**Comment by SeanFeldman** [comment]
Thinking out loud - perhaps this should be left in but control given to users to decide what the behavior should be (allow override).

**Comment by nemakam** [comment]
@SeanFeldman 
I did think about that, but one of the main reasons why this change was taken out was to avoid issues related to mismatch in system clock skew. Even if we allow this override there is no way a user can easily answer whether he should use the override it or not (since clock skew can happen to anyone).

**Comment by SeanFeldman** [comment]
That's true. There's no way to know there's a clock skew. With `LockedUntilUtc` the problem of clock skew is still not resolved. Only unnecessary message processing. And potentially providing feedback to differentiate better between general lock loss and specifically when message got to the processing late in the game.
