### ISSUE TITLE
GeoDR: Not able to create subscription with forward to when connected to alias

### ISSUE THREAD

**Issue by acerock** [Azure/azure-service-bus#153]
After testing our systems running on a Geo DR service bus set-up, it looks like I've found this bug. 
We have a service creating subscriptions (on demand) with an auto-forward rules to queues. 
This works fine when the service is using the primary sb connection string but fails once configured to use the alias. 

The problem can be reproduced using Service Bus Explorer:
1. Connect using the alias connection string
2. Create a queue
3. Create a topic
4. Create a subscription with "forward to" the queue

Step 4. fails with (500) Internal Server Error:  "The auto forwarding destination entity does not exist."

It will work as expected when connected using the primary sb connection string.

**Comment by ChristianWolf42** [comment]
The fix for that should be released in the next two weeks.
