### ISSUE TITLE
BrokeredMessage.Abandon() with support for ScheduledEnqueueTimeUtc

### ISSUE THREAD

**Issue by dominiquelee** [Azure/azure-service-bus#156]
It's possible to requeue a message with a new ScheduledEnqueueTimeUtc by completing the message and crafting and sending a new message. This requires SAS-access to a MessageSender.
On the other hand, without access to a MessageSender, the only way to requeue a message is to abandon it and it's then immediately requeued.

Having the possibility to update ScheduledEnqueueTimeUtc would help in throttling messages when we temporarily can't process them.

PS: as far as I know, this is not supported by PropertiesToModify, is that right?

**Comment by nemakam** [comment]
@dominiquelee 
Yes. This is not a supported feature as of now.
Does `receiver.defer()` and `receiveDeferredMessage()` work out for you?

**Comment by dominiquelee** [comment]
Thanks. I guess message deferral could work, but it implies:
- making the reader stateful,
- in case of multiple readers, it binds the message to a particular reader for no good reason.

**Comment by SeanFeldman** [comment]
👍 for this feature. Deferring means adding persistence for `SequenceNumber`. Feels very forced.
This feature has been requested by many (https://github.com/Azure/azure-service-bus-dotnet/issues/52 and it would be grateful to see it supported 🙂

**Comment by SeanFeldman** [comment]
@binzywu is this something we'd see in the near-ish future? Thank you.

**Comment by funkycoding** [comment]
Any updates on this? 😇

**Comment by EldertGrootenboer** [comment]
The described request is similar to https://github.com/Azure/azure-service-bus/issues/454, so will close this issue. We have added the request to our backlog, and are tracking this in the linked issue.
