### ISSUE TITLE
Document filtering options for NamespaceManager.GetRulesAsync() /.GetQueuesAsync() / .GetSubscriptionsAsync() / .GetTopicsAsync with filter parameter

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus#16]
Related to #15.

Currently, there's zero documentation out there. The syntax for filters is not documented and seem to vary between entity types:

```c#
manager.GetQueuesAsync("startswith(path, '$#_') eq true")
```
works for a queue, but an expression
```
"startswith(name, 'rule1') eq true"
```
would not work for Rules.

**Comment by sethmanheim** [comment]
Thanks Sean, we're working on getting this information from the development team.

**Comment by SeanFeldman** [comment]
> we're working on getting this information from the development team

Looking at your avatar, you're quite equipped for an info extraction 😜 

![image](https://cloud.githubusercontent.com/assets/1309622/25150413/0bb5868a-243f-11e7-9083-9e28dc0a3117.png)

**Comment by SeanFeldman** [comment]
ping

**Comment by jtaubensee** [comment]
@SeanFeldman - I'm taking this one, but it will be a little bit before the reference documentation is updated accordingly.

**Comment by SeanFeldman** [comment]
👍

**Comment by SeanFeldman** [comment]
@hmlam do you know who can help with this? Thanks.

**Comment by mattdone01** [comment]
GetRulesAsync() was added to the new ServiceBus client in https://github.com/Azure/azure-service-bus-dotnet/pull/192 . Is this something that will be generally available. Not being able to check for the existence of a rule is frustrating. Thanks

**Comment by sethmanheim** [comment]
John made these updates before he left.

**Comment by SeanFeldman** [comment]
👍 xmldoc remarks are showing up on [docs.microsoft.com](https://docs.microsoft.com/en-ca//dotnet/api/microsoft.servicebus.namespacemanager.getrulesasync).
