### ISSUE TITLE
Explicite message receive and browse

### ISSUE THREAD

**Issue by ddobric** [Azure/azure-service-bus#165]
It would be important to have following methods on all clients:

ReceiveMessage
ReceiveMessageAsync
PeekMessagesAsync
PeekMessagesAsync

+related batch methods

There are many scenarios, which cannot be implemented by using of currently supported "OnMessageReceive" pattern.

**Comment by SeanFeldman** [comment]
@ddobric those are supported afaik.
Are you referring to the **new** client?

**Comment by ChristianWolf42** [comment]
@ddobric So right now we allow all that but if you want to bypass the receive pump you need to go to the Microsoft.Azure.ServiceBus.Core library. Wouldn't that be sufficient?
