### ISSUE TITLE
Better documentation of Premium tier

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus#17]
## Partitioning

[Documentation](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-premium-messaging) doesn't explicitly state what seems to be the behavior - Premium tier entities are always partitioned.

> Having two partitions ensures availability and is a more appropriate number for the Premium runtime environment.

Is sort of hinting at that, but documentation should be explicit and clear.

## Individual queue size

With Standard tier partitioning is required to have more than 5GB queue. With Premium entities, despite having only 2 partitions, one can set the size up to 80GB.

## Summary

It would be nice to have these kind of things documented.

**Comment by SeanFeldman** [comment]
@sethmanheim would you be able to get this going? Thank you.

**Comment by sethmanheim** [comment]
@SeanFeldman @jtaubensee Yep, working on this.

**Comment by sethmanheim** [comment]
@SeanFeldman @jtaubensee In the current docs, it mentions that you get 16 partitions per 1 GB of queue size. So a 5 GB queue is 5*16 = 80 GB. 

Is this correct? It seems like an odd way to manage queue size. If so, we're saying that in Premium, you only get 2 partitions, no matter what the size of the queue is? I just want to make the distinction clear in the docs.

**Comment by jtaubensee** [comment]
@SeanFeldman - That is correct. Previously, the default behavior of standard entities was non-partitioned, and the API's existed before partitioning was a thing. So in order to not break previous deployments, things aren't quite as clear as they should be. Hopefully the docs can help explain this.

**Comment by sethmanheim** [comment]
Closing issue as changes published to 
- https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-premium-messaging
- https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-partitioning
