### ISSUE TITLE
Cancellation support for receive operations

### ISSUE THREAD

**Issue by ig-sinicyn** [Azure/azure-service-bus#179]
Moved by request, origin https://github.com/Azure/azure-service-bus-dotnet/issues/439

C#, nuget package WindowsAzure.ServiceBus v4.1.8

**Use case:** I have a code that receives and processes messages in a loop, something like this: 
```cs
		BrokeredMessage msg;
		while ((msg = await queueClient.ReceiveAsync(timeout)) != null)
		{
			// message processing goes here
		}
```
Messages are rare, timeout set to 2-5 minutes.

I want to be able to cancel receive op immediately on app shutdown, but there's no way to do that. The `Receive()` method does not accept CancellationToken.
I cannot abort receive via disposing the queue client, too. The client may be used by another parts of code and I do not want to abort it in the middle of message processing.
Use small timeouts? Nope, 1-sec receive timeout will result in a millions of billed operations on service bus (we have a lot of instances that poll the queue).

**Suggestion:** add cancellation support for the Receive() calls, please:)

**Comment by EldertGrootenboer** [comment]
If this issue still occurs using the latest SDK, please let us know and we can re-open the issue.
