### ISSUE TITLE
Portal issue - Queue size

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus#18]
Not sure if this is the right place. Please excuse if not and mote to the appropriate repo if needed.

When creating a queue on a premium tier, size can go up to 80GB. Assuming 80GB queue is created,
![image](https://cloud.githubusercontent.com/assets/1309622/25317766/9c18b64c-283c-11e7-9c41-3dd36eac0d71.png)

reviewing the property doesn't indicate the size _and_ drop down is only goes as much as 5GB.

![image](https://cloud.githubusercontent.com/assets/1309622/25317776/d4586c28-283c-11e7-9356-0437ddd57a9f.png)

**Comment by jtaubensee** [comment]
@arundsouza - This does seem to be incorrect. Can you confirm?

**Comment by SeanFeldman** [comment]
Assuming this is fixed? 🙂
