### ISSUE TITLE
Unable to set primary or secondary keys in newer APIs

### ISSUE THREAD

**Issue by TerrapinStation** [Azure/azure-service-bus#184]
# Description

## Actual Behavior
1. When using an api version later than 2014-09-01, I am unable to set the Primary Key for an authorization rule. If I use the 2014-09-01 version of the API, I am able to define my own primary key for an auth rule.

## Expected Behavior
1. I need to be able to set Primary or Secondary keys in later versions of the ServiceBus API.

**Comment by EldertGrootenboer** [comment]
If this issue still occurs, please let us know and we can re-open the issue.
