### ISSUE TITLE
Possible to use Azure Storage Emulator with this library?

### ISSUE THREAD

**Issue by rozele** [Azure/azure-service-bus#186]
# Description

Should it be possible to use the Azure Storage Emulator for either the DotNet or Java SDKs? I.e., using the connection string `UseDevelopmentStorage=true`? I don't see anything options to configure topics on the Azure Storage Emulator, so it may not make sense for this library. I guess I'm wondering if it's on the roadmap.

## Actual Behavior
1. Use connection string `UseDevelopmentStorage=true`
2. DotNet client throws exception

## Expected Behavior
1. Able to use Azure Storage Emulator

**Comment by SeanFeldman** [comment]
I think you're mixing 🍎s and 🍊s here.
Azure **Storage** emulator has nothing to do with Azure Service Bus.
If your question is about Service Bus **emulator**, see https://feedback.azure.com/forums/216926-service-bus/suggestions/2565564-provide-a-service-bus-emulator-on-a-local-computer

**Comment by rozele** [comment]
Thanks @SeanFeldman, I had not realized there was a difference between Azure Storage queues and Azure Service Bus.
