### ISSUE TITLE
Use SAS authentication for subscription with .NET Standard library

### ISSUE THREAD

**Issue by rozele** [Azure/azure-service-bus#187]
The WindowsAzure.ServiceBus package supports the use of SAS tokens scoped to subscriptions. Is there any option to achieve something similar with the Microsoft.Azure.ServiceBus package?

# Description

## Actual Behavior
1. Authorization rules cannot be created for subscriptions.
2. SAS tokens can be generated that are scoped to a subscription.

## Expected Behavior
1. Option to listen to messages from a subscription using a scoped SAS token in .NET Core.

**Comment by nemakam** [comment]
If you have a SAS token scoped to a subscription, you can use it by calling `TokenProvider.CreateSharedAccessSignatureTokenProvider(token)`. But there is no public method to create that SAS token
To request for that feature, open the issue in https://github.com/Azure/azure-service-bus-dotnet repo.
