### ISSUE TITLE
Expired token only on windows

### ISSUE THREAD

**Issue by Grigsuv** [Azure/azure-service-bus#189]
Hi,i  tried to run same program in linux and windows,in windows i am getting error of expired token,the same code in linux works without errors,i've updated primary key,secondary,created new key with managing enable and even created new queue but still can't send or receive in js and c#,but the same code works on another pc with windows,WHY?
How can i fix this ?

**Comment by nemakam** [comment]
From the sound of it, this looks like a machine issue.
Can you check if the date on the machine is updated and there is no mismatch in system time?

**Comment by Grigsuv** [comment]
Yes,thank you
