### ISSUE TITLE
MSI - Sample

### ISSUE THREAD

**Issue by grik001** [Azure/azure-service-bus#194]
Hi,

Is it possible to use MSI with Microsoft.Azure.ServiceBus? I have only found samples for the previous library. If it is possible are there any samples available please?

Thanks!

**Comment by SeanFeldman** [comment]
This should be possible. I'm going to add a sample next week.

**Comment by grik001** [comment]
Great, thanks :) !!

**Comment by grik001** [comment]
Hi @SeanFeldman  , any update regarding this ticket please?

**Comment by SeanFeldman** [comment]
@grik001 sorry for delay. Priorities shifted and I'm left with zero time to focus on this.
I will _try_ to get it done this week.

**Comment by SeanFeldman** [comment]
@grik001 I'm almost done with the sample, but if you need to get going, here's the necessary code:

```c#
var tokenProvider = TokenProvider.CreateManagedServiceIdentityTokenProvider();
var messageSender = new MessageSender("sb://<namespace>.servicebus.windows.net/", "queuePath", tokenProvider);
await messageSender.SendAsync(new Message(Encoding.UTF8.GetBytes(messageBody)));
```

**Comment by grik001** [comment]
@SeanFeldman 

Much appreciated! Will start straight away :)

**Comment by grik001** [comment]
@SeanFeldman 

Hi Sean still have to try this, but I can't seem to find the method below which takes no parameters.

var tokenProvider = TokenProvider.CreateManagedServiceIdentityTokenProvider();

**Comment by SeanFeldman** [comment]
Make sure you use the latest version of the netstandard client, 3.0

>

**Comment by grik001** [comment]
@SeanFeldman 

Will do and thanks for the info. One last question but not necessarily fully related to this library. Is it possible to managed Topics (Create/Delete etc) using MSI ?

**Comment by SeanFeldman** [comment]
@grik001 could you re-open the issue? I haven't added the sample yet 🙂

> Is it possible to managed Topics (Create/Delete etc) using MSI ?

That's not related to MSI. The client itself doesn't support management operations (other than subscriptions). [Another package](https://github.com/Azure/azure-service-bus-dotnet/issues/65#issuecomment-338874419) will.
