### ISSUE TITLE
Updating sys.SessionId in a Topic Subscription Rule Action fails

### ISSUE THREAD

**Issue by DaveEx1** [Azure/azure-service-bus#196]
Created a BrokeredMessage with a custom property (OrderNum).

1. As expected: When the Message is sent to a Service Bus Topic with a Subscription that has 'Requires Session' enabled the message gets routed to the Dead Letter Queue. DeadLetterReason: 'Session id is null.' DeadLetterError: 'Session enabled entity doesn't allow a message whose session identifier is null.'

2. As expected: Set the BrokeredMessage.SessionId="temp" and send to Service Bus. Message is read from the Topic Subscription by a Logic App SB connector.

3. Set the BrokeredMessage.SessionId="temp" AND add a Topic Subscription Rule SQLAction: SET sys.SessionId = 'some value', i.e. updating the SessionId in the SQLAction. The result are:

- As expected - SQLAction: SET sys.SessionId = newid() - message received by the Subscription and consumed by the Logic App;
- As expected - SQLAction: SET sys.SessionId = user.OrderNum + newid() - message received by the Subscription and consumed by the Logic App;
-  **Not as expected** - SQLAction: SET sys.SessionId = user.OrderNum - message remains active in the Topic, not retrieved by the Subscription and not consumed by the Logic App;

**Comment by VDanylevskyi** [comment]
Hi. 
Is any news about this issue, because I found very interesting behavior. When I am defining this kind of action, then Service bus is blocking receiving of all messages, those are coming to the topic

**Comment by DaveEx1** [comment]
Yes, that was my experience too. This is still an issue that hasn’t been resolved unfortunately.

**Comment by VDanylevskyi** [comment]
Today I was able to make it work. I created a new Topic and a new subscription with session support and the value was successfully assigned and the message appeared in the subscription. I added another subscription without session support and it still works.

But it does not work for my old topic. Looks like the issue is in the compatibility between already existed topics and a session support

**Comment by EldertGrootenboer** [comment]
If this issue still occurs, please let us know and we can re-open the issue.
