### ISSUE TITLE
Confusion for NET 461 (windowsazure.servicebus) vs NET Standard (Microsoft.Azure.ServiceBus)- Why we need both with NET Standard

### ISSUE THREAD

**Issue by sasachan** [Azure/azure-service-bus#198]
"Microsoft.ServiceBus.Messaging" part of "[windowsazure.servicebus](https://www.nuget.org/packages/WindowsAzure.ServiceBus/4.1.9)" nuget - "Please note that this package requires .Net Framework 4.5.2 Full Profile." - that's the note written I see with nuget restore window using visual studio 2017 having update 15.7.1 - still okay as my project is running with 461 full profile.

Now, I've plan to move few of existing Net Standard, Hence, the first step would be take update nuget dependency "Microsoft.Azure.ServiceBus" part of "[Microsoft.Azure.ServiceBus](https://www.nuget.org/packages/Microsoft.Azure.ServiceBus/2.0.0)"

Now, I was looking for an alternate implementation of  "TokenProvider.CreateSharedAccessSignatureTokenProvider". And the [sample/code](https://github.com/Azure/azure-service-bus/blob/master/samples/DotNet/Microsoft.Azure.ServiceBus/QueuesRequestResponse/Server/RequestReplyResponder.cs) implementation is routing me to something that is connected with "Microsoft.ServiceBus.Messaging". That's confusion? And then why would I need to "Microsoft.Azure.ServiceBus". 

Additionally, is there an assumption as existing version of "Microsoft.Azure.ServiceBus" is compatible to work with NET Standard? Or is there an alternate plan?

**Comment by sasachan** [comment]
I Just tried to use the windowsazure.servicebus" package but it seems to be not compatible as the visual studio solution explorer started throwing yellow triangle icon on nuget?

![image](https://user-images.githubusercontent.com/12516416/39956501-4316a4b8-55ff-11e8-92ba-7d38d06bc480.png)

**Comment by sasachan** [comment]
It seems we there is new version of "Microsoft.Azure.ServiceBus 3.0" is shipped. And look like the feature I was looking for does available. I'll give a try and come back.

**Comment by sasachan** [comment]
@SeanFeldman  Just for a quick, I see version Microsoft.Azure.ServiceBus 3.0 has a dependency over AppAuthentication package a preview version. Is there immediate plan to address it?

![image](https://user-images.githubusercontent.com/12516416/40092225-db50ec16-58d9-11e8-8a5f-63c4b8ec70aa.png)

**Comment by nemakam** [comment]
@sasachan 
We are using features which are present only in preview library. We will have to wait till that time decides to release a non-preview release.

**Comment by viganella** [comment]
Microsoft.Azure.ServiceBus **vs** Windows.Azure.ServiceBus which one are you using, it is quite confusing for me which one to use, as they seem to be similar to each other  and both claim to be the one nuget to be use for Azure ServiceBus communication ?

**Comment by tikluganguly** [comment]
you would still need to use windowazure.servicebus in case you want to use Relay based WCF service.

**Comment by amitchaudhary** [comment]
So, can we have clear guidance on which packages should be used and when?

**Comment by SeanFeldman** [comment]
@amitchaudhary https://github.com/Azure/azure-service-bus/issues/198#issuecomment-439121286
Beyond that is not about when to use what, but wherever you can migrate from the old package or not (yet).
