### ISSUE TITLE
OnMessageOptions.AutoRenewTimeout

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus#20]
Documentation doesn't specify what value disables `AutoRenewTimeout` (my tryouts led me to `TimeSpan.Zero`) or what's the default value (5 mins).

[docs page](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.onmessageoptions.autorenewtimeout?view=azureservicebus-4.0.0#Microsoft_ServiceBus_Messaging_OnMessageOptions_AutoRenewTimeout)

[sample page](https://github.com/Azure/azure-service-bus/blob/8de8f69d06371980eb8f8c497303d4bfd925a897/samples/DotNet/Microsoft.ServiceBus.Messaging/QueuesGettingStarted/README.md)

**Comment by SeanFeldman** [comment]
Paging @sethmanheim for the rescue 😃

**Comment by SeanFeldman** [comment]
Adding @jtaubensee

**Comment by jtaubensee** [comment]
This will go out with #16, which might not be until there is a new NuGet package.

**Comment by SeanFeldman** [comment]
As long as it's addressed, I'm good

**Comment by jtaubensee** [comment]
But I guess to answer your question in the meantime, the default is 5 minutes, and TimeSpan.Zero will disable it.

**Comment by SeanFeldman** [comment]
:+1: thank you for the confirmation @jtaubensee

**Comment by sethmanheim** [comment]
@hmlam Can your team add this to the source code comments?

**Comment by SeanFeldman** [comment]
And since @hmlam is buying, also add a warning about this operation not been guaranteed? I.e. can fail.
![image](https://user-images.githubusercontent.com/1309622/27098714-cfa017c8-5035-11e7-91de-a4c22efa9150.png)

**Comment by SeanFeldman** [comment]
Was getting a lot of questions about `AutoRenewTimeout`, so have added the non-guaranteed explanation to my [original post](https://weblogs.asp.net/sfeldman/azure-service-bus-autorenewtimeout).

**Comment by SeanFeldman** [comment]
@binzywu could you please provide the reason it's closed? E.g. "documentation updated, closing" or "next version will contain xmldoc remarks". Thank you.
