### ISSUE TITLE
how to manually ACK/NACK a message in PeekLock receive mode using Service Bus JAVA sdk 1.2.5

### ISSUE THREAD

**Issue by deepushri** [Azure/azure-service-bus#200]
Hi,
I was reading through the java documentation for receive messages and I see that in order to receive a message in the PeekLock mode, I need to send the Complete() so that the message can be successfully removed from the queue. This property can be set as true(auto complete) in the MessageHandler implementation.

But if I set it to false in MessageHandler, then how do I invoke the same in my code?? As I want a manual Ack and NACK from my code instead of Auto Acks.

Can you please help me with the page where I will have more examples on similar lines???

**Comment by SeanFeldman** [comment]
You'd have to Abandon() the message.

**Comment by deepushri** [comment]
Hi,
I do understand that i will have to call abandon() to retry the message.My question was more on the lines, how do i set or call Abandon() or Complete() from my code if m using the message handler. 
To brief more abt it, when we register a handler with queueClient in java, we have the option to set the autoack as true or false. If i set it to true, then incase of exceptions the message will be open for other consumers and will nt be removed from queue. But here instead of making the handler param(auto ack) to true, i want to make it false and want to handle the acks manually in my code. So when a message comes to the queue and my messageHandler receives the message, how do i invoke the complete() or abandon() methods???

**Comment by nemakam** [comment]
@deepushri The way to do that is to use `queueClient.complete()` or `queueClient.abandon()`.

**Comment by backendjavadeveloper** [comment]
This is the message handler that I have for reading the messages. How will I have the hold of queueClient object here???


public class MessageHandler implements IMessageHandler {

	
	@Override
	public CompletableFuture<Void> onMessageAsync(IMessage message){
               .....
		return CompletableFuture.completedFuture(null);
	}

	@Override
	public void notifyException(Throwable exception, ExceptionPhase phase) {
		// TODO Auto-generated method stub
		System.out.println(exception.getMessage());
		System.out.println(phase.name());
		
	}

}

And this is how I define my bean for the queuClient.
        
@Bean(name="messageListener")
@DependsOn("publishqueue")
public QueueClient receiveMessage() throws  InterruptedException, ServiceBusException
{
	String publishqueue = sbconfig.getPublishQueue();
	String connectionString = getSBConnectionString();

		QueueClient client = new QueueClient(new ConnectionStringBuilder(connectionString,publishqueue), com.microsoft.azure.servicebus.ReceiveMode.PEEKLOCK);
		
		MessageHandlerOptions messageoptions = new MessageHandlerOptions(5, false, Duration.ofMinutes(2),Duration.ofDays(1));
		System.out.println("handler options set are " + messageoptions.toString());
		client.registerMessageHandler(getMessageHandler(),messageoptions);
		return client;
}

Can you please suggest on how can I use the abandon() and complete() methods in my above code???

**Comment by deepushri** [comment]
@nemakam 

This is the message handler that I have for reading the messages. How will I have the hold of queueClient object here???

public class MessageHandler implements IMessageHandler {

@Override

public CompletableFuture<Void> onMessageAsync(IMessage message){

          .....

    return CompletableFuture.completedFuture(null);

}@Override

public void notifyException(Throwable exception, ExceptionPhase phase) {

    // TODO Auto-generated method stub

    System.out.println(exception.getMessage());

    System.out.println(phase.name());

    

}

}

And this is how I define my bean for the queueClient.

@bean(name="messageListener")

@dependson("publishqueue")

public QueueClient receiveMessage() throws InterruptedException, ServiceBusException

{

String publishqueue = sbconfig.getPublishQueue();

String connectionString = getSBConnectionString();

    QueueClient client = new QueueClient(new ConnectionStringBuilder(connectionString,publishqueue), com.microsoft.azure.servicebus.ReceiveMode.PEEKLOCK);

    

    MessageHandlerOptions messageoptions = new MessageHandlerOptions(5, false, Duration.ofMinutes(2),Duration.ofDays(1));

    System.out.println("handler options set are " + messageoptions.toString());

    client.registerMessageHandler(getMessageHandler(),messageoptions);

    return client;

}

Can you please suggest on how can I use the abandon() and complete() methods in my above code???

**Comment by shantanookirtane** [comment]
@nemakam  - Why this thread is closed. Can you please respond to the previous thread posted by @deepushri
