### ISSUE TITLE
Equivalent for NoMatchingSubscriptionException and how to capture it

### ISSUE THREAD

**Issue by hgjura** [Azure/azure-service-bus#201]
In the older version there used to be the NoMatchingSubscriptionException, to catch any messages that would not be picked up by any subscriber. What is the equivalent in the new library and how do you capture these exceptions to get the orphan messages.

Thanks
Herald

**Comment by axisc** [comment]
hi,
could you share the old and new version? We do have this on the latest Azure SDK as well.
https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.nomatchingsubscriptionexception?view=azure-dotnet

Also, for future client dot-net library questions, could you post them on the [DotNet Library repo](https://github.com/Azure/azure-service-bus-dotnet/) ?

**Comment by hgjura** [comment]
/unresolved

@EldertGrootenboer Hi, you closed this long-running query as resolved, but I am not sure what the solution to this is.

In the early days of the ASB SDK, if a message that was sent to a topic did not have any subscription to fall into, it would throw this NoMatchingSubscriptionException. In the later versions of the SDK this was removed. I still don't know how one can capture and identify any messages that do not get filtered by any subscriptions. Avoiding so to lose them.

Thanks

**Comment by EldertGrootenboer** [comment]
@hgjura I see I forgot to add the comment for this. The ask here is the same as in https://github.com/Azure/azure-service-bus/issues/277, so closing this one and tracking the progress in the other issue. We have added this to our backlog to investigate the options around this.
