### ISSUE TITLE
Auto-forwarding destination entity not found error is incomplete

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus#203]
```c#
var connectionString = Environment.GetEnvironmentVariable("AzureServiceBus.ConnectionString");
var nsm = NamespaceManager.CreateFromConnectionString(connectionString);

var desc = new QueueDescription("blah")
{
	ForwardTo = "doesntexist",
	ForwardDeadLetteredMessagesTo = "doesntexisteither",
};

await nsm.CreateQueueAsync(desc).ConfigureAwait(false);
```

Exception thrown: **ArgumentException**

```
The remote server returned an error: (400) Bad Request. SubCode=40400. 
The auto forwarding destination entity does not exist. TrackingId:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxx 
asbnamespace.servicebus.windows.net:blah, Timestamp:xx/xx/xxxx xx:xx:xx xx
```

From the exception it is not clear which forwarding destination was not found as it's not mentioned in the exception.
Please specify argument name / value.

**Comment by EldertGrootenboer** [comment]
We have added this to our backlog, and will update this issue when we have more information.

**Comment by EldertGrootenboer** [comment]
The work for this has been done, closing this issue as completed.

**Comment by SeanFeldman** [comment]
A true 5 year anniversary gift 😂
Does that mean the exception will contain the entity name?

**Comment by EldertGrootenboer** [comment]
Correct 🙂.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
