### ISSUE TITLE
SAS authentication using latest Java SDK for Service bus

### ISSUE THREAD

**Issue by backendjavadeveloper** [Azure/azure-service-bus#204]
Hi,
In the documentations, it is advised to use SASAuthentication while trying to interact with Azure Servicebus. But i am not able to find the appropriate class to use the SAS token for connections. I used to see one in older version "configureWithSASAuthentication". Do we have any suggestions on how to do it in the latest SDK version??

Thanks

**Comment by nemakam** [comment]
Use this: https://github.com/Azure/azure-service-bus-java/blob/97c68743a675466aae590963d45e22a2c405b003/azure-servicebus/src/main/java/com/microsoft/azure/servicebus/primitives/ConnectionStringBuilder.java#L188-L191

If you have any more questions related to the java client, please open a new issue in [azure-service-bus-java](https://github.com/Azure/azure-service-bus-java/issues) repo
