### ISSUE TITLE
Can not call queueClient.SendAsync from MVC Controller

### ISSUE THREAD

**Issue by pduer** [Azure/azure-service-bus#206]
# Description
To try and test creating a Service Bus Queue Message. The code works fine from a Console Application, but NOT from IIS Express. I have eliminated firewall issues by checking the same code from a Azure VM with NO firewalls.

I keep getting "A Task was Cancelled" exceptions.

`            try
            {
                await queueClient.SendAsync(new Message(Encoding.UTF8.GetBytes("hello world")))
                    .ContinueWith(
                        t => { Console.WriteLine(t.Status + "," + t.IsFaulted + "," + t.Exception.InnerException); },
                        TaskContinuationOptions.OnlyOnFaulted);
            }
            catch (Exception e)
            {
                // Logger.Error("Error Dispatching USER EMAIL MESSAGE to Azure Service Bus Queue:\n" + e);
            }`

I am using:

VS 2017 15.7 MVC 5.2.4 Microsoft.Azure.ServiceBus 3.0.2

I am also sure my connection strings are valid and the queue is created.
## Actual Behavior
1.  On the call to:  await queueClient.SendAsync(new Message(Encoding.UTF8.GetBytes("hello world")))
nothing happens in the controller, the code just hangs and no message is sent.
2. 

## Expected Behavior
1. calling SendAsync would send the queue message and go on.

**Comment by SeanFeldman** [comment]
I've noticed your question on StackOverflow as well. The continuation of the task is what I'd look into and chage this to tr/catch with logging in catch (w/o `Console.WriteLine` 🙂).

**Comment by pduer** [comment]
Yeah, the continuation wasn't needed for sure. I have been able to setup a base vanilla MVC project and get the message send to the queue with the Async Awaits in place. But, where I want to use this is in an Episerver project and it seems to be catching the async and not letting the message send through. I am still kind of at square one because I get no error yet. The timeout never happens.

**Comment by pduer** [comment]
I was able to what I wanted with the following code:

`        private bool AddUserMailMessageToServiceBusQueue(MailMessage mailMsg)
        {
            mailMsg.AlternateViews.Clear();
            var serializedMailMsg = JsonConvert.SerializeObject(mailMsg);

            var queueClient =
                new MessageSender(ServiceBusContext, UserMailMessageQueueName, RetryPolicy.Default)
                {
                    OperationTimeout = TimeSpan.FromSeconds(10)
                };
            var queueMessage = new Message(Encoding.UTF8.GetBytes(serializedMailMsg))
            {
                MessageId = Guid.NewGuid().ToString()
            };
            try
            {
                AsyncHelper.RunSync(() => queueClient.SendAsync(queueMessage));
                AsyncHelper.RunSync(() => queueClient.CloseAsync());
                return true;
            }
            catch (Exception e)
            {
                Logger.Error("Error Dispatching USER EMAIL MESSAGE to Azure Service Bus Queue:\n" + e);
                return false;
            }
        }`

AsyncHelpder.RunSync() looks like this:

`		public static void RunSync(Func<Task> func)
		{
			AsyncHelper._myTaskFactory
			  .StartNew<Task>(func)
			  .Unwrap()
			  .GetAwaiter()
			  .GetResult();
		}`

If I ran the method in ASync, I never got a response, just a hang on the worker process. I think that the overriding EpiServer code might play a part, but I am not sure.

**Comment by SeanFeldman** [comment]
Async code should ideally should run as async bottom up.
The controller should be an async controller to allow an async action and to get rid of the wrapper method to execute asynchronous code in a synchronous manner. I suspect when a new task is spawn off in a fire and forget mode, the controller terminates while the messaging taks is not completed and hence the exception.
