### ISSUE TITLE
Implementing health check service for queues and topics

### ISSUE THREAD

**Issue by sshogunn** [Azure/azure-service-bus#208]
# Description
We use Azure Service Bus queues and topics in our microservices deployed in Azure. One of the things we would like to implement is monitoring of our services. We also want to check that every microservices does not have any issues to send and receive messages from queues and topics. Usually it is called health check , and that's what we would like to have. I haven't found anything available out of the box, so I am looking for some other options, one of them is implement custom health check. It will be working in the following way:
- Sends a dummy message in a queue to check that message is sent
- Receives the message from the queue to verify that messages can be read from the queue 

The same thing I am going to do with topics. But I have some doubts, because I did not find any way to:
1. Send a message that will be not received by other consumers(real endpoints used by business)
2. Receive exactly the same message that was sent in the step 1. IMessageReciever interface does not provide any methods to fetch a message that has some properties or labels.

I can also use a workaround, I can send dummy messages and configure other consumer to ignore them:
- The message is received 
- Label or properties checked
- If the message should be ignored, the consumer adds it back to the queue

But I don't think that it is the best option because we might have very high load on the messaging and such operations may lead to some confusion. 
Could you please propose some other options for my case?

**Comment by nemakam** [comment]
@sshogunn 
Are you looking for functionality which equates to "Does queue exist?"? 
Could you describe what is it that your program does if "health check" fails?

**Comment by sshogunn** [comment]
@nemakam , it is simple monitoring tool or dashboard like Prometheus. Honestly, I want to check that not only a queue/topic exist, I also want to check that it can receive and process messages, something like - https://rumanblogs.com/azure-service-bus-self-polling-health-check/

**Comment by sshogunn** [comment]
I did by sending dummy message and reading it back.
Thank you for your help

**Comment by DaniaALkhadraa** [comment]
Hello @sshogunn I am on the same problem.
could you tell me the way u managed to solve it?
