### ISSUE TITLE
Reading batch of messages by the same factory 

### ISSUE THREAD

**Issue by sshogunn** [Azure/azure-service-bus#210]
Greetings,

We are working on a feature where we send quite a lot messages per operation, usually it is around 1 000 000 of messages. To reduce the number of calls on sender side, we use batching, it helps a lot. We also use prefetch count on receiver side to reduce the number of calls to ASB, it works as well. 
But we also have more than one instance of consumer service(our microservice is scaled by k8s ), it is why I would like to make sure that the same batch of messages sent from sender side was consumed by the same consumer instance. A reason why I would like to do this is collecting messages grouped by one batch and commiting all of them in one transaction. 

**What can i use for that? How can I guarantee that messages from the same batch have been read by the same consumer?**

**Comment by SeanFeldman** [comment]
Have you looked into [Message Session](https://docs.microsoft.com/en-us/azure/service-bus-messaging/message-sessions) feature?

@sshogunn I'm not a member of the ASB team, but it feels wrong to raise a question like that on issue tracker for old client and broker. This question seems more suitable for StackOverflow, where not only thousands of knowledgeable developers can answer your question in a very short time, but also other forum members can benefit from reading the answer when searching for something similar. You'll be surprised to find out that similar question has been answered in the past many times 🙂

**Comment by sshogunn** [comment]
@SeanFeldman,

You are right. I just feel like here I can find more Azure and ASB experts, it is why I addressed question here. :) I will make a post in StakeOverflow if I cannot find any answer here. 

Thank you for your help

**Comment by nemakam** [comment]
`MessageSession` is the feature you are looking for.
