### ISSUE TITLE
NamespaceManager.QueueExistsAsync() is working incorrectly

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus#211]
Given the following code:

```c#
var namespaceManager = NamespaceManager.CreateFromConnectionString(connectionString);
await namespaceManager.QueueExistsAsync("error");
```
**Actual**
when a connection string w/o Manage rights is used, the client will throw `UnauthorizedAccessException` in case `error` queue exists. If the queue doesn't exist, it will return `false`.

**Expected**
Throw whenever connection string has no Manage rights.

This is a potential security issue as information about entities could be revealed.

Note: have not tested with other entities. Could be the same issue.

**Comment by axisc** [comment]
Closing this since it was opened on the dot-net client library.

**Comment by SeanFeldman** [comment]
@axisc this issue was closed, the client issue was not moved to the new SDK repo, leaving this bug in the air. Can I suggest to re-open this issue as it is broker-related? Or, alternatively, move https://github.com/Azure/azure-service-bus-dotnet/issues/519 to the new repo.
