### ISSUE TITLE
Update Premium tier cost documentation and Calculator

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus#212]
Premium tier is now charged per hour, making it more appealing to customers that would not want to be charged for the whole day.

Examples:

- [Service Bus pricing](https://azure.microsoft.com/en-gb/pricing/details/service-bus/) page
- [Service Bus Premium and Standard messaging tiers](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-premium-messaging) page 
- [Azure Calculator](https://azure.microsoft.com/en-ca/pricing/calculator/)

![image](https://user-images.githubusercontent.com/1309622/42460929-6b92aefc-835c-11e8-98fa-3fc7ca5da2bc.png)

**Comment by SeanFeldman** [comment]
@sethmanheim could you please review this? 
I've [blogged](https://weblogs.asp.net/sfeldman/what-you-pay-is-what-you-get) about hourly billing and many ping me directly pointing out that non of the public documentation was updated to reflect the new billing. Thank you.

**Comment by sethmanheim** [comment]
@SeanFeldman I'm out for just this week, but I will definitely look at this when I get back. Thank you Sean.

**Comment by spelluru** [comment]
@axisc - I can update the docs page:
https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-premium-messaging

Other two are owned by the product team. Thanks.

**Comment by axisc** [comment]
these have been done. closing this now.

**Comment by SeanFeldman** [comment]
> closing this now.

Wait, you don't expect it to be broken again, don't you 😂

Thank you @axisc
