### ISSUE TITLE
Removing a specific message

### ISSUE THREAD

**Issue by onuar** [Azure/azure-service-bus#215]
Hi all,

Is there any way to remove a specific message. We can send the messages to the topic and get message Id. But I think, we are not able to remove a message that is already in a topic. So message Id is useless at this point or I'm missing something.

**Comment by SeanFeldman** [comment]
`MessageId` is optional and is assigned by the client therefore cannot be used for browsing.

> The sequence number can be trusted as a unique identifier since it is assigned by a central and neutral authority and not by clients.

What you should look into is receiving message by its [`SequenceNumber`](https://docs.microsoft.com/en-us/azure/service-bus-messaging/message-sequencing).

**Comment by onuar** [comment]
MessageId is not the proper way. Ok, SequenceNumber will be fit better. But still I don't know how to manage removing a message by SequenceNumber.

**Comment by SeanFeldman** [comment]
ReceiveAsync() with SequenceNumber

**Comment by onuar** [comment]
Thanks Sean. It's useful. I get it.

Let me explain my scenario more. On my application layer, I queue a message. This message will be worked after 15 minutes. But a user can cancel the message before it works. So I should be able to remove this message on my application layer not on my consumer application layer. For achiviving that, I have to get message sequence number. 

What I tried is to send message and get the message.SequenceNumber on my application layer. Problem is that I'm getting InvalidOperationException.

My code is below:
```csharp
               var client = TopicClient.CreateFromConnectionString(Config.ConnectionString, topicName);
                var message = new BrokeredMessage(new MyModel()
                {
                    Id = 10,
                    Name = name
                });
                client.Send(message);
                Console.WriteLine($"SequenceNumber: {message.SequenceNumber}");
```

**Comment by SeanFeldman** [comment]
> System.InvalidOperationException
> Thrown if the message was not received from the message server.

You have to receive a message from the broker to get the `SequenceNumber`.

If you need to schedule a message in future and be able to cancel it, then there's a different API, `ScheduleMessageAsync`. You'll find details [here](https://weblogs.asp.net/sfeldman/azure-service-bus--canceling-scheduled-messages).
