### ISSUE TITLE
[Docs Request] How to use Microsoft.Azure.ServiceBus.SubscriptionClient.RegisterPlugin

### ISSUE THREAD

**Issue by GustavoAmerico** [Azure/azure-service-bus#218]
What is the difference between method Microsoft.Azure.ServiceBus.SubscriptionClient.RegisterPlugin and Microsoft.Azure.ServiceBus.SubscriptionClient.RegisterMessageHandler? What is the appropriate scenario for each method?

**Comment by SeanFeldman** [comment]
`ReginsterPlugin()` is to register incoming and outgoing message plugins. See details [here](https://github.com/Azure/azure-service-bus-dotnet-plugins). [Attachments plugin](https://github.com/SeanFeldman/ServiceBus.AttachmentPlugin) is an example of a plugin that allows messages larger than the allowed maximum.

`RegisterMessageHandler()` is to register message processing callback invoked for each incoming message.

For the future, these kind of questions are better to be asked at [StackOverflow](https://stackoverflow.com/search?q=azure-servicebus).
