### ISSUE TITLE
Portal and WindowsAzure.ServiceBus client discrepancy on minimum lock duration

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus#22]
![image](https://cloud.githubusercontent.com/assets/1309622/25750956/ac59714e-3170-11e7-837a-489a65c0fa64.png)

Logically portal is correct, but technically it's wrong and should respect what the client API & Broker support.

@jtaubensee

**Comment by EldertGrootenboer** [comment]
If this issue still occurs, please let us know and we can re-open the issue.
