### ISSUE TITLE
Docs: BatchFlushInterval and SendBatchAsync

### ISSUE THREAD

**Issue by stofte** [Azure/azure-service-bus#222]
Hello SB people,

When referring to the client-side batching docs: https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-performance-improvements#client-side-batching they seem pretty clear that the batching only happens for SendAsync and CompleteAsync, but does the batching also apply for SendBatchAsync?

**Comment by axisc** [comment]
made doc changes

**Comment by stofte** [comment]
Actually reading the changes does not mention anything about the Batch calls. My question is pretty simple. If I call `SendBatchAsync` a bunch of times within the batch interval, will those calls be batched together? Currently, I can only conclude that the calls will not be batched.

Anyway, the mentioned method `SendBigBatchAsync ` seems to refer to a code example from everyones stackoverflow/servicebus expert? https://mikhail.io/2017/07/sending-large-batches-to-azure-service-bus/

**Comment by SeanFeldman** [comment]
> My question is pretty simple. If I call SendBatchAsync a bunch of times within the batch interval, will those calls be batched together? 

No.
