### ISSUE TITLE
OnMessage/OnMessageAsync very slow invocation with AMQP in WindowsAzure.ServiceBus client

### ISSUE THREAD

**Issue by jr01** [Azure/azure-service-bus#226]
Consider the following simple code:
```
namespace ConsoleApp
{
    using System;
    using System.Diagnostics;
    using Microsoft.ServiceBus.Messaging;

    class Program
    {
        static void Main(string[] args)
        {
            var messagingFactory = MessagingFactory.CreateFromConnectionString(
                "Endpoint=sb://xxxxxx.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;" +
                "SharedAccessKey=xxxxxx=;TransportType=Amqp");

            var queueClient = messagingFactory.CreateQueueClient("myqueue");
            
            var sw = new Stopwatch();
            sw.Start();

            queueClient.OnMessage(
                b =>
                {
                });

            Console.WriteLine("Took: " + sw.Elapsed);
            Console.ReadLine();
        }
    }
}

```
## Actual Behavior
1. When using `TransportType=Amqp` the `OnMessage` invocation often takes more than 10 seconds, while without Amqp it takes around 0.5 second.  Sometimes with Amqp it is fast though. 
With the new [Microsoft.Azure.ServiceBus client](https://github.com/Azure/azure-service-bus-dotnet) it is always fast. So it looks like an issue with the older client.
When there are many queues to listen to and thus multiple queue clients / OnMessage invocations (we are using [webjobs](https://github.com/Azure/azure-webjobs-sdk) framework...) it takes a long time to just startup the application. 

## Expected Behavior
1. Invoking OnMessage/OnMessageAsync should be fast.

## Versions  
- OS platform and version: Win10 Enterprise
- .NET Version: 4.6.1
- NuGet package version or commit ID: tested with WindowsAzure.ServiceBus 3.4.6 and 5.00

**Comment by axisc** [comment]
Thanks for submitting the feedback. We're not actively making changes to the older client version particularly for AMQP.

Is there any particular reason for you to use the previous client? We highly recommend switching to the new client if you are using AMQP.

**Comment by jr01** [comment]
We use the [Microsoft Webjobs SDK](https://github.com/Azure/azure-webjobs-sdk) and that has the old library in its latest v2.x release. Webjobs SDK v3 has the new client,, but it's [unclear](https://github.com/Azure/azure-webjobs-sdk/issues/1555) when that will be released.
