### ISSUE TITLE
ArgumentOutOfRangeException on TopicClient.SendAsync

### ISSUE THREAD

**Issue by MrGlenThomas** [Azure/azure-service-bus#227]
# Description
ArgumentOutOfRangeException is thrown on TopicClient.SendAsync. Not sure what is causing this, but appears to be internal to the library (v4.1.6).

> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
> Parameter name: index
>    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
>    at Microsoft.ServiceBus.Messaging.SendAvailabilityPairedNamespaceMessageSender.get_Backlog()
>    at Microsoft.ServiceBus.Messaging.SendAvailabilityPairedNamespaceMessageSender.SendAsyncResult.<GetAsyncSteps>b__6_6()
>    at Microsoft.ServiceBus.Tracing.MessagingClientEtwProvider.TraceClient(Action action)
>    at Microsoft.ServiceBus.Messaging.SendAvailabilityPairedNamespaceMessageSender.SendAsyncResult.<GetAsyncSteps>d__6.MoveNext()
>    at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.EnumerateSteps(CurrentThreadType state)
>    at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.Start()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
>    at Microsoft.ServiceBus.Messaging.SendAvailabilityPairedNamespaceMessageSender.OnEndSend(IAsyncResult result)
>    at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.EnumerateSteps(CurrentThreadType state)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
>    at Microsoft.ServiceBus.Messaging.MessageSender.<>c.<SendAsync>b__44_1(IAsyncResult a)
>    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

## Actual Behavior
1. Call TopicClient.SendAsync
2. ArgumentOutOfRangeException is thrown

## Expected Behavior
1. Call TopicClient.SendAsync
2. Message is published to service bus topic

**Comment by axisc** [comment]
Could you share the code with us for investigation - please be sure to obfuscate the keys and PII.

**Comment by axisc** [comment]
Please reopen if still an issue
