### ISSUE TITLE
Service Bus Topic created with size of 32 GB

### ISSUE THREAD

**Issue by rishikeshjadhav** [Azure/azure-service-bus#229]
**Description**:
I was trying to provision a service bus topic using .NET client and was able to create topic with 32 GB size, however when i try to do it again, i am getting the error saying topic can be created with allowed size as 1, 2, 3, 4 5 GB.

**Actual Behaviour**:
Topic is created with size of 32 GB, attached is snapshot for the same

**Expected Behaviour**:
Topic should be created with size of 1, 2, 3, 4, 5 GB size as per azure portal

![snap 1](https://user-images.githubusercontent.com/17293029/45011977-e6183680-b032-11e8-8db8-115283efb191.png)

**Comment by clemensv** [comment]
I assume you did this on Service Bus Standard with a size of 2GB. If you create a partotioned topic, it's 2GB per partition, with 16 partitions.

**Comment by rishikeshjadhav** [comment]
Yes, the Service Bus is on Standard Messaging tier. Also i created a partitioned topic with size of 32 GB. I am trying the same thing again and is throwing me an exception, see attached below

![snap 2](https://user-images.githubusercontent.com/17293029/45012680-cf271380-b035-11e8-8193-77e01283989c.PNG)


I am not sure how it created the first time.

**Comment by rishikeshjadhav** [comment]
Found following reference and understood why it happened.
 
https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-partitioning#standard
