### ISSUE TITLE
Getting timeout exception

### ISSUE THREAD

**Issue by sadatmazumder** [Azure/azure-service-bus#237]
# Description
Getting timeout exception

## Actual Behavior
getting below error while running the sample application:
Sending message: Message 0
4/10/2018 3:22:29 PM :: **Exception: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond ErrorCode: TimedOut**

## Expected Behavior
1.  should have received the sent messages

**Comment by nemakam** [comment]
Please retry. You could also try it on a different entity or from a different machine to check if its happening due to service issue or client machine issue.
If issue persists, open support ticket through Azure portal.
