### ISSUE TITLE
Poor performance 

### ISSUE THREAD

**Issue by jazeem-azeez** [Azure/azure-service-bus#238]
# Description
Experienced Poor send and receive rates while using this library 

Sample code, tried other techniques too

https://github.com/Azure/azure-service-bus/blob/master/samples/DotNet/GettingStarted/Microsoft.Azure.ServiceBus/SendReceiveUsingMessageSenderReceiver/Program.cs
 

## Actual Behavior
1.  getting a send & receive rate close to one message per second 

## Expected Behavior
1.  Close to 100 messages per second (that was the bare minimum, while using .net framework library (Windows azure service bus) 

Also reviewed 
https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-performance-improvements

**Comment by axisc** [comment]
@jazeem-azeez  - could you share a repro for this - specifically for the other techniques?

Currently this is not actionable since we don't have any other details. Please feel free to reopen when other details are added

**Comment by jazeem-azeez** [comment]
> @jazeem-azeez - could you share a repro for this - specifically for the other techniques?
> 
> Currently this is not actionable since we don't have any other details. Please feel free to reopen when other details are added

@axisc  : I used this same project itself. there is no separate repo; 

https://github.com/Azure/azure-service-bus/blob/master/samples/DotNet/GettingStarted/Microsoft.Azure.ServiceBus/SendReceiveUsingMessageSenderReceiver/Program.cs

https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/GettingStarted/Microsoft.Azure.ServiceBus


recent update : I Managed to Fix Performance issue, by doing async call in parallel. wrote a separate class to handle that.

**Comment by jazeem-azeez** [comment]
> specifically for the other techniques?
 couldn't get you, can you be more specific
