### ISSUE TITLE
OnMessage(CallBackFunc,Options) is taking time 60+ seconds

### ISSUE THREAD

**Issue by sxd63870** [Azure/azure-service-bus#241]
# Description
  public MessageSession messageSession = null;

        public void ReceiveMessage()
        {
            MessagingFactory messagingFactory = MessagingFactory.CreateFromConnectionString(connectionString);
            SubscriptionClient subscriptionClient= messagingFactory.CreateSubscriptionClient(TopicName, SubscriptionName);
            String subId = Guid.NewGuid().ToString();
            if ((subscriptionClient != null) && (messageSession == null))
            {
                try
                {
                    OnMessageOptions onMessageOptions = new OnMessageOptions();                    
                    onMessageOptions.AutoComplete = true;                    
                    messageSession = ncwSubscriptionClient.AcceptMessageSession(subId);                                      
                    messageSession.OnMessage(ProcessResponseCallBack, onMessageOptions);                                                                              
                }
                catch (Exception ex)
                {
                    
                }
            }
        }

        public void ProcessResponseCallBack(BrokeredMessage msg)
        {
            Console.WriteLine("Received Msg :: " + msg.CorrelationId);
            msg.Complete();
        }

I need to know what causing the latency at OnMessage(). why is it taking 60+ seconds
I am using WindowsAzure.ServiceBus

## Actual Behavior
1. All the times OnMessage(callbackfunc,options) is quick ,sometimes it takes time and it takes 60+ seconds if it takes time.

## Expected Behavior
1. All the times OnMessage(callbackfunc,options) should be quick

**Comment by nemakam** [comment]
Kindly open a support ticket through the azure portal with namespace name/ entity name and approx timestamps for the delayed message.
