### ISSUE TITLE
Duplicates history saves messages even if they were received

### ISSUE THREAD

**Issue by iBalag** [Azure/azure-service-bus#243]
# Description
I use Azure Service Bus queue with enabled duplicate detection. I set up duplicate detection history time window to 5 min and sent a message with unique MessageID.
After that I received this message and tried to send it again (MessageID was the same that the first time).

## Actual Behavior
1. There is no message in the queue

## Expected Behavior
1. Duplicates history should be cleared after message receiving
2. New message should be in the queue

**Comment by SeanFeldman** [comment]
That's not how the feature is working. You're talking about _sliding window_ history. ASB supports fixed time history.

The feature will de-duplicate _any_ message received after an message with the same ID has been seen once. Wherever it's handled or not, is unrelated.

**Comment by iBalag** [comment]
Thank you @SeanFeldman ! Ok, it seems this is not a bug - just a feature :) It makes sense in many cases.
Are you planning to add a support of _sliding window_ history?

**Comment by SeanFeldman** [comment]
@iBalag this would be a question to the broker (service) team.
/cc @axisc

**Comment by nemakam** [comment]
@iBalag 
No, there is no near future plan to add that support. You can open a new feature request if needed.
