### ISSUE TITLE
Single Receiver/Sender

### ISSUE THREAD

**Issue by grik001** [Azure/azure-service-bus#245]
Hi,

I have a question regarding Receivers and Senders. I am currently keeping a single instance for my Senders and Receivers for ServiceBus.

I am not sure what is considered high load for SB but lets say I am posting 1500 requests/minute should I span these across multiple senders or still use one sender?

The sender is being executed by an API. I am still trying to find the source of the problem but sometimes it feels like it is choking on the number of requests it has to handle.

**Comment by SeanFeldman** [comment]
Single sender with a premium namespace with concurrent sends is performance.
But the same setup on standard tier would not give you the same result.

**Comment by grik001** [comment]
Hi Sean,

I have managed to reproduce this on a console app. As before it was on API thus was unable to share code.

Is it normal for the Receive to stop returning for some minutes? I have replied to one of my own threads.

**Comment by SeanFeldman** [comment]
I've witnessed some minor slowdowns, but never a complete stop. What tier do you use?

Also, w/o repro code it's hard try to help you...

**Comment by grik001** [comment]
Hi Sean,

I am currently testing using this repo to test: 

https://github.com/grik001/ServiceBusTest/tree/master/ServiceBusTest

**Comment by grik001** [comment]
Tier is Standard

**Comment by SeanFeldman** [comment]
Standard tier will never give you guaranteed performance or very high throughput. It's a shared environment. Your testing should be based on Premium and here's an official [sample](https://github.com/Azure-Samples/service-bus-dotnet-messaging-performance).

**Comment by grik001** [comment]
But should I expect a point were I do not receive any message for a couple of minutes? I understand performance can vary but I cannot figure out why I get no messages.

**Comment by SeanFeldman** [comment]
Briefly looked at the code

1. Do not mix old and new client.
1. Do not complete a single message at a time if you have multiple messages locktokens.
1. Use async code w/o `.Wait`/`.Result`.
1. When benchmarking, do not send and receive using the same process/client.
1. Do not create clients dynamically for each operation using connection sting - you're establishing a new connection each time and that's a killer.
   1. Helper class `ServiceBusHelper` should not create new clients.

Recommend to go over official samples rather than create your own. That includes benchmarking as well.

PS: also, avoid checking in `obj`, `bin`, and `packages` folder 🙂

**Comment by grik001** [comment]
Hi Sean,

Yes removed bin/obj/packages a few hours ago, had to go out so just committed asap and forgot to add gitignore :) 

1) I am sure I did this for a reason, will review it though
2) This code is an API and accepts requests for a single lock
3) I am only using Wait and Result in the main thread since I do not need to console to remain responseive, I do not think this is related to the receiver
4) I will split to test, but I have the same situation in an API
5) It is not, I am re using all connection. 

Will do, thanks for your help. Any remarks regarding my replies please?

**Comment by grik001** [comment]
Hi Sean,

So basically I now understand why this is happening. Regarding point one, the reason I am using the old Library is to be able to complete the call from a different Receiver. The reason I needed this is because I have 3 seperate API calls for Send, Receive and Complete.

Regarding the MessageReceiver choking, its because I was not completing the messages on the **new** MessageReceiver thus was stopping to work after around 5000k messages received.

**Comment by SeanFeldman** [comment]
@grik001 if you can, perfer Microsoft.Azure.ServiceBus over WindowsAzure.ServiceBus. The latter is considered a legacy library. Also, some behaviours you'll have with legacy library is not what you'll need to do in the new one (completing messages has to be done with the **same** client, connection pooling is manual, number of connections, etc). Cheers.

**Comment by grik001** [comment]
Hi Sean,

So to confirm I am understanding you correctly. With the new library I need to complete messages with the same client is that correct?

Feel free to close this ticket.

**Comment by SeanFeldman** [comment]
Yes, correct.
Can't close the issue. You'd have to do it 🙂

**Comment by grik001** [comment]
Oh ok :D 

Thanks for all your help Sean!

**Comment by grik001** [comment]
Oh ok :D 

Thanks for all your help Sean!
