### ISSUE TITLE
Service bus does not respect roles inherited from groups when trying to access SB with MSI

### ISSUE THREAD

**Issue by maxiptah** [Azure/azure-service-bus#246]
# Description

## Actual Behavior
1. Set up a service with managed service identity
2. Grant to this MSI Owner role through a group in RBAC
3. Service gets "unauthorized" when trying to access the Service Bus.
4. If service has Owner role directly, access works as expected.

## Expected Behavior
1. Roles inherited from elsewhere are respected.

**Comment by axisc** [comment]
cc: @ShubhaVijayasarathy  for MSI/RBAC related queries

**Comment by AnthonyDewhirst** [comment]
Is there anything happening with this? I see the exact same issue

**Comment by LeroyK** [comment]
I am currently having an issue where listing topics using an MSI access token works, but listing subscriptions gives unauthorized access. It might be related to this.

This is however with the Owner role directly assigned on the service bus namespace.

Any updates on this issue?

**Comment by EldertGrootenboer** [comment]
If this issue still occurs using the latest SDK, please let us know and we can re-open the issue.
