### ISSUE TITLE
5.0.1 not signed?

### ISSUE THREAD

**Issue by danielmarbach** [Azure/azure-service-bus#248]
Recently 5.0.1 was released on nuget but it looks like that release was not signed. Our build servers are breaking with 5.0.1 with the following build error

```
[Step 3/4]   ----> Could not load file or assembly 'Microsoft.ServiceBus, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)
```

### 5.0.0

![image](https://user-images.githubusercontent.com/174258/48192106-2c498900-e347-11e8-9aab-b143e213da14.png)

### 5.0.1

![image](https://user-images.githubusercontent.com/174258/48192512-4a63b900-e348-11e8-82f2-f9a1192fc2a7.png)

// cc @yvesgoeleven @SeanFeldman

**Comment by vinaysurya** [comment]
Uploaded a new package with signed binaries.
https://www.nuget.org/packages/WindowsAzure.ServiceBus/5.0.2

**Comment by danielmarbach** [comment]
Great, thanks! Did you unlist 5.0.1?

**Comment by SeanFeldman** [comment]
@danielmarbach yep, it's unlisted.
