### ISSUE TITLE
Auto-forwarding of dead-lettered messages as a result of exceeded max number of hops is not working

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus#249]
# Description

This is an issue raised earlier in #33. Raising a separate issue to solely focus on the server-side behaviour that is not working.

## Use case

In a system with dozens or hundreds of queues, it is far from ideal to monitor individual dead-letter queues. Instead, a centralized dead-letter queue is used to consolidate all dead-lettered messages. Centralized DLQ is then monitored.

## Expected Behavior
1.  A set of entities auto-forwards messages one to another (`a` --> `b` --> `c` --> `d` --> `destination`).
1. All queues auto-forward dead-lettered messages to the centralized dead-letter queue `dlq`.
1. Send a message to `a` and see it going to `dlq` with `DeadLetterReason` header.

## Actual Behavior
Dead-lettered message are **not** auto-forwarded despite the configuration.
![image](https://user-images.githubusercontent.com/1309622/48500100-42e45a00-e7f7-11e8-99c8-4d115129f2c5.png)

[Repro code](https://github.com/Azure/azure-service-bus/files/2581838/forwarding.and.dlq.forwarding.linq.txt)

**Comment by SeanFeldman** [comment]
I've updated issue description to match a real world use case and up-to-date repro.
The issue is _not_ about endless forwarding, but about ability to centralize dead-lettered messages for efficient and practical monitoring. /cc @axisc

**Comment by axisc** [comment]
Not sure if centralization of DL messages has much value add over keeping them separate to better localize the correction logic. It can be achieved by a simple application though.

In any case, disabling auto-forwarding when the max number of hops is exceeded is a feature (as you probably know)
