### ISSUE TITLE
Auto Forward does not guarantee "at least once delivery"

### ISSUE THREAD

**Issue by KuehneThomas** [Azure/azure-service-bus#252]
# Description
We had an issue with an Azure Premium Service Bus where messages were picked up by the auto fowarder from the subscription but were not delivered to the attached queue.

According to the support, only the primary entity (topic + subscription) guarantees "at least once delivery" but not the secondary queue.

The documentation does not explicitly mention this distinction:
https://docs.microsoft.com/en-us/azure/event-grid/compare-messaging-services
https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-auto-forwarding

## Actual Behavior
Auto forward does not guarantee "at least once delivery"

## Expected Behavior
Auto forward should guarantee "at least once delivery"

**Comment by SeanFeldman** [comment]
This sounds suspicious.
Could you describe your message flow scenario? Was it forwarded several times?
When failed to be forwarded, was it dead-lettered?

**Comment by KuehneThomas** [comment]
It was forwarded only once, from a subscription to a queue. No, it was not dead lettered. MS support analyzed the issue and the root cause was described as "memory state out of sync" inside the service bus. Resolution was: "resetting the in memory state".

However, the actual point is that there is no "at least once delivery" guarantee. This issue just revealed that circumstance since we were not aware of it before.

**Comment by SeanFeldman** [comment]
Sounds like a broker bug. Forwarding is a guaranteed operation. I'd freak out if it wasn't 🙂

**Comment by axisc** [comment]
This is a bug - has been fixed for Premium though. Will look to resolve this for Standard as well. No ETA for now.

**Comment by KuehneThomas** [comment]
Just to clarify that: According to the MS support there was a known defect which caused a message loss in our premium service bus. However, it was also stated that there is no "at least once delivery" guarantee neither in the standard nor in the premium service bus regarding the auto-forwarding.

What exactly has been fixed?

**Comment by SeanFeldman** [comment]
@KuehneThomas, regarding:

> However, it was also stated that there is no "at least once delivery" guarantee neither in the standard nor in the premium service bus regarding the auto-forwarding.

There's no _at-least-once_ delivery because auto-forwarding is _exactly-once_ delivery.

**Comment by KuehneThomas** [comment]
Sounds really good! However, I am still worried since the MS support was very clear that there is no guarantee at all that a message is forwarded from the subscription ("primary entity") to the queue ("secondary entity").

Furthermore, I wasn't able to find neither the exactly-once delivery nor the distinction between primary and secondary entity in the documentation of the service bus in general or the auto forwarding:

https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-auto-forwarding
https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-azure-and-service-bus-queues-compared-contrasted 
=> "At-Most-Once" is mentioned but only when using session state

Could you provide me a link to the documentation regarding the exactly-once auto-forwarding guarantee?

Thanks in advance!

**Comment by SeanFeldman** [comment]
I'm sure @axisc would agree documentation has to be updated.

@sethmanheim or @spelluru - do you know who could help with clarifying [auto-forwarding article](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-auto-forwarding)? (also a good opportunity to change "autoforwarding" to "auto-forwarding" 🙂). Thank you.

**Comment by nemakam** [comment]
@KuehneThomas 
I am a developer at ServiceBus. I'm sorry that there seems to be some kind of misunderstanding / miscommunication somewhere.
Auto-Forwarding **IS a lossless operation**. And like @SeanFeldman mentioned, with the current implementation, it has an exactly-once semantics. 
In the recent past there was a bug which might have showed up in your namespace. But as for expectations - you will not be losing any messages.
We have noted down the lack of details on our documentation page and we will work on improving it. Thanks for pointing it out. I'm closing this issue as a "not an issue"
