### ISSUE TITLE
Service Bus Scheduled Message Count Is Negative 

### ISSUE THREAD

**Issue by rcreynolds53** [Azure/azure-service-bus#254]
# Description

When cancelling scheduled messages without knowing the sequence number, I used the following 
code using the ServiceBus Message Receiver Class to peek at all messages and then cancel the scheduled messages async. Instead of stopping at zero, when there were no more messages to cancel, the service bus kept deleting messages from the scheduled queue and ended up with a negative number 

CODE 
`var messages = await messageReceiver.PeekAsync(250);
`          
 `do`
            `{`
                `Console.WriteLine(messages.Count);`
                `await Task.WhenAll(messages.Select(m =>`
               ` {`
                   ` Console.WriteLine(m.SystemProperties.SequenceNumber);`
                    `return queueClient.CancelScheduledMessageAsync(m.SystemProperties.SequenceNumber);`
                `}));`
                `messages = await messageReceiver.PeekAsync(250);`            
`} while (messages.Count > 0);`

Here is a picture of the message count: ![image](https://user-images.githubusercontent.com/26964362/50017578-1fe1cd00-ff92-11e8-8b12-8f16c46dcb99.png)
## Actual Behavior
1.  Service bus is displaying a negative number for the scheduled messages 

## Expected Behavior
1. When deleting the scheduled messages the service bus count should not be able to go negative.

**Comment by axisc** [comment]
Thanks for reporting this. we're tracking this internally.

**Comment by calvaradocl** [comment]
This is happening to me too, but I'm deleting the scheduled messages by their Sequence Number. Same negative information on both ServiceBusExplorer and Azure Portal.

**Comment by axisc** [comment]
we're currently working to fix this. I'll update and close this issue when we have sorted this out.

**Comment by SeanFeldman** [comment]
@axisc the label `backlog` is not exactly going along with [your comment](https://github.com/Azure/azure-service-bus/issues/254#issuecomment-485566448). Perhaps you meant to apply `in-progress` label?

**Comment by aresowj** [comment]
Hi @rcreynolds53 , just want to confirm for debugging purpose, was there any activities (scheduling / send / receive messages) while the deletion was going on? Thanks.

**Comment by aresowj** [comment]
Update: we have checked in the fix for both standard and premium messaging, the fix is expected to be included in the next major deployment.

**Comment by JSCProjects** [comment]
This is still happening within our subscriptions. Our sagas depend on scheduled messages and our ops team is complaining that they can't rely on this number.

**Comment by jrgcubano** [comment]
Same here. Still happening on our side.
