### ISSUE TITLE
Broker doesn't respect prefetch count for partitioned queue

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus#255]
# Description

Originated from SO [question](https://stackoverflow.com/questions/53748086/azure-service-bus-keeps-throwing-messagelocklostexceptions/).

When a Message Handler (using old or new client is used) set up, prefetch count on receiver is not respected. To reproduce the issue , use a repro [here](https://github.com/mywyb2/ServiceBusTest). Note: the linked code is using `AutoRenewTimeout` which could be removed from code to simplify analysis.

### Steps to repro:

1. Create a **partitioned ** queue with 30 sec `LockDuration`
1. Create  a message receiver with `PrefetchCount = 0` (default)
1. Set up message handler on the message receiver with the following options
  1. `AutoComplete = false`
  1. `MaxConcurrentCalls = 1`
1. Print the difference between message's `LockedUntilUtc` and current UTC date/time. 
1. Register a message handler that receives a message and emulates some work by using `await Task.Delay(10sec)`
1. Complete message

## Expected Behavior
Printed difference between message's `LockedUntilUtc` and current UTC date/time should be close to `LockDuration`. Messages should be processed in serial manner w/o throwing exceptions about lock, indicating that prefetch is not taking place, receiving one message at a time.

## Actual Behavior
Printed difference is dropping till lock lost exception is thrown. This indicated that are messages while _processed_ in a serial manner, are received in batches (prefetched), rather than being received one by one.

## Hypothesis

I suspect `PrefetchCount` is either not respected by the underlying AMQP library or by the broker when a queue is **partitioned**. While legacy client is handling messages better and doesn't throw an exception, it also seems to receive more than one message via prefetch, rather than a single message at a time.

**Comment by sandermvanvliet** [comment]
I've managed to reproduce this using the repro case you provided. Once you create a queue that is not partitioned the issue goes away.
Had a bit of a dig trough the Microsoft.Azure.Amqp sources but it doesn't have any reference to partitions at all which leads me to suspect this is an issue with Azure Service Bus itself.

**Comment by rmccabe24** [comment]
I am also seeing this problem when using the SubscriptionClient and MessageReceiver within my .net Core console application.  My SO issue is [here](https://stackoverflow.com/questions/53853306/renewlock-error-using-servicebus-subscriptionclient?noredirect=1#53853306).  


Unfortunately, we have already for production code running against Topics and reading messages where Partitioning is enabled using the .net Framework client.  And I cannot drain these Topics in order to delete and recreate without Partitioning.

**Comment by kaftw** [comment]
We're also experiencing this with some of our queues that have partitioning enabled.

**Comment by LinusDillon** [comment]
I believe we are seeing this also; 

- Single topic subscription with multiple concurrent listeners processing messages. 
- Prefetch set to zero. 
- Partitioned topic. 
- Standard tier. 
- .NET Full Framework

Can confirm I see intermittent cases where the SAME message is received by multiple listeners.

Any idea if Premium tier service bus will suffer from this?

**Comment by axisc** [comment]
Thanks for reporting this. We're investigating this internally.

@LinusDillon - I can confirm that this won't affect the Premium tier because Premium doesn't offer Partitioned entities.

**Comment by SeanFeldman** [comment]
According to @binzywu this is expected on partitioned entities.

**Comment by sandermvanvliet** [comment]
@seanfeldman is this made clear in service bus documentation somewhere? Would be nice so others don’t get surprised by this and only find this GitHub issue

**Comment by jholovacs** [comment]
This seems similar to what I'm seeing with queues.  @SeanFeldman you say this is expected on partitioned entities per @binzywu, can you reference that thread?  I'm confused why this behavior could be "expected".

**Comment by SeanFeldman** [comment]
@axisc would it be possible to refresh documentation on the topic? Then a link could be posted here to help everyone running into this. Thank you.
