### ISSUE TITLE
Intermittent issues with Deferred Messages.

### ISSUE THREAD

**Issue by tvperez76** [Azure/azure-service-bus#256]
# Description
There appears to be an issue where some deferred messages are peekable, but when attempting to receive the message via its SequenceId an exception is thrown.  
`MessageReceiver messageReceiver = new MessageReceiver(…);
var messages = await messageReceiver.PeekAsync(500).ConfigureAwait(false);
                if (messages != null)
                {
                    foreach (Message message in messages)
                    {
                        if (!message.SystemProperties.IsLockTokenSet)
                        {
                            var messageR2 = await messageReceiver2.ReceiveDeferredMessageAsync(message.SystemProperties.SequenceNumber).ConfigureAwait(false);
                            await messageReceiver2.AbandonAsync(messageR2.SystemProperties.LockToken).ConfigureAwait(false);
                        }
                    }
                }`

An interesting side note is that the messages appear to be erroneously marked as Active, when using the Service Bus Explorer tool while using AMQP.  However, when viewing the same messages via the NetMessaging protocol, the messages are marked as Deferred.

## Actual Behavior
1. When invoking the ReceiveDeferredMessageAsync() method, I get the following exception:
Failed to lock one or more specified messages. Either the message is already locked or does not exist.  TrackingId:4ba48261-bd82-45fa-b75c-5c797770ecd1_B50, SystemTracker:georeptest1:Topic:test2|attempt1, Timestamp:2018-12-18T17:50:01

## Expected Behavior
1. The deferred message to be retrieved so that it could be deleted properly.

**Comment by axisc** [comment]
@tvperez76  - it may have been a transient error, If you are still experiencing it, please open a support ticket.

closing for now
