### ISSUE TITLE
Unable to connect Service Bus Queue Using JMS

### ISSUE THREAD

**Issue by dnyaneshlb** [Azure/azure-service-bus#258]
# Description

## Actual Behavior
1. I have been following documentation provide in this repo. 

https://github.com/Azure/azure-service-bus/blob/master/samples/Java/qpid-jms-client/JmsQueueQuickstart/src/main/java/com/microsoft/azure/servicebus/samples/jmsqueuequickstart/JmsQueueQuickstart.java

I am trying to connect service bus queue using JMS (Qpid client). I am able to successfully connect and send messages but listening is not working.
To debug further, I started app in debug mode where I can see below error message while app bootstrap.
"proton.trace: IN: CH[13] : Detach{handle=0, closed=true, error=Error{condition=amqp:unauthorized-access, description='Unauthorized access. 'Listen' claim(s) are required to perform this operation. Resource:"
I have verified multiple times if SAS key I am using is having both Send and Listen Claims.
 

## Expected Behavior
1. I should be able to connect, send , listen messages successfully.

**Comment by axisc** [comment]
@dnyaneshlb if you still have this issue, please open a support ticket. 
If you've verified the SAS keys on your end, we'll need more information to investigate this, which the support team can help with.

I'm closing this issue for now.
