### ISSUE TITLE
Samples Missing for WindowsAzure.ServiceBus

### ISSUE THREAD

**Issue by asumner** [Azure/azure-service-bus#261]
# Description

## Actual Behavior
1. The documentation says "The samples in the Microsoft.ServiceBus.Messaging folder target the .NET Framework WindowsAzure.ServiceBus NuGet package, which is maintained for backwards compatibility." The samples all appear to have been converted to .Net Standard.

## Expected Behavior
1. Restore the Microsoft.ServiceBus.Messaging sample apps targeting WindowsAzure.ServiceBus  or update documentation and samples putting a note up that all WindowsAzure.ServiceBus have been removed?
2. Provide a link to the deprecation notice of WindowsAzure.ServiceBus nuget in favor of Microsoft.Azure.ServiceBus?

**Comment by dmarlow** [comment]
I second this. I was trying to locate the source for WindowsAzure.ServiceBus to see why `IMessageSender` is `internal` while the .NET Standard version is `public`. Is there a migration document to move towards the netstandard version somewhere? Where should WindowsAzure.ServiceBus related issues go?

**Comment by axisc** [comment]
you can open issues for the .NET standard SDK [here](https://github.com/Azure/azure-service-bus-dotnet)

We absolutely support WindowsAzure.ServiceBus for backcompat, but samples refer to the Microsoft.Azure.ServiceBus to avoid customers from basing their code on those. @spelluru - could we modify the document to make that more explicit.
