### ISSUE TITLE
Autoforwarding not working

### ISSUE THREAD

**Issue by johnknoop** [Azure/azure-service-bus#263]
I've setup the most basic forwarding scenario: A topic subscription (A) (without any rules) with forwarding to a different topic. But when I send test messages to the first topic, they just remain as active messages on subscription A, nothing gets forwarded.

I've tried setting up the topology using the Portal, the CLI and with ServiceBusExplorer. No difference.

I'm not sure how I can diagnose this issue. Does the broker have a log or something?

**Comment by SeanFeldman** [comment]
That sounds off.
I'd try to re-create your topics/subscriptions and see if any of those entities was "faulty".
In case that still doesn't work, could you supply a repro code/script to try out?

**Comment by johnknoop** [comment]
Thats weird... I just created two new topics with subscriptions as:

```
+---------------+       +---------------+
|Topic A        |    -> |Topic B        |
+---------------+   /   +---------------+
                   /
+---------------+ /     +---------------+
|Subscription A |-      |Subscription B |
+---------------+       +---------------+

```

And this time it works. Exactly the same settings, just different names. It must be something "on my side".

Thanks.
