### ISSUE TITLE
ScheduleMessageAsync when used with duplicate detection enabled

### ISSUE THREAD

**Issue by stevehurcombe** [Azure/azure-service-bus#265]
## Background
Consider a mobile app, with intermittent connectivity, the user wants to schedule a message for some point in the future. We'll use ScheduleMessageAsync with duplicate detection enabled. The messages get picked up by an Azure Function and processed using SendGrid. 

The user may wish to cancel and reschedule the message (hence the SequenceNumber is important) and we don't want them to receive duplicate messages. 

The queues ability to deduplicate messages is important as it solves issues with distributed locking.

## Actual Behavior
Given a queue with duplicate detection enabled, in this case the time window is set at 20 seconds, I received two sequence numbers. The second message is ignored, the first message survives.

I used a simple [Test] to verify this.

```
IQueueClient queueClient = new QueueClient(serviceBusConnectionString, "testqueue");

var message = new Message(Encoding.UTF8.GetBytes(JsonConvert.SerializeObject(sendEmailRequest)));
message.MessageId = "1"; // Prevent duplicate messages

// Return the sequence number for later cancellation if required
long SequenceNumber1 = await queueClient.ScheduleMessageAsync(message, sendEmailRequest.sendon);
long SequenceNumber2 = await queueClient.ScheduleMessageAsync(message, sendEmailRequest.sendon);
```

I store the SequenceNumber in order to be able to cancel the message later on. However the sequence number that I receive is actually the one for the message that failed. 

The client may not be aware of the first message due to network issues and therefore it will retry. It also won't be aware that the second message got discarded as there is no indication of this. Therefore I will not be able to cancel that message.

## Expected Behavior
I would like the SequenceNumber of the surviving message to be returned, regardless of how many times I attempt to add a message (while within the de-duplication window). 

- if I happen to add two scheduled messages (through normal communication issues) within the duplication window I want one to be dropped and I need the surviving sequence number to allow later cancellation

**Comment by stevehurcombe** [comment]
Anyone?
```We are trying to do our best, to at least reply to issues as fast as possible, yet in most cases please expect 5-7 business days.```

**Comment by SeanFeldman** [comment]
@binzywu any thoughts?

**Comment by stevehurcombe** [comment]
#266 is related BTW.

**Comment by EldertGrootenboer** [comment]
If this issue still occurs using the latest SDK, please let us know and we can re-open the issue.
