### ISSUE TITLE
ScheduleMessageAsync when used with duplicate detection enabled, second scenario

### ISSUE THREAD

**Issue by stevehurcombe** [Azure/azure-service-bus#266]
## Background
Consider a mobile app, with intermittent connectivity, the user wants to schedule a message for some point in the future. We'll use ScheduleMessageAsync with duplicate detection enabled. The messages get picked up by an Azure Function and processed using SendGrid. 

The user may wish to cancel and reschedule the message (hence the SequenceNumber is important) and we don't want them to receive duplicate messages. 

The queues ability to deduplicate messages is important as it solves issues with distributed locking.

## Actual Behavior
Given a queue with duplicate detection enabled and through issues with network connectivity, two messages will get added to the queue if they are added outside of the duplication window.

I used a simple [Test] to verify this.

```
IQueueClient queueClient = new QueueClient(serviceBusConnectionString, "testqueue");

var message = new Message(Encoding.UTF8.GetBytes(JsonConvert.SerializeObject(sendEmailRequest)));
message.MessageId = "1"; // Prevent duplicate messages

// Add two messages outside of the duplication window, but with the same delivery time
long SequenceNumber1 = await queueClient.ScheduleMessageAsync(message, sendEmailRequest.sendon);
Thread.Sleep(25000); 
long SequenceNumber2 = await queueClient.ScheduleMessageAsync(message, sendEmailRequest.sendon);
```

## Actual Behavior
When a scheduled message reaches its delivery date a new message is created. In this scenario both scheduled messages have identical sendon dates and so their new messages will hit the queue at the same time. These new messages are **not deduplicated** and two remain in the queue for processing. 

The first one has the state **active** and the second has the state **scheduled**. 

This seems odd in any case, I would have expected two active messages (if deduplication wasn't happening) or a single one if it was.

## Expected Behavior
I would have expected the dedeuplication process to have deduplicated messages based on their scheduled dates. 

The full scenario I'm trying to mitigate is this:

- if I happen to add two scheduled messages *outside* of the deduplication window (the user retries some time later on) but for a message for delivery in the same time slot, I would like the subsequent second messages to be deduplicated.

**Comment by axisc** [comment]
@stevehurcombe deduplication as a concept only exists between the sender and the broker in the given timeframe at the time of send. 
It's a good idea to set guardrails (i.e. the timeframe) to ensure better throughput/performance for your Service Bus namespace.

Also, regarding your use-case of a mobile app sending data to Service Bus, it won't scale well. 
Please consider having an abstraction layer between your mobile app and the Service Bus namespace that allows fan-in of the mobile app's requests.

Closing this for now, please reopen if needed.

**Comment by stevehurcombe** [comment]
Hi Ashish,
I simplified the scenario, the mobile app is using an Azure Function to manage the service bus.

However you missed this part of the problem:

"The first one has the state active and the second has the state scheduled.
This seems odd in any case, I would have expected two active messages (if deduplication wasn't happening) or a single one if it was."

If the de-duplication happens when the messages are added to the queue rather than when they leave (which I still argue is not useful in the case of Scheduled Messages) it isn't working when the messages are added outside of the window.

**Comment by stevehurcombe** [comment]
How do I reopen this issue? I can only edit.
