### ISSUE TITLE
Session state example doesn't use transactions

### ISSUE THREAD

**Issue by nickwalkmsft** [Azure/azure-service-bus#267]
I thought that a big part of the value of using session state (instead of some external state provider) is the ability to manipulate messages and commit state changes within single transaction. Is that not correct? The session state sample doesn't use transactions, and as a result is not resilient in a failover situation.

**Comment by SeanFeldman** [comment]
Related SO questions: [here](https://stackoverflow.com/questions/54717817/what-is-the-actual-meaning-value-and-usage-of-azure-service-bus-at-most-once).

**Comment by axisc** [comment]
@nickwalkmsft - thanks for reporting this. I'll add this to the backlog.

**Comment by EldertGrootenboer** [comment]
Closing this, as this was added back in 2020, but this issue was not closed at the time.
