### ISSUE TITLE
Inaccurate error message when using a reserved word

### ISSUE THREAD

**Issue by phillipsj** [Azure/azure-service-bus#269]
I ran into an issue when creating a Service Bus that consistently failed with the following message.

```
Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="The specified service namespace is invalid. CorrelationId: xxxxxxxxxx
```

I was not aware that there are naming restrictions as identified [here](https://docs.microsoft.com/en-us/rest/api/servicebus/create-namespace), which was what was causing my error. It would be helpful if the error message would contain either a link to this document or the specific reason why it failed. This would have saved time troubleshooting the error.

**Comment by arob98** [comment]
@spelluru - FYI

**Comment by spelluru** [comment]
@axisc - Can we update the message to be more specific? I will also need to update this article to mention the rules for namespace names: 
https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-quickstart-portal#create-a-namespace-in-the-azure-portal

**Comment by axisc** [comment]
Thanks for reporting this @phillipsj - I've added this to the backlog and we'll improve the error message.

@spelluru - thanks for making the changes to the documentation

**Comment by spelluru** [comment]
#please-close
I have added the following statement:
 For a list of rules for naming namespaces, see [Create Namespace REST API](https://docs.microsoft.com/en-us/rest/api/servicebus/create-namespace).

**Comment by axisc** [comment]
thanks @spelluru

**Comment by createchange** [comment]
FWIW, this messaging exists in the `Operational Details` section during an Azure deployment. 

The above clarification in the documentation did help me to realize that I had a resource name which was too long, but the messaging left me confused.

```json
{
     ...
    "resourceId": "/subscriptions/<subscription>/resourcegroups/SumoLogicNetworkWatcherEastUS/providers/Microsoft.EventHub/namespaces/SUMOBREvtHubNSSumoLogicNetworkWatcherEastUS2si33xr6n4p7k",
    "status": {
        "value": "Failed",
        "localizedValue": "Failed"
    },
    ...
    "submissionTimestamp": "2022-07-07T20:10:31.1106609Z",
    "properties": {
        "statusCode": "BadRequest",
        "statusMessage": "{\"error\":{\"message\":\"The specified service namespace is invalid. CorrelationId: bab07784-2956-44ec-a561-8f641346be42\",\"code\":\"BadRequest\"}}",
        "eventCategory": "Administrative",
        "entity": "/subscriptions/<subscription>/resourcegroups/SumoLogicNetworkWatcherEastUS/providers/Microsoft.EventHub/namespaces/SUMOBREvtHubNSSumoLogicNetworkWatcherEastUS2si33xr6n4p7k",
        "message": "Microsoft.EventHub/namespaces/write",
    },
    ...
}
```
