### ISSUE TITLE
Exception​Received​Event​Args.​Action is not documented

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus#27]
[`Exception​Received​Event​Args.​Action`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.exceptionreceivedeventargs.action?view=azureservicebus-4.0.0#Microsoft_ServiceBus_Messaging_ExceptionReceivedEventArgs_Action) received when [`On​Message​Options.​Exception​Received` event](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.onmessageoptions.exceptionreceived?view=azureservicebus-4.0.0) is raised, supposed to provide a clue what action has caused an exception.

Today, there's no way to discover what's the list of those actions, except running in production and logging all the actions. This is far from ideal. Needs to be documented properly to allow better guidance on how to deal with these exceptions (see issue #28).

**Comment by SeanFeldman** [comment]
cc @sethmanheim

**Comment by SeanFeldman** [comment]
@sethmanheim PR was merged. So this is fixed for the new client, but not for the old.

**Comment by sethmanheim** [comment]
We will need to have the dev team make any required changes to the documentation comments in the source code.

**Comment by sethmanheim** [comment]
Pretty sure this no longer exists in the library: https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.servicebus.exceptionreceivedeventargs?view=azure-dotnet. @SeanFeldman Please confirm.

**Comment by SeanFeldman** [comment]
It does @sethmanheim. [Here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.servicebus.exceptionreceivedcontext.action?view=azure-dotnet#Microsoft_Azure_ServiceBus_ExceptionReceivedContext_Action).

Though this issue originally was raised for the old client.

**Comment by sethmanheim** [comment]
OK, I see it now -- for some reason it was not showing up before (really).

**Comment by EldertGrootenboer** [comment]
If this issue still occurs using the latest SDK, please let us know and we can re-open the issue.
