### ISSUE TITLE
IMessage getMessageBody example

### ISSUE THREAD

**Issue by vlasceanuv** [Azure/azure-service-bus#271]
There is an error when i'm trying to see an example(https://github.com/Azure/azure-service-bus/blob/master/samples/Java/azure-servicebus/ReceiveLoop/.%5Csrc%5Cmain%5Cjava%5Ccom%5Cmicrosoft%5Cazure%5Cservicebus%5Csamples%5Creceiveloop%5CReceiveLoop.java).
If this is not available could you point to an example on how to use IMessage.getMessageBody() and not getBody() - because the last one is deprecated but is still in your documentation: https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-java-how-to-use-topics-subscriptions

**Comment by axisc** [comment]
it should actually point to [this](https://github.com/Azure/azure-service-bus/blob/master/samples/Java/azure-servicebus/ReceiveLoop/src/main/java/com/microsoft/azure/servicebus/samples/receiveloop/ReceiveLoop.java)

hope that helps.

**Comment by vlasceanuv** [comment]
getBody is deprecated so this link is not useful

**Comment by sivataras** [comment]
I have the same challange, without example, it's hard to implement

**Comment by vlasceanuv** [comment]
@axisc why is this fixed? The resolution was a deprecated one
