### ISSUE TITLE
Need SequenceNumber of enqueued service bus queue message

### ISSUE THREAD

**Issue by TaruchuAtWork** [Azure/azure-service-bus#272]
**Feature Request**

Hey Microsoft,

I'm building a messaging pipeline that needs the ability to put both direct and scheduled messages into multiple queues. I want to provide developers using my service the ability to put messages into a Queue and the ability to query for the status of a particular message.

Currently when I queue a Message using Microsoft.Azure.ServiceBus.QueueClient.SendAsync(Message) it doesn't look like the SystemProperties on the enqueued Message object get updated with the SequenceNumber, and the SendAsync method doesn't return a SequenceNumber either. To see if my message is on the queue I use the batch peek method called Microsoft.Azure.ServiceBus.Core. MessageReceiver.PeekAsync(Int32) and perform a linq query on the result in order to filter out one message based on a Microsoft.Azure.ServiceBus.Message.UserProperties key value pair that I assign before sending.

The overhead using this method should be apparent, as I may need to iterate the entire Queue depending on where the message is. I would ideally like to use the Peek method that accepts a sequence number argument and returns a single message that already exists called Microsoft.Azure. ServiceBus.Core.MessageReceiver.PeekBySequence. Is there a reason SendAsync doesn't update the SystemProperties of the Message object or return the sequence number directly?

Thanks :-)

**Comment by EldertGrootenboer** [comment]
If this is still a valid ask, please raise it in the Service Bus SDK repository.
