### ISSUE TITLE
Deploy to Azure button does not work

### ISSUE THREAD

**Issue by theangrydev** [Azure/azure-service-bus#273]
# Description

## Actual Behavior
1. Click the "Deploy to Azure" button on https://github.com/Azure/azure-service-bus/tree/master/samples/Java
2. The error "There was an error loading the template from URI 'https://github.com/azure/azure-service-bus/master/samples/Java/scripts/azuredeploy.json'. Ensure that the template is publicly accessible and does not have any comments." is displayed in Azure.

## Expected Behavior
1. The deployment of the sample script succeeds

**Comment by EldertGrootenboer** [comment]
The link has been fixed.
