### ISSUE TITLE
scripts/setupenv.ps1 is missing

### ISSUE THREAD

**Issue by ErikMogensen** [Azure/azure-service-bus#274]
Under the heading "Exploring and running the samples" in the file https://github.com/Azure/azure-service-bus/blob/master/samples/DotNet/Microsoft.Azure.ServiceBus/README.md it says:

> To make running the samples straightforward, there is a Powershell (Azure PS) script in scripts that will obtain the namespace connection string from your current Azure subscription, assume the entity names configured in the deployed templates, and export those into a configuration file in your user directory, eliminating the need to pass arguments on the command line.

> The Powershell script is scripts/setupenv.ps1. It needs to be called with the name of the Resource Group and the Service Bus namespace name as ordinal arguments.

But it seems that there is no setupenv.ps1 in this repository. I found instructions for creating a similar file manually at https://github.com/Azure/azure-service-bus/blob/master/samples/DotNet/Microsoft.Azure.ServiceBus/common/Main.md. The variables in that file does not seem to be used in any sample though.

To workaround this I created a file in my user folder called azure-msg-config.properties with the following content:
`SB_SAMPLES_CONNECTIONSTRING=<Connection string>`

It is probably important to end the line above with a new line.

**Comment by MaherJendoubi** [comment]
cc @SeanFeldman

**Comment by SeanFeldman** [comment]
PR #280 will fix this

**Comment by YhorbyMatias** [comment]
Is there any example of this file i ran the current ps script without any success, where can I create it manually?
@SeanFeldman

**Comment by SeanFeldman** [comment]
@YhorbyMatias if you follow the [PR](https://github.com/Azure/azure-service-bus/pull/280) associated with this issue you'll see that it was never merged. 

@axisc do you know who'd be able to wrap it after, ehm... 2 years? 😀

**Comment by YhorbyMatias** [comment]
HAHAH @SeanFeldman  yeah I followed the PR and I trying to run the file but does not create the config file

**Comment by YhorbyMatias** [comment]
That's the current content of the file script 


param (
    [Parameter(Mandatory=$true)][string]$resourceGroup,
    [Parameter(Mandatory=$true)][string]$namespaceName,
    [string]$ruleName="SendListen"
 )

$env:SB_SAMPLES_CONNECTIONSTRING=(Get-AzureRmServiceBusKey -ResourceGroupName $resourceGroup -Namespace $namespaceName -Name $rulename).PrimaryConnectionString
$env:SB_SAMPLES_QUEUENAME="BasicQueue"
$env:SB_SAMPLES_TOPICNAME="BasicTopic"
$env:SB_SAMPLES_SUBSCRIPTIONNAME="Subscription1"

**Comment by EldertGrootenboer** [comment]
PR has been merged. If this issue still occurs, please let us know and we can re-open the issue.
