### ISSUE TITLE
GetMessageSessions in a queue

### ISSUE THREAD

**Issue by CoenraadS** [Azure/azure-service-bus#275]
# Description
The other service bus package, webjobs.service bus has a function called `GetMessageSessions()` which will list all sessions of a queue.

This package does not have this, and I don't want to iterate over all messages in a queue to list the session id's.

**Comment by EldertGrootenboer** [comment]
We have opened an investigation task for this in our backlog to check the possibilities of exposing this, and will update this issue when we have more information.

**Comment by EldertGrootenboer** [comment]
Thank you for your feedback on this item, it helps us in our efforts to continuously prioritize the different requests we get from all our various feedback channels. We have added this feature in our backlog, however we currently don't have an ETA on when development might start on this. For now, to help us give this the right priority, it would be helpful to see others vote and support this feature, as well as explain their scenarios.

**Comment by miqm** [comment]
@EldertGrootenboer as for my scenario I'm using azure functions with keda on kubernetes. Session-enabled queue allows me to make a FIFO queue and ensure only one message is processed for a particular device (device ID is my session ID). In fact the order does not matter that much as scaling limitation. However devices will grow over time and the load on them is not equal. Therefore I'd like to have a dynamic way of scaling horizontally the workload.
What I'd need is a way to get number of sessions that have at least one active message. Although currently I can get list of sessions via AMQP command, I don't know how many (or if any) messages are waiting which can lead to unnecessary scaling.

Please re-prioritise implementing this functionality in the service bus.
