### ISSUE TITLE
Long running message processing ( > 20 mins) Partitioned Entities fails with MessageLockLostException

### ISSUE THREAD

**Issue by vinaysurya** [Azure/azure-service-bus#276]
### Symptoms
Long running message processing ( > 20 mins) with Partitioned Entities fails with MessageLockLostException

### Issue
This is an issue on the Service side, where the links are timing out after 20 mins even though the renew is happening

### Who's Affected
- Only if messages are being processed for more than 20 mins.
- Only on Partitioned Entities
- Only when using the [https://github.com/Azure/azure-service-bus-dotnet](url) library or using the AMQP Transport type with the [https://www.nuget.org/packages/WindowsAzure.ServiceBus](url) library

###  Workaround
- The issue does not happen with Entities created with 'EnablePartitioning' set to false. So if possible for your scenario, re-create entity with 'EnablePartitioning' set to false and the issue should not happen then.

### Fix
We are actively working on a fix for this and should be deployed with our next update to Service. We will post the date here as soon as we know. At this point expecting an ETA of about 3-4 weeks.

**Comment by SeanFeldman** [comment]
Origin: client repo issue: https://github.com/Azure/azure-service-bus-dotnet/issues/645

@vinaysurya the client issue probably can be closed. While this one could be labeled as `bug`. Would you agree?

**Comment by rondelward** [comment]
@vinaysurya I tried recreating my entity with `EnablePartitioning` set to false and I'm still able to reproduce this issue on the recreated queue. Though I did notice a minor improvement in frequency, we are still seeing the `MessageLockLost` exceptions when using the auto renew functionality in QueueClient. 

We did have 1 message successfully complete after a retry but another that failed to complete twice in a row (max delivery was set to 2). The processing for these operations is around an hr. 

Is it likely that this issue also affects non-partitioned queues?

**Comment by vinaysurya** [comment]
@rondelward, i did try the scenario with non-Partitioned entities and ran the same scenarios with completing messages after say 25 mins and did not repro the issue. 

1) Which library are you using
2) What is the Autorenewtimeout or MaxAutoRenewDuration set to?
3) Are you seeing a MessageLockLostException when it fails?

**Comment by vinaysurya** [comment]
@rondelward, I tried the scenario on a non-partitioned entity for processing messages > 1hr and I do not see the issue.  I tried the below sample for a couple of times just to make sure it works repeatedly.

Here's the sample I'm trying out. [Create Non-partitioned Queue with the name supplied to the MessageReceiver and send a message to it]

`static void Main(string[] args)
        {
            string ConnectionString = "blah";
            var receiver = new MessageReceiver(ConnectionString, "nonpartq");
           

            receiver.RegisterMessageHandler(DelaySome, new MessageHandlerOptions(LogException)
            {
                AutoComplete = true,
                MaxAutoRenewDuration = TimeSpan.FromMinutes(120)
            });

            Console.ReadLine();
        }

        static async Task DelaySome(Message message, CancellationToken cancellationToken)
        {
            Console.WriteLine($"[{DateTime.UtcNow}]: ---START MessageHandler---");
            await Task.Delay(60 * 60 * 1000);
            Console.WriteLine($"[{DateTime.UtcNow}]: ---END MessageHandler---");
        }

        public static Task LogException(ExceptionReceivedEventArgs args)
        {
            Console.WriteLine(args.Exception.ToString());
            return Task.CompletedTask;
        }`

**Comment by rondelward** [comment]
@vinaysurya I'm using libraries:
Microsoft.Azure.ServiceBus: 3.1.0
Microsoft.Azure.Amqp: 2.3.0

The only difference I see code-wise is that we're not using `AutoComplete` though that doesn't seem like it should cause the problem. I had run simpler test with a trace using updated libraries but this was before recreating the entity (my repro steps here https://github.com/Azure/azure-service-bus-dotnet/issues/684).

I can try this again after updating the libraries if you believe there is a chance I'm seeing a different issue.

**Comment by vinaysurya** [comment]
@rondelward, I tried using the same library the 3.1.0 version and changed to do Complete myself and it works fine. Tried a couple of times to be sure and it worked both times without failures. Couple of questions
1) Do you have AutoComplete set to false from the RegisterMessageHandler?
2) Are you using a standard or premium namespace. It should not matter but just to make sure we are testing against the same things.

**Comment by rondelward** [comment]
Here is a stripped down version of what we're doing for reference here

```
                 _queueClient.RegisterMessageHandler(
                    async (message, token) =>
                    {
                        try
                        {
                            processMessage(message); // await Task.Delay(...)
                            await _queueClient.CompleteAsync(message.SystemProperties.LockToken);
                        }
                        catch (Exception ex)
                        {
                            await _queueClient.CompleteAsync(message.SystemProperties.LockToken);
                        }
                    },
                    new MessageHandlerOptions(OnException)
                    {
                        AutoComplete = false,
                        MaxConcurrentCalls = MaxConcurrentCalls, // 1
                        MaxAutoRenewDuration = MaxAutoRenewDuration // 2 hrs
                    }
                );
```

Let me know if anything there seems off. We're using standard queues with a Pay-as-you-go subscription. 

I will run another test with `await Task.Delay` instead of our processing logic to see if I can reproduce. Our processing is synchronous and fairly CPU intensive so will try to rule out any weirdness there

**Comment by vinaysurya** [comment]
The fix for the issue was deployed to all scaleunits by 4/15/2019. So this issue should be resolved. Please check and let us know if you are still seeing the issue.

**Comment by rowanb** [comment]
I'm still seeing this issue with a function running > 20 minutes on functions v1  using Microsoft.Azure.ServiceBus 2.2.0, with a non-partitioned entity. Did the fix get applied to the v1 libraries?

**Comment by SeanFeldman** [comment]
@rowanb 2.2.0 is fairly old. 3.4.0 is the latest and as you can see there were some bug fixes. While not sure if it's related, any chance you could verify with the latest version?

**Comment by rowanb** [comment]
Doesn't 3.x require functions v2? We're still on v1.On 23 May 2019 03:39, Sean Feldman <notifications@github.com> wrote:@rowanb 2.2.0 is fairly old. 3.4.0 is the latest and as you can see there were some bug fixes. While not sure if it's related, any chance you could verify with the latest version?

**Comment by rowanb** [comment]
> Increasing the service bus entity lock duration from 1 minute to 5 minutes seems to have helped.

I don't see the exception any more but I still see messages going into the dead letter queue despite being successfully processed.

**Comment by SeanFeldman** [comment]
Check the dead-lettering reason (header on the dead-lettered messages). It should tell you why this happened.

**Comment by rowanb** [comment]
> Check the dead-lettering reason (header on the dead-lettered messages). It should tell you why this happened.

It's always MaxDeliveryCountExceed but I assume this is because the message isn't completed due to the lock being lost, which causes it to be reprocessed (I have max delivery count set to 1 on the subscription).

**Comment by SeanFeldman** [comment]
Maximum delivery count of 1 is not a good idea.
And if your processing is taking 20-50 minutes, lock will be lost and the message will be picked up by another Function instance.

**Comment by rowanb** [comment]
But if i have autoRenewTimeout up to 1 hour shouldn't it be able to renew the lock?

**Comment by SeanFeldman** [comment]
In theory yes, but this is not a guaranteed operation. A client could make a request, and request be unsuccessful, causing the lock to be lost.

**Comment by rowanb** [comment]
@SeanFeldman understood. Just to confirm, what is the latest library version we should be using with v1? Is it 2.3.0? The documentation states 3.x libraries are for v2 is that correct?

**Comment by SeanFeldman** [comment]
@rowanb this is probably a good question for the WebJobs SDK team, https://github.com/Azure/azure-webjobs-sdk
