### ISSUE TITLE
OnMessageOptions.ExceptionReceived is not documented properly

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus#28]
Quoting the sole [source of documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.onmessageoptions.exceptionreceived?view=azureservicebus-4.0.0) on this event handler:

> Occurs when an exception is received. Enables you to be notified of any errors encountered by the message pump. When errors are received calls will automatically be retried, so this is informational.

While it's clear that exceptions are received, it doesn't actually go into explaining what exceptions should or should not be handled. 

For example, when there's a `TimeoutException`, which cannot be determined as transient or not since it's not of the [`MessagingException`](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-messaging-exceptions), but it's happening as a result of a failing lock renewal operation. Such a failing operation can be considered a transient error and exception can be swallowed. For other cases of `TimeoutException` it might be a bad idea to swallow exception. Unfortunately, in addition to lacking documentation/guidance on this event handler, [`Exception​Received​Event​Args.Action`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.exceptionreceivedeventargs.action?view=azureservicebus-4.0.0#Microsoft_ServiceBus_Messaging_ExceptionReceivedEventArgs_Action) has no documentation whatsoever. Separate issue raised, #27.

Give the fact that one cannot mimic all the exceptions raised by the broker, this API should have a better documentation to help developers handle exceptions that **will** be happening in production.

**Comment by SeanFeldman** [comment]
@sethmanheim any updates on this one? Thanks.

**Comment by sethmanheim** [comment]
@seanfeldman I don't, sorry. We need this API documentation to come from the development team.

**Comment by SeanFeldman** [comment]
I'm on a fence with your suggestion @sethmanheim. And this is why.

Documentation embedded into code should focus on **API documentaiton**. I.e. short description to provide immediate orientation, type description and potential remarks if such exist. A good example would be documentation issue #37 or #20. That can be handled by a remark in XML doc.

Documentation that is more of a **guidance** such as this case as well as #4 or #16,  should not be coupled with the code. Here are the reasons:

1. Clarifications on the guidance and updates should not be tied into code release/modifications.
1. Guidance should not be rendered down to API documentation. Then it's no longer guidance.
1. Developers are not always the best ones to describe their own work (what do you mean my child is not perfect?! It is for me! 🙂)
1. Comparison charts/tables, visuals, content of more than a sentence or two don't really belong to XML doco.

If you ask today what people need from documentation - they most likely say "guidance" and not "API documentation".

Hopefully this helps.

**Comment by sethmanheim** [comment]
@SeanFeldman All good points, and I will certainly add your request to the backlog. I was simply addressing the major point of this issue which seemed to be summarized by "this API should have a better documentation".

**Comment by SeanFeldman** [comment]
Good example of API doco attempted for guidance [going rough](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.messagesender?redirectedfrom=MSDN&view=azureservicebus-4.0.0#remarks).

**Comment by sethmanheim** [comment]
@SeanFeldman Not sure what your last comment means, can you clarify?

**Comment by SeanFeldman** [comment]
I've linked it in the [comment ](https://github.com/Azure/azure-service-bus/issues/28#issuecomment-311378346)@sethmanheim. Here's the visual:
![image](https://user-images.githubusercontent.com/1309622/29642578-e8bfb424-8826-11e7-9289-183b0b5eab7a.png)

**Comment by sethmanheim** [comment]
@SeanFeldman Ah OK, I see what you're referring to. That sure is ugly!

**Comment by EldertGrootenboer** [comment]
If this issue still occurs using the latest SDK, please let us know and we can re-open the issue.
