### ISSUE TITLE
writing in a queue and waiting for your reply in another

### ISSUE THREAD

**Issue by henriqueweiand** [Azure/azure-service-bus#283]
I'm using the sdk of the service bus to send to a queue and listen for the answer in another, but I can not find valid examples of how to make that flow. My biggest difficulty is being able to set reply_to and reply_to_group_id, as I did in the old versions directly in the MessageProperties, now in the class Message I am in doubt with what to inform in the index 'message' to achieve this objective

**Comment by SeanFeldman** [comment]
@henriqueweiand this repository is a server side issue track repo. Not the .NET client.

For documentation: https://docs.microsoft.com/en-us/azure/service-bus-messaging/
.NET Client repository and issue tracker: https://github.com/Azure/azure-service-bus-dotnet/
Samples: https://github.com/Azure/azure-service-bus/tree/master/samples/

**Comment by henriqueweiand** [comment]
I mean sdk with use with python, but thanks anyway ... the examples are complicated to find ... the documentation is very weak for this
