### ISSUE TITLE
Null reference exception when space appears on the begining of connection string

### ISSUE THREAD

**Issue by ddobric** [Azure/azure-service-bus#285]
I have following statement:

new ManagementClient("Endpoint=sb://abcdef.servicebus.windows.net/;...**=")

when appending space in fromt of connection string, initialization fails with NULL reference exception.

new ManagementClient(" Endpoint=sb://abcdef.servicebus.windows.net/;...**=")

It would be helpfull to:
1. implement trimm END/START
2. Throw appropriate exception 

Damir

**Comment by SeanFeldman** [comment]
@ddobric you might want to move it to the client issue tracker here: https://github.com/Azure/azure-sdk-for-net/issues

**Comment by ddobric** [comment]
Ok. Thanks :)
