### ISSUE TITLE
Sending Events from Storage Account to Service Bus Queue via Event Grid

### ISSUE THREAD

**Issue by fabich** [Azure/azure-service-bus#286]
# Description
Creating an event subscription in Azure Storage with endpoint type Service Bus Queue results in wrong messages received by subscriber.
Message content can not be read.

![image](https://user-images.githubusercontent.com/727420/58807204-ee2ff180-8617-11e9-9b50-fa4a6e3ee764.png)

## Actual Behavior
According to @PramodValavala-MSFT missing Content Type set on the incoming message

## Expected Behavior
Receive event that contains information regarding blob create / delete event

Originally posted here: https://github.com/MicrosoftDocs/azure-docs/issues/32062

**Comment by SeanFeldman** [comment]
Could you please provide the full stacktrace?

I'm not entirely sure this is a Service Bus broker issue. EventGrid is the one that is emitting the event. It's the one that creates the payload and populates the headers (such as `aeg-delivery-count`). It should also provide the value for the `content-type` header, which is btw needed by the Function you're trying to trigger by the ASB message.

**Comment by fabich** [comment]
@SeanFeldman I think so as well. This is most likely an EventGrid problem.
But there is no repo for EventGrid to post this issue.

**Comment by PramodValavala-MSFT** [comment]
@fabich @SeanFeldman I have checked with the team internally and a fix is being worked on from the Event Grid side.

I will keep this thread(s) updated with the details once I know more.

**Comment by PramodValavala-MSFT** [comment]
@fabich @SeanFeldman This has been fixed

**Comment by fabich** [comment]
@PramodValavala-MSFT thanks for the update.
I will give it a try

**Comment by fabich** [comment]
bug is fixed.
@PramodValavala-MSFT thank you for your help!
