### ISSUE TITLE
Receive Deferred Message by sequence number from partitioned topic

### ISSUE THREAD

**Issue by Blackbaud-JeffreyAaron** [Azure/azure-service-bus#287]
# Description

I am running into an issue with the Microsoft.Azure.ServiceBus.Core.MessageReciever, but the `azure-service-bus-dotnet` repo appears to be archived, so I'm unable to create an issue in that repo.

## Background:
I am attempting to use IMessageReceiver to preview/reprocess/complete messages from the DeadLetterQueue of a subscription to a partitioned topic. IMessageReceiver.PeekAsync allows listing the messages in the DLQ. IMessageReceiver.ReceiveAsync allows me to iterate through the messages to find the targeted sequence number for the message to reprocess and/or complete. Any messages received other than the targeted message must be deferred to prevent an endless receive loop. The issue arises when attempting to receive one of the previously deferred messages.

## Actual Behavior
1. Calling IMessageReciever.ReceiveDeferredMessageAsync(long) or IMessageReciever.ReceiveDeferredMessageAsync(list<long>) on a partitioned topic is raising the following error on line 1154 of MessageReceiver.OnReceiveDeferredMessageAsync
>ReceiveBatch of sequence numbers from different partitions is not supported for an entity with partitioning enabled.

## Expected Behavior
1. Calling IMessageReciever.ReceiveDeferredMessageAsync(long) or IMessageReciever.ReceiveDeferredMessageAsync(list<long>) on a partitioned topic should return the deferred message from whichever partition.
2. Or...there should be a way for me to specify the partitionId in the request

**Comment by SeanFeldman** [comment]
[`readme.md`](https://github.com/Azure/azure-service-bus-dotnet/blob/dev/README.md#weve-moved) states that the repository has moved.
The new location for the .NET SDK is here: https://github.com/Azure/azure-sdk-for-net/
