### ISSUE TITLE
AMQP 0.9.1 support?

### ISSUE THREAD

**Issue by Tiberriver256** [Azure/azure-service-bus#288]
Hello,

It doesn't appear that azure-service-bus supports AMQP 0.9.1 which limits the options for AMQP clients. Would it be possible to add support for 0.9.1?

**Comment by axisc** [comment]
@Tiberriver256 , we don't have plans right now to support AMQP 0.9.x. 

I'm closing the issue for now, please feel free to reopen if you have more questions.

**Comment by Tiberriver256** [comment]
Thank you for the response
