### ISSUE TITLE
Surprise: Non-sessioned and sessioned messages not mixable

### ISSUE THREAD

**Issue by vhe1** [Azure/azure-service-bus#289]
# Description

## Actual Behavior
1. When sending a message without a session if to a queue with session "_support_" "_enabled_", I get an exception "The SessionId was not set on a message, and it cannot be sent to the entity. Entities that have session support enabled can only receive messages that have the SessionId set to a valid value. ..."

I haven't seen this anywhere in the documentation.

## Expected Behavior
"enabled support" is, to me, very different from "forced to use". So, from reading the documentation I expected that this is a supported feature, i.e. an add-on to the normal functionality and that normal messages still work and behave like before. So, 
1. either make it clear in the documentation that I can't mix the two message types, i.e. that "enabling" one type of messages actually _disables_ the other type and I have to use two queues. Maybe call it "queue type" and it has two values "sessioned" and "unsessioned" with distinct performance and data characteristics.
2. or make make the feature "supported" only, i.e. so that it's _in addition_ to the normal functionality and non-session type messages get processed normally, with non-sessioned clients.

**Comment by SeanFeldman** [comment]
Just a suggestion - link to the documentation page.

> make it clear in the documentation that I can't mix the two message types

That's more likely to happen. You could raise an issue for that documentation article or submit a PR.

**Comment by axisc** [comment]
Thanks for raising this. I've made the doc change for this. :)
