### ISSUE TITLE
Microsoft.ServiceBus.Messaging: QueueClient.GetMessageSessions() showing sessions present even when (seemingly) there are none

### ISSUE THREAD

**Issue by boylec** [Azure/azure-service-bus#290]
# Description
QueueClient.GetMessages() returning inaccurate session count - from multiple different processes, after shutting down a process and running it from another process against the same queue, the result is the same.

## Actual Behavior
1. Queued several messages across different session ids.
2. Completed those messages, and called close on the sessions.
3. Calling QueueClient.GetMessageSessions() return 2 sessions, even after several hours, or shutting the process down and starting a new one and running the method against the same queue. Messages are not present in the queue, but QueueClient.GetMessageSessions() is still returning those 2 MessageSession objects.
4. This is repeatable using the code that caused it the first time. I set up a separate test to try and reproduce it with brand new code from scratch, and a brand new queue, but cannot. There is something specific to this queue or the code/package running it that is causing it to happen every time.

## Expected Behavior
1. Queue several messages across different session ids.
2. Call complete on messages and Close() on their respective MessageSession objects.
3. Call QueueClient.GetMessageSessions() and it should return 0 sessions.

From where does the QueueClient.GetMessageSessions retrieve the sessions if not examining the messages themselves (in Microsoft.ServiceBus.Messaging)? Because the messages are gone, but its still reporting sessions in existence.

Returned session object(s) - they both look the exact same except the session ID of course:
`{
  "Path": "{maskedqueuename}",
  "PrefetchCount": 0,
  "LastPeekedSequenceNumber": -1,
  "LockedUntilUtc": "0001-01-01T00:00:00",
  "IsExclusiveMode": false,
  "LockToken": null,
  "SessionId": "{maskedsessionid}",
  "BatchFlushInterval": "00:00:00",
  "Mode": 0,
  "RetryPolicy": {
    "MinimalBackoff": "00:00:00",
    "MaximumBackoff": "00:00:30",
    "DeltaBackoff": "00:00:03",
    "TerminationTimeBuffer": "00:00:05",
    "MaxRetryCount": 10
  },
  "IsClosed": false
}`

**Comment by EldertGrootenboer** [comment]
If this issue still occurs using the latest SDK, please let us know and we can re-open the issue.

**Comment by boylec** [comment]
I've since moved on from this project so I won't be testing it again just FYI.
