### ISSUE TITLE
AcceptMessageSession does not work correctly

### ISSUE THREAD

**Issue by ddobric** [Azure/azure-service-bus#292]
Method **AcceptMessageSession** does not behave correctly. I have a feeling that always block for undetermined amount of time.
For example, following will block for 2min, 3,min etc. Every time different time:
   
`var session = await this.SessionClient.AcceptMessageSessionAsync(TimeSpan.FromSeconds(10));`
      
This exception sis thrown if no session accepted. However, after waiting for 3 or 5 min, it always throws: 59sec.

> Microsoft.Azure.ServiceBus.ServiceBusTimeoutException: 'The operation did not complete within the allocated time 00:00:59.9321129 for object receiver258.'

**Comment by SeanFeldman** [comment]
@ddobric I have a feeling this is more client-related issue than the broker. If it proves to be the case, client repo has moved and issue tracker is here: https://github.com/Azure/azure-sdk-for-net/issues
