### ISSUE TITLE
[feature] Provide cancellation token in AcceptMessageSession 

### ISSUE THREAD

**Issue by ddobric** [Azure/azure-service-bus#293]
Method AcceptMessageSession should make a usage of cancellation.

`AcceptMessageSession (TimeSpan, CancellationToken)`

Following code could be in this case simplified:

 ```csharp
 public async Task Start(CancellationToken cancelToken)
        {
            Task[] tasks = new Task[2];

            tasks[0] = Task.Run(async () =>
            {
                while (!cancelToken.IsCancellationRequested)
                {
                    try
                    {
                        var session = await this.SessionClient.AcceptMessageSessionAsync();
                        Debug.WriteLine($"Session: {session.SessionId}");                      
                    }
                    catch (ServiceBusTimeoutException ex)
                    {
                      
                    }
                }
            }, cancelToken);

            tasks[1] = Task.Run(async ()=> {
                while (!cancelToken.IsCancellationRequested)
                {
                    await Task.Delay(500);
                }
            });

            Task.WaitAny(tasks);
        } 

```

With cancellation:

 ```csharp
 public async Task Start(CancellationToken cancelToken)
        {
            Task[] tasks = new Task[2];

            tasks[0] = Task.Run(async () =>
            {
                while (!cancelToken.IsCancellationRequested)
                {
                    try
                    {
                        var session = await this.SessionClient.AcceptMessageSessionAsync(cancelToken);                      
                    }
                    catch (ServiceBusTimeoutException ex)
                    {
                    }
                }
            }, cancelToken);
        }
```

**Comment by SeanFeldman** [comment]
It's not just `AcceptMessageSession()` almost all async operations that involve IO work should have that support. For example: https://github.com/Azure/azure-service-bus-dotnet/issues/439, https://github.com/Azure/azure-service-bus-dotnet/issues/258, and https://github.com/Azure/azure-service-bus-dotnet/issues/675.

This is an issue with the client in general. I've tried to convince [here](https://github.com/Azure/azure-service-bus-dotnet/issues/439#issuecomment-423770087), but it didn't happen. With the client moving to a new repository, I'll raise it there (https://github.com/Azure/azure-sdk-for-net/issues/6653), which you can upvote if you'd like. Either way, it belongs to https://github.com/Azure/azure-sdk-for-net/

**Comment by Areson** [comment]
I'd like to add my support to this as well. I have a message queue feeding a constrained resource, and from time to time that resource will issue an alert that it needs to stop processing for a time. I have to close the QueueClient at that point, but the message pumps keep functioning despite the client being closed, which causes a lot of noise.

**Comment by Mortana89** [comment]
Same here, we should be able to suspend the message pump without closing the client (sending should still be possible)

**Comment by EldertGrootenboer** [comment]
If this issue still occurs using the latest SDK, please let us know and we can re-open the issue.
