### ISSUE TITLE
Issue with JMS APIs for Azure Service Bus Topic

### ISSUE THREAD

**Issue by kalungevinayak** [Azure/azure-service-bus#295]
* Spring Boot 2.0.3 + Spring JMS + AMQP + QPid

Followed Microsoft Document: 
https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-java-how-to-use-jms-api-amqp

# Description
I have developed a spring boot microservice for receiving data from the service bus topic using JMS APIs and storing it into the azure cosmosdb.
I have set a message listener to listen to messages asynchronously. I'm stuck into a situation where my service is locking a batch of messages at once from the service bus topic to read and process them. From my understanding, once my service started listening to incoming messages it is locking a batch of messages(not known) at a time and sending an acknowledgement of each message one by one. As it locks batch of messages at a time, the LOCK DURATION TIME (number of seconds for which a message will be blocked by a receiver once it receives it so that no other receiver can receive that message) of all messages starts and messages whose acknowledgement is not sent in that duration those remain in the queue and whose acknowledgement is received those are deleted from the subscription.  When service read the same message again, it dumped the message into the dead letter queue of the subscription(reason: MaxDeliveryCountExceeded) as MAX DELIVERY COUNT (maximum number of times a message can be delivered) is set to 1 as we want to read a message once. Find the attached code file(main code file: ServiceBusManager.java) and screenshots below.
Note: LOCK DURATION TIME and MAX DELIVERY COUNT are properties of the subscription which are set on the Azure portal.

## Actual Behavior
1. All the messages are not getting acknowledged in the Lock Duration Time so not getting deleted. 
2. Messages are dumped into dead letter queue of the subscription.

## Expected Behavior
1. Lock a message at a time rather than a batch of messages. 
2. Messages should be acknowledged properly so that they get deleted from the service bus topic and no message should be dumped to the dead letter queue of the subscription.

## Attachments

* Screenshots:

![Messages sent initially](https://user-images.githubusercontent.com/52272451/60244978-3a99e480-98d9-11e9-953a-6c8760817d6f.png)
![Initial message count in subscription](https://user-images.githubusercontent.com/52272451/60244991-41285c00-98d9-11e9-9338-8dbe8fb945cc.png)
![Received All messages ](https://user-images.githubusercontent.com/52272451/60245013-49809700-98d9-11e9-9786-82ede0a08b3f.png)
![Final message count in subscription](https://user-images.githubusercontent.com/52272451/60245029-51d8d200-98d9-11e9-9bc2-33143048fd47.png)
![Reading deadletter queue messages](https://user-images.githubusercontent.com/52272451/60245049-5b623a00-98d9-11e9-9a9d-454727240449.png)
![Azure Service Bus Topic Subscription properties](https://user-images.githubusercontent.com/52272451/60245062-5f8e5780-98d9-11e9-8d4e-c9a84e771b69.png)

* Code:
[ServiceBusManager.zip](https://github.com/Azure/azure-service-bus/files/3333361/ServiceBusManager.zip)

**Comment by axisc** [comment]
@kalungevinayak Thanks for raising this issue.

Given that your lock duration is set to 5 seconds and JMS doesn't have a way to renew the lock, you will end up hitting this same issue even with a higher delivery count.

I'd recommend keeping the message lock duration higher just to give you program additional time to process the message. If you finish and acknowledge the message before the lock expires then the message will be removed from the queue anyways.

Also, message delivery count can be made greater than 1. Each time the application locks the message and gives it up, the delivery count increases. Given that you have set it to 1, Service Bus assumes that it is supposed to try once to delivery it to you, or dead letter it. If you acknowledge the message then it is removed from the queue and not delivered to you again.

Hope this helps.
