### ISSUE TITLE
Payload format recommendations

### ISSUE THREAD

**Issue by nickstaggs** [Azure/azure-service-bus#297]
# Description

In Microsoft's documentation about [Messages, payloads, and serialization](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-messages-payloads) it is recommended to use JSON and Apache Avro as payload formats for structured data. I am curious as to the reasoning behind this recommendation as both use dynamic typing and are generally slower in marshalling/unmarshalling compared to statically typed payload formats such as Thrift or protobuf.

## Actual Behavior
1. Dynamic payload formats JSON and Apache Avro recommended

## Expected Behavior
1. Statically typed payload formats to be recommended

**Comment by SeanFeldman** [comment]
Suggest to open a documentation issue on the referenced page. It will ping individual(s) that created it, as well as facilitate the conversation with the team on the topic.
