### ISSUE TITLE
Deleted entities sometimes stay in internal metadata preventing re-creation

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus#298]
# Description

When an entity is deleted, its (internal) metadata is removed as well.
Sometimes internal metadata stays and causes operations attempting to recreate an entity to fail despite entity being reported as non-existing.

## An example of how it looks like

1. An existing topic called `bundle-1` is deleted
1. List all topics ![image](https://user-images.githubusercontent.com/1309622/62644566-a2474480-b907-11e9-8bcd-95ac60551bc4.png)
1. Try to create the topic again ![image](https://user-images.githubusercontent.com/1309622/62644586-aa9f7f80-b907-11e9-8855-8c91851fcd26.png)

Once this happens, the namespace is stuck with an entity that cannot be re-created and required either deletion and re-creation of the namespace or support involvement. Both are not a good way to handle this and therefore should be considered as a bug that should be addressed.

**Comment by axisc** [comment]
@SeanFeldman thanks for reporting this. We are investigating internally.

**Comment by SeanFeldman** [comment]
Checking in to see if there are some updates or if I amend my list for 🎅

**Comment by EldertGrootenboer** [comment]
If this issue still occurs, please let us know and we can re-open the issue.
