### ISSUE TITLE
QuotaExceededException documentation

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus#3]
# Description

`Microsoft.ServiceBus.Messaging.QuotaExceededException` [is documented](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-messaging-exceptions#quotaexceededexception) with an emphasis on entity filled up with messages. This exception is also thrown when number of connections to a namespace is exceeding the maximum.

```
Microsoft.ServiceBus.Messaging.QuotaExceededException: ConnectionsQuotaExceeded for namespace xxx.
<tracking-id-guid>_G12 ---> 
System.ServiceModel.FaultException`1[System.ServiceModel.ExceptionDetail]: 
ConnectionsQuotaExceeded for namespace xxx.
```

## Expected

Update documentation to reflect this scenario

**Comment by sethmanheim** [comment]
Thanks @SeanFeldman, you found the secret way to submit issues. :-) I'll add this info right away.

**Comment by SeanFeldman** [comment]
![image](https://cloud.githubusercontent.com/assets/1309622/23570955/ef8005d8-0023-11e7-83a5-391bcd3951f8.png)

**Comment by sethmanheim** [comment]
PR is submitted and merged, please close @jtaubensee. Should appear in the next publishing run, probably Monday.

**Comment by jtaubensee** [comment]
Thanks @sethmanheim. Added you as a contributor, so you can close in the future.
