### ISSUE TITLE
Could not load file or assembly Microsoft.Azure.ServiceBus

### ISSUE THREAD

**Issue by mikebridge** [Azure/azure-service-bus#30]
Sorry, this is probably a generic issue which is not specific to azure-service-bus, but I'm not sure why I'm getting this error.

When I compile azure-service-bus from the git source, then copy the resulting DLLs to my project and add a reference to them via "Browse", I get the following error at runtime (it compiles fine):

```
System.IO.FileNotFoundException occurred
  HResult=0x80070002
  Message=Could not load file or assembly 'Microsoft.Azure.ServiceBus, Version=0.0.6.0, Culture=neutral, PublicKeyToken=7e34167dcc6d6d8c'. The system cannot find the file specified.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at MyApp.DomainEvents.Tester.<Exec>d__4.MoveNext() in C:\Visual Studio 2017\Projects\MyApp\src\Profiles\DomainEvents\Tester.cs:line 43
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at ProfileManager.DomainEvents.Tester.Exec()
   at Api.Controllers.CurrentProfileController.<Get>d__3.MoveNext() in 
C:\Visual Studio 2017\Projects\MyApp\src\Api\Controllers\CurrentProfileController.cs:line 39
```

However, when I include the whole project in my solution, add the azure-service-bus project as a "Project" reference, and compile the whole thing together it works fine.

More description [here](https://stackoverflow.com/questions/44337484/could-not-load-file-or-assembly-microsoft-azure-servicebus-with-prerelease-in-do).

**Comment by mikebridge** [comment]
Sorry, meant to post this in the azure-service-bus-dotnet repo. :(

**Comment by SeanFeldman** [comment]
😃 they are very similar, but different.
Perhaps better to close this one and raise against the appropriate repo (if still relevant).

**Comment by SeanFeldman** [comment]
Should this be closed?

**Comment by mikebridge** [comment]
Yes, sorry, my mistake. :(
