### ISSUE TITLE
azure.servicebus.common.errors.ServiceBusError: Handler failed: CBS Token authentication failed.

### ISSUE THREAD

**Issue by wec2018** [Azure/azure-service-bus#304]
# Description

The customer refer to : https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-python-how-to-use-queues
They want to send and receive the service bus message. 

But it occurred errors : 
**dle_exception
    raise error
azure.servicebus.common.errors.ServiceBusError: Handler failed: CBS Token authentication failed.
Status code: 404
Description: The messaging entity 'sb://ruchandemo.servicebus.windows.net/queen0' could not be found. TrackingId:a96beffe-7d14-4ba4-
93de-aa6170377c1f_G10, SystemTracker:ruchandemo.servicebus.windows.net:queen0, Timestamp:2019-08-18T03:59:01**

**Below is their code :** 
from azure.servicebus import ServiceBusClient
from azure.servicebus import QueueClient, Message

sb_client = ServiceBusClient.from_connection_string('Endpoint=sb://ruchandemo.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=htE23623UKdvlNitYdOeeqsFwj0dGclWuz4mSBEDez8=')

// Create the QueueClient
queue_client = QueueClient.from_connection_string(
    'Endpoint=sb://ruchandemo.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=htE23623UKdvlNitYdOeeqsFwj0dGclWuz4mSBEDez8=', 'queen0')

// Send a test message to the queue
msg = Message(b'Test Message')
queue_client.send(msg)

// Receive the message from the queue
with queue_client.get_receiver() as queue_receiver:
    messages = queue_receiver.fetch_next(timeout=3)
    for message in messages:
        print(message)
        message.complete()

// Expected Behavior
Send and receive message sucessfully.

**Ask PG** 
Could you please advise what the errors mean ? Need to regenearte the SAS token ? 

Thank you!!

**Comment by kajahno** [comment]
I've hit this very same issue. The fix was to update the system clock.

**Comment by EldertGrootenboer** [comment]
If this issue still occurs, please let us know and we can re-open the issue.
