### ISSUE TITLE
SqlFilter: IN Logic not working

### ISSUE THREAD

**Issue by bertenbobje** [Azure/azure-service-bus#308]
# Description

I have a piece of code that adds an **IEnumerable** to the **UserProperties** of a **Message** by turning it into a comma-delimited string, adding single quotes around every element if it is a **IEnumerable\<string\>**.

I add a UserProperty called **Apps** to my message with the following string (notice the single quotes around every element):
`'75ee6538','b5fb3f71','b830a32c','a93f995d','aee69844','sdf32xd4','01925154'`

I have added a **SqlFilter** to a subscription, checking if a provided string appears in the comma-delimited string, which is shown below:

`'01925154' IN (user.Apps)`

**The messages where this should evaluate to true, never get received by this subscription.**

I have tried a hacky SqlFilter of doing it like so:

`'''75ee6538'',''b5fb3f71'',''b830a32c'',''a93f995d'',''aee69844'',''sdf32xd4'',''01925154'' LIKE '%''01925154''%'`

and then it works perfectly, meaning the User Property comes through OK.

## Actual Behavior
1. Message does not get handled by the subscription.

## Expected Behavior
1. Message gets handled by the subscription.

**Comment by SeanFeldman** [comment]
According to the [documentation](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-messaging-sql-filter), a filter can check if a single expression is found in a collection. I.e. `user.App IN ('val1', 'val2', 'val3'...)` where `user.App` is a single value.

**Comment by truyb** [comment]
So it's not possible to do it the other way around (where the user property is a collection)?

Right now, I create a filter based on the UID of the App (**01925154**) while adding a subscription and check it against the collection of UIDs that get provided in the message user properties.

**Comment by SeanFeldman** [comment]
If I understand the document correctly, it's not possible.

`<expression> [NOT] IN ( <expression> [, ...n] )  ` where
```
<expression> ::=  
      <constant>   
      | <function>  
      | <property>  
      | <expression> { + | - | * | / | % } <expression>  
      | { + | - } <expression>  
      | ( <expression> )  

<property> :=   
       [<scope> .] <property_name>
```

reads to me that you can have a property (header) evaluated against one or more values.

@axisc could maybe confirm, but I'm pretty sure that `user.App IN ('val1', 'val2', 'val3'...)` where `user.App` is a single value header would work, but not the other way around. Attempt to evaluate `user.App IN ('val1')` where `user.App` is a collection would not fly.
