### ISSUE TITLE
System.OperationCanceledException documentation

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus#31]
`System.OperationCanceledException` is documented as an exception under ["User coding error" category](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-messaging-exceptions).

Here's [an example](https://stackoverflow.com/questions/44385210/operationcanceledexception-when-sending-to-service-bus/44394224) of this exception raised when it's a server internal error. 

```
Exception System.OperationCanceledException: The operation cannot be performed because the entity has been closed or aborted. --->
 System.ServiceModel.CommunicationObjectAbortedException: Internal Server Error: 
The server did not provide a meaningful reply; this might be caused by a premature session shutdown.
```

The "The server did not provide a meaningful reply" part makes me wonder how is this user coding error? Clarification will be greatly appreciated.

**Comment by SeanFeldman** [comment]
cc @sethmanheim

**Comment by hmlam** [comment]
may I ask if there is a specific steps you use to generate this error? OperationCanceledException usually is from a connection drop or client got aborted and I just want to make sure which case we are talking about here.

**Comment by SeanFeldman** [comment]
@hmlam unfortunately I don't have access to this code. The customer on SO can provide more details.

**Comment by sethmanheim** [comment]
@SeanFeldman This isn't really a documentation issue, is it? If it is, please clarify, otherwise we should close this issue. I'm asking because I'm collating all your documentation issues and we will be taking action on them.
