### ISSUE TITLE
Deferred messages in the Dead-letter end of the Service Bus Queue are obtained on peeking the dead-letter queue even if the message is locked by a receiver

### ISSUE THREAD

**Issue by Ranjith-Eswaran** [Azure/azure-service-bus#310]
# Description
Deferred messages in the Dead-letter end of the Service Bus Queue are obtained on peeking the dead-letter queue even if the message is locked by the receiver when using **Microsoft.ServiceBus.Messaging** Library version 5.0.0

## Actual Behavior
Deferred Messages locked by a receiver are peeked by the receiver in the dead-letter end of the queue

## Expected Behavior
Locked messages should not be peeked if it is locked by receiver for processing

**Comment by SeanFeldman** [comment]
Somewhat related to https://github.com/Azure/azure-service-bus/issues/95

**Comment by EldertGrootenboer** [comment]
If this issue still occurs using the latest SDK, please let us know and we can re-open the issue.
