### ISSUE TITLE
Azure Service Bus - Unregister Message Handler for MessageReceiver.OnMessageAsync or Gracefully Close Message Receiver

### ISSUE THREAD

**Issue by JishanK** [Azure/azure-service-bus#311]
# Description
We are having a windows service which receives messages from Azure Service bus queue and process those messages with business logic and finally completes them.

To receive messages from service bus we are using MessageReceiver which we are creating with below code snippet.

                string sasToken = SASServiceHelper.SASTokenGenerationAsync(QueueName).Result;
                var tokenProviderQueue = TokenProvider.CreateSharedAccessSignatureTokenProvider(sasToken);
                MessagingFactorySettings settings = new MessagingFactorySettings
                {
                    TokenProvider = tokenProviderQueue,
                    OperationTimeout = TimeSpan.FromMinutes(12)
                };                

                messageFactoryQueue = MessagingFactory.Create(connectionString, settings);                
                messageReceiver = await messageFactoryQueue.CreateMessageReceiverAsync(qName, ReceiveMode.PeekLock);

Here SAS token expires in 60 minutes. And we have registered message handler with, 

               var options = new OnMessageOptions
                {
                    MaxConcurrentCalls = Convert.ToInt16(MessageMaxConcurrentCalls),
                    AutoComplete = false                    
                };
                options.ExceptionReceived += OptionsOnExceptionReceived;
                messageReceiver.OnMessageAsync(MessageHandler, options);

Also I am having a timer which generates new SAS token every 55 minutes and create a messageReceiver again and register same message handler. But issue here is, the older messageReceiver still continues to run message handler and after 60 minutes it gives below exception.

**Error - 40105: Malformed authorization token.**

So to overcome this issue, I had tried closing messaging factory which creating new message receiver. But it still gives me **Error - The operation cannot be performed because the entity has been closed or aborted**. This might be because messages might be in process and I am closing the messaging factory.

So I require help here to overcome this issue on how I can update the messaging factory/message receiver with latest  SAS token and continue OnMessageAsync or how I can unregister message handler and register with new message receiver without causing any exception.

Service bus nuget package I am using is WindowsAzure.ServiceBus 4.1.8.

**Comment by SeanFeldman** [comment]
This repository is for server-side issues. The issue is for the legacy (old) client. @axisc @binzywu would you recommend keeping it in this repo or any other suggestions.

**Comment by JishanK** [comment]
If it has to move to another repo, can you please let me know to which repo I should move it?

**Comment by EldertGrootenboer** [comment]
If this issue still occurs using the latest SDK, please let us know and we can re-open the issue.
