### ISSUE TITLE
Ways to check the Service bus health status to trigger failover

### ISSUE THREAD

**Issue by shettyh** [Azure/azure-service-bus#315]
# Description

I am trying to check if there are any ways to detect service bus failure. This is needed for us to automate the Service bus failover or at-least raise an alert if the service bus status in unhealthy.

One hack is to create a dummy queue and try to send/receive messages. Is there any documented ways to check the health of service bus ?

**Comment by EldertGrootenboer** [comment]
We recommend using Azure Monitor to check the health of Service Bus, more information can be found at https://docs.microsoft.com/en-us/azure/service-bus-messaging/monitor-service-bus.
