### ISSUE TITLE
having slash in Topic or Queue name

### ISSUE THREAD

**Issue by WahidBitar** [Azure/azure-service-bus#32]
# Description
I can't create topics or queue that contain slash in their name from the portal. Although the portal allow me to add the / to the name in the create form, when I click create button it goes away without any error or success message

## Actual Behavior
1. The portal allows me to add the / to the name in the create form when I click create button it goes away without any error or success message 
2. in the notification it just show message saying "Service Bus queue creation"
3. When using Masstransit library in the code it creates those topics and queue automatically containing slash in the names. But in that case, I couldn't control them from the portal

## Expected Behavior
1. To allow slash when adding topics or queue either programming or from the portal
2. To allow control over the created topics or queues which created by Masstransit that have slash in their names

**Comment by SeanFeldman** [comment]
It's a bug. As a workaround, you could use [SBExplorer](https://github.com/paolosalvatori/ServiceBusExplorer/releases) or [SB360](https://www.servicebus360.com/) to get those entities created.

**Comment by WahidBitar** [comment]
Thank you,
do those tools give me a full control over the topics and queues?

**Comment by SeanFeldman** [comment]
They do. Check then out and your questions shall be answered. 😉
