### ISSUE TITLE
Receive all the messages from a specific subscription from a topic in a single call

### ISSUE THREAD

**Issue by SibeeshVenu** [Azure/azure-service-bus#320]
# Description
How can I receive all the messages from a specific subscription from a topic? I see that there is a method available for the queues. How can I do that same for my subscription?

` _messageReceiver = new MessageReceiver(parameters);` 
`var lstMessage = await _messageReceiver.ReceiveAsync(100000);`
## Actual Behavior
No method to read all the messages from the subscription

## Expected Behavior
There should be a method. I am looking for a [method like this](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.servicebus.core.messagereceiver.receiveasync?view=azure-dotnet#Microsoft_Azure_ServiceBus_Core_MessageReceiver_ReceiveAsync_System_Int32_) where it returns `Task<IList<Message>>`

**Comment by SeanFeldman** [comment]
You provide an entity name. Don't know what you pass in your parameters.

**Comment by SibeeshVenu** [comment]
> You provide an entity name. Don't know what you pass in your parameters.

My question is, is there any function that I can use already to receive all the messages from a subscription of a topic?

**Comment by SeanFeldman** [comment]
`MessageReceiver` is designed to work with queues and subscriptions. Please see [the documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.servicebus.core.messagereceiver.-ctor).
There's also a samples repository I suggest to review: https://github.com/Azure/azure-service-bus/blob/master/samples/readme.md

**Comment by SibeeshVenu** [comment]
Thanks. Yes I know that. But my query is, are there any workarounds or additional method that will give me all the messages from a subscription in a topic?

**Comment by SeanFeldman** [comment]
There's no method that will give you all messages. The broker will send a batch (when using message receiver's `ReceiveAsync(int)` method), but that batch is never guaranteed to be the same size as the number of the messages found under subscription.

**Comment by SibeeshVenu** [comment]
But again this ReceiveAsync(int) method is supported for queues right? Can I use it for the Subscription in a topic ?

**Comment by paolosalvatori** [comment]
Yes, https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.subscriptionclient.receiveasync?view=azure-dotnet. I'm closing this issue, as this is not a specific issue of the tool, but rather a question on the client API.

**Comment by SibeeshVenu** [comment]
@paolosalvatori I think you misunderstood my question, sorry for not explaining it well. I had updated my initial query. Please have a look. Thanks

**Comment by SibeeshVenu** [comment]
@SeanFeldman Thanks. I have changed the question as you mentioned. Sure, I will write the logic to drain my subscription, are there anyways to find whether there are no more messages to be read in the subscription? I am following this [doc](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-dotnet-how-to-use-topics-subscriptions#receive-messages-from-the-subscription).

**Comment by SeanFeldman** [comment]
> are there anyways to find whether there are no more messages to be read in the subscription?
Yes. While the broker is returning messages, there's more. When there's none, the broker will return a null. Also, you can active message count on the queue to find out if there's anything left.

General comment - I think you should close this issue. It's not a bug or a feature that will be implemented.

**Comment by SibeeshVenu** [comment]
> @SeanFeldman Thanks. I have changed the question as you mentioned. Sure, I will write the logic to drain my subscription, are there anyways to find whether there are no more messages to be read in the subscription? I am following this [doc](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-dotnet-how-to-use-topics-subscriptions#receive-messages-from-the-subscription).

Sure I can close this issue, I asked this question I am not aware of any settings to see whether all the messages are read or not in the message read handler. If you know it, please share it. Thanks

**Comment by SeanFeldman** [comment]
There's no setting. The API allows you to either continuously receive messages or check what's the message count and decide if you want to pump those or not. An alternative approach is to use EventGrid to subscribe to [`Microsoft.ServiceBus.ActiveMessagesAvailableWithNoListeners`](https://docs.microsoft.com/en-ca/azure/event-grid/event-schema-service-bus) published whenever messages are available and no clients consuming those. This is only available with Premium (https://github.com/Azure/azure-service-bus/issues/321).

**Comment by SibeeshVenu** [comment]
Thanks a lot for sharing all the information.
