### ISSUE TITLE
Support receiving EventGrid events on the Standard Tier

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus#321]
# Description

Support receiving EventGrid events on the Standard Tier, just like it works with the Standard tier.

And when that happens, update the [documentation](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-to-event-grid-integration-concept) to let the world know.

**Comment by SeanFeldman** [comment]
Public wishlist issue https://github.com/SeanFeldman/azure-events-wishlist/issues/1

**Comment by EldertGrootenboer** [comment]
We don't have any immediate plans to implement this, but you can upvote this on [Azure Feedback](https://feedback.azure.com/d365community/idea/d6c85ae0-2125-ec11-b6e6-000d3a4f0f84), and we might revisit this in the future if there is enough traction for it. Please make sure to include the scenario where you would like to use this for, as it helps us give prioritization to the various items.
