### ISSUE TITLE
ServiceBusTrigger does not trigger function when User assigned managed identity is used

### ISSUE THREAD

**Issue by SiarheiAbr** [Azure/azure-service-bus#322]
I have the following scenario:
1. there is function triggered by ServiceBusTrigger:
```
 [FunctionName("MyAwesomeFunction")]
        public static async Task RunAsync([ServiceBusTrigger("my-queue", Connection = "MyConn")] string myQueueItem)
        {
          // .. some code
        }
```
2. '**MyConn**' connection string looks like this: '_Endpoint=sb://my-endpoint.servicebus.windows.net/;Authentication=ManagedIdentity_'
3. I added a new managed identity in azure portal and in function -> Platform features -> Identity -> User assigned I have added this user identity
4. in Service Bus -> 'my-queue' -> Access control (IAM) I have assigned an 'Azure Service Bus Data Receiver' role for the user identity
5. restart the function
6. send a message to 'my-queue'

Expected result: function is triggered and processed
Actual result: function is not triggered, I tested this in Service Bus Explorer and see that messages remain in Active state and don't trigger the function.

I use:
Microsoft.Azure.ServiceBus 4.0.0
Microsoft.Azure.WebJobs.Extensions.ServiceBus 3.0.0
Microsof.NET.Sdk.Functions (1.0.22)

**Comment by edvowles** [comment]
I've got this working where the connection string has a space between "Managed" and "Identity", i.e. 'Endpoint=sb://my-endpoint.servicebus.windows.net/;Authentication=Managed Identity'

**Comment by SeanFeldman** [comment]
@edvowles this would be great addition to the documentation https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-managed-service-identity. Currently there's no mentioning of. Want to raise an issue against that article as well.

**Comment by luisaf8a** [comment]
I have similar issue but my function works the first time, after the 20 min timeout the trigger seems to have stopoed working or unsynchronized, so the new messages stay in my topic. I also have an Azure SQL binding when the message is received to store the message in a table.

I added synchronisation command in my deployment script as recommended in other issues I have checked and this does not help either.

I am using consumption plan. Could this be related to the plan I am using or is the functionality broken for topics?

**Comment by SeanFeldman** [comment]
> I have similar issue but my function works the first time, after the 20 min timeout the trigger seems to have stopoed working

@luisaf8a then it's not a similar issue. This one is about SB trigger not triggering at all 🙂 Have you raised an issue with Azure Functions about it?

**Comment by luisaf8a** [comment]
> > I have similar issue but my function works the first time, after the 20 min timeout the trigger seems to have stopoed working
> 
> @luisaf8a then it's not a similar issue. This one is about SB trigger not triggering at all 🙂 Have you raised an issue with Azure Functions about it?

Yes, I created a support request. Thank you :)

**Comment by 4nandP** [comment]
> @edvowles this would be great addition to the documentation https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-managed-service-identity. Currently there's no mentioning of. Want to raise an issue against that article as well.

I have raised https://github.com/MicrosoftDocs/azure-docs/issues/64363 as I too suffered from lack of docs.

**Comment by ilya-git** [comment]
It seems it is possible to use managed identity with this connection string `Endpoint=sb://sb-uniteaq-dev.servicebus.windows.net/;Authentication=ManagedIdentity`, but I have not found any documentation on this which is really strange, as this would simplify access management and can be widely used.
