### ISSUE TITLE
Throttle concurrent (session) message processing

### ISSUE THREAD

**Issue by worldspawn** [Azure/azure-service-bus#323]
I have a large volume of session'd messages arriving being consumed by a service that can't handle the volume it's getting. Each message results in a sql write and I am seeing other operations failing that the sql server session limit has been hit.

Using the Microsoft.Azure.ServiceBus library (the new one) I have an option to set the maximum concurrent sessions but I want to throttle the number of concurrent message receive operations i am running like I can with non session message handlers.

Is this possible?

**Comment by SeanFeldman** [comment]
Are you using message session handler API?

**Comment by Mortana89** [comment]
Very curious here as well! We're currently taking a look at a circuit-breaker pattern that will disable receiving messages from a queue upon certain metrics (throttled counts in our case).

**Comment by praba984** [comment]
Any solution? I am facing an issue with 5000 session'd messages at the consumer end.

**Comment by gethari** [comment]
> Any solution? I am facing an issue with 5000 session'd messages at the consumer end.

Did you find any solution for this ? Looks like this is a way old thread

**Comment by worldspawn** [comment]
If you have a single consumer you can manage this with Polly (and ur dotnet). A bulkhead policy can constrain the number of concurrent executions. Wrap it in a retry policy so you can retry in the event of a BulkheadRejectedException. Alternatively you can "handle" the rejection by returning the message to the queue perhaps with a bit of a delay. Or some combination.

```
var bulkheadPolicy = Policy.BulkheadAsync<TResponse>(request.MaxConcurrency);
            var waitPolicy = Policy.Handle<BulkheadRejectedException>()
                .WaitAndRetryAsync(100, (retryCount) => TimeSpan.FromSeconds(retryCount * .1));

            return waitPolicy.WrapAsync(bulkheadPolicy);
```

For multiple consumers its not so easy. You would need a distributed semaphore.

**Comment by EldertGrootenboer** [comment]
If this issue still occurs using the latest SDK, please let us know and we can re-open the issue.
