### ISSUE TITLE
Queue name length documented incorrectly

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus#324]
Service Bus Namespace Access [document](https://docs.microsoft.com/en-us/rest/api/servicebus/addressing-and-protocol) is specifying queue name length as 290 when it's 260. Should be fixed.

This connects to https://github.com/Azure/azure-service-bus/issues/257. It would be really nice to have more sanity about these name length quotas.

**Comment by SeanFeldman** [comment]
cc @axisc

**Comment by EldertGrootenboer** [comment]
This has been fixed to indicated the correct length.
