### ISSUE TITLE
run java It is not possible for an entity that requires sessions to create a non-sessionful message receiver

### ISSUE THREAD

**Issue by dahaibao** [Azure/azure-service-bus#326]
# Description

## Actual Behavior
1. 
2. 

## Expected Behavior
1. 
2.

**Comment by dahaibao** [comment]
When I run test cases for TopicsGettingStarted or others , there always issue accure "java.lang.UnsupportedOperationException: It is not possible for an entity that requires sessions to create a non-sessionful message receiver. TrackingId:74094b98-dd04-4662-961d-ac2890b6f58c_B5, SystemTracker:alliancetest:topic:alliancetopic~15|alliancesubscription, Timestamp:2019-11-05T10:13:54 TrackingId:f560b40766db4c78a91d56a319504d80_G13, SystemTracker:gateway7, Timestamp:2019-11-05T10:13:54Disconnected from the target VM, address: '127.0.0.1:60213', transport: 'socket'
"

**Comment by SeanFeldman** [comment]
That's by design. Either create your entity w/o sessions support or use it with a receiver that has sessions support enabled.

**Comment by dahaibao** [comment]
Thanks for you reply, but how to make a receiver with session support. Is there a sample?

**Comment by dahaibao** [comment]
> That's by design. Either create your entity w/o sessions support or use it with a receiver that has sessions support enabled.

Thanks for you reply, but how to make a receiver with session support. Is there a sample?

**Comment by SeanFeldman** [comment]
Don't know about the Java API, but with .NET you need to start accepting sessions. Here's the article: https://docs.microsoft.com/en-us/azure/service-bus-messaging/message-sessions

**Comment by dahaibao** [comment]
> Don't know about the Java API, but with .NET you need to start accepting sessions. Here's the article: https://docs.microsoft.com/en-us/azure/service-bus-messaging/message-sessions

Thank you buddy, that's very useful, I will figure it out.

**Comment by dreamuth** [comment]
In Java, the session support works with azure-servicebus library example
[QueuesGettingStarted.java](https://github.com/Azure/azure-service-bus/blob/master/samples/Java/azure-servicebus/QueuesGettingStarted/src/main/java/com/microsoft/azure/servicebus/samples/queuesgettingstarted/QueuesGettingStarted.java) by changing `queueClient.registerMessageHandler` to `queueClient.registerSessionHandler` and relevant changes.

But it doesn't work with JMS example [JmsQueueQuickstart.java](https://github.com/Azure/azure-service-bus/blob/master/samples/Java/qpid-jms-client/JmsQueueQuickstart/src/main/java/com/microsoft/azure/servicebus/samples/jmsqueuequickstart/JmsQueueQuickstart.java), Does anyone make it work?

**Comment by axisc** [comment]
@dreamuth - JMS doesn't have the concept of sessions. Please disable sessions on the queue and try again.

The original question has been correctly answered by @SeanFeldman

**Comment by gennadiy-dubina** [comment]
hi @axisc 
JMS has grouped messages, it looks like similar to sessioned queue.
Is it possible to configure qpid client to use sessioned queue ?
