### ISSUE TITLE
Not able to receive multiple messages on standard Service Bus topic using Java SDK(v2.0.0)

### ISSUE THREAD

**Issue by welcomemandeep** [Azure/azure-service-bus#328]
#Background 
A real-life application is a long-running process that encompasses queueClient to be re-used for multiple messages.  Such kind of application takes implements load leveling and competing-consumers patterns.  So essentially my application has 2 Azure service bus clients (one for send and one for receive). I am using  "queues" in the Azure Service Bus. The receiver client runs is a separate thread pool.  My MessageHandlerOptions options are  `new MessageHandlerOptions(1, false, Duration.ofMinutes(5))`.  I am completing the message after processing some business logic.

#Problem 
The receiver client is unable to fetch further messages event when I mark the message as complete ` receiveClient.complete(messageLockId)` or/and mark the future which I returned from the `IMessageHandler` that I registered `queueClient.registerMessageHandler(new IMessageHandler() {...}` to the receiver client. 

#Environment Details

* Java  SDK - v 2.0.0
* Azure service bus -  Standard (non premium)
* Queue config - 
 *** Partition - No
 *** Queue Size - 1GB
 *** Message Lock duration - 5 mins 
 *** Duplicate Detection - 10 Mins
 *** Rest of settings - default

#How to reproduce 
Here is a sample to reproduce the problem. 
https://gist.github.com/welcomemandeep/203ea6efb24cd2158f473b76e04a2011

#Workaround
When I return `null` from `IMessageHandler` and forget about futures ( and just do `receiveClient.complete(messageLockId)` after my business logic), things start to work except for the fact that the "active message count" in the queue does not decrease even after complete being called.

So the only way to work around the problem was to use futures and `close()` and re-create the queue client for receiving messages. 

Also, an (related / unrelated) error that I am getting with or without using futures - 

`
{
  "timestamp" : "2019-11-22 11:03:33.350",
  "level" : "ERROR",
  "thread" : "pool-3-thread-1",
  "logger" : "com.microsoft.azure.servicebus.MessageAndSessionPump",
  "message" : "onMessage with message containing sequence number '53' threw exception",
  "context" : "default",
  "exception" : "java.lang.NullPointerException: null\n\tat java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)\n\tat java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)\n\tat java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n"
}
`

**Comment by yvgopal** [comment]
There is a bug in your code. Change line number 63 from completableFuture.complete(true) to completableFuture.complete(null). Then it will work. That is a completableFuture of type Void, and it must be completed only with a null value. It took some time for me to figure out what is going on. The compiler is warning you as it should. But java runtime doesn't see that the future is completed.

This behavior of the java runtime is not very consistent. whenComplete is invoked on the same completablefuture, but not other methods. Anyway I cannot speak for java runtime. You change that line, better fix those generic type warnings, and your code should work.

**Comment by welcomemandeep** [comment]
@yvgopal, thanks. That worked like a charm.  Do you also have any guesses for the unrelated error as well?

**Comment by welcomemandeep** [comment]
To add more context to it - 

I have registered this the IMessageHandler - 
`
// callback invoked when the message handler has an exception to report
public void notifyException(Throwable throwable, ExceptionPhase exceptionPhase) {
  LOG.error("{} - {}", exceptionPhase, throwable.getMessage());
}
`
So sometimes I get this stack  - 

`
  "exception" : "java.lang.NullPointerException: null\n\tat java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)\n\tat java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)\n\tat java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n"
`


and the "notifyException" 
 `"USERCALLBACK - null"`


I am suspecting it has to do with this future code only.

**Comment by yvgopal** [comment]
@welcomemandeep All I can say is that your onMessage method is throwing a nullpointer exception. I didn't look very carefully what might be causing it. May be you can try putting try/catch around your method and see what is being caught.
