### ISSUE TITLE
Scheduling a message using the method ScheduledEnqueueTimeUtc - how far ahead in time?

### ISSUE THREAD

**Issue by sdg002** [Azure/azure-service-bus#332]
# Description
If I am posting a message and setting the property **ScheduledEnqueueTimeUtc** with a date in the future, then is there any known limitation on far ahead in time can the value of **ScheduledEnqueueTimeUtc** be?  Example: 30 days, 6 months, 1 year, etc.

**Comment by SeanFeldman** [comment]
`ScheduledEnqueueTimeUtc` is a `DateTime`. Personally, I would not advise going too crazy in the future as then it's a data storage and not a messaging solution. Aside from that, the broker doesn't impose any restrictions.

**Comment by sdg002** [comment]
Thanks for looking into this.  It would be imperative to have some practical limits from Microsoft. 
**Example scenario**- 

- We are building a health care system where we would want to schedule an business logic execution 6 months in the future. 
- This event will be on a per customer basis.
- Wake up and do some calculations based on data collected in the 6 months
- Send out a notification to the customer

Service bus fits in very well. However, it would be good to know if Microsoft has a different opinion.

**Comment by SeanFeldman** [comment]
Your comment makes sense. Documentation is usually where I'm looking. This property/feature has never provided any [guidelines](https://docs.microsoft.com/en-us/azure/service-bus-messaging/) neither with the [old package](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.brokeredmessage.scheduledenqueuetimeutc?view=azure-dotnet) nor with the [new one](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.servicebus.message.scheduledenqueuetimeutc?view=azure-dotnet#Microsoft_Azure_ServiceBus_Message_ScheduledEnqueueTimeUtc). That is why I'm usually following the rule of thumb of 1 year to ensure it doesn't turn into a database.

@axisc are there any recommendations on the practical limits of the values set to this property?

**Comment by sdg002** [comment]
any luck?

**Comment by sdg002** [comment]
Interestingly, AWS SQS (AWS Simple Queue Service) has a similar feature and as per their docs, the maximum possible delay is 15 minutes.
https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-delay-queues.html
![image](https://user-images.githubusercontent.com/20245330/75635037-c30c1a00-5c0a-11ea-8726-17f7eade0837.png)

**Comment by SeanFeldman** [comment]
Service Bus should not be compared to AWS SQS, rather [Storage queues.](https://docs.microsoft.com/en-us/azure/storage/queues/storage-queues-introduction)

**Comment by rasmuschristensen** [comment]
Any updates on this one?

**Comment by EldertGrootenboer** [comment]
Although we don't impose hard limits on scheduled messages, as Sean mentioned, Service Bus should not be used as a database. So the proposed scenario can be implemented like this, but it depends per scenario to decide what the best option is.
