### ISSUE TITLE
Does ASB support setting the distribution-mode on a receiver link?

### ISSUE THREAD

**Issue by nwalsh1025** [Azure/azure-service-bus#333]
# Description
Does ASB support setting the distribution-mode on a receiver link as described in the protocol?
http://www.amqp.org/sites/amqp.org/files/amqp.pdf - page 88
I need to support dynamic topic-subscriptions and setting up a read-only queue by setting the distribution-mode to copy would be one way to achieve this.

**Comment by axisc** [comment]
@nwalsh1025, thanks for raising this issue.

Please consider using the Service Bus SDK that abstracts the AMQP protocol frames and makes your application model easier.

A read-only queue can be setup by managing the applications permissions either using SAS keys or AAD's "Service Bus Receiver" role scoped to that specific queue and assigned to your applications identity. Please check this [link](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-authentication-and-authorization) for more details.

Hope this helps.
