### ISSUE TITLE
40100: Unauthorized when using AzureActiveDirectoryTokenProvider with ManagementClient

### ISSUE THREAD

**Issue by phmcder** [Azure/azure-service-bus#334]
# Description
I am trying to authenticate connections to a Service Bus using an AzureActiveDirectoryTokenProvider. I am able to successfully connect using QueueClient, TopicClient and SubscriptionClient. When I try to test using ManagementClient configured in a similar way to the other client I get the exception below
`Microsoft.Azure.ServiceBus.UnauthorizedException : SubCode=40100: Unauthorized`
I have enabled every role I can think of for the client at service bus, resource group and subscription but none of them worked.

Any ideas?

**Comment by EldertGrootenboer** [comment]
If this issue still occurs using the latest SDK, please let us know and we can re-open the issue.
