### ISSUE TITLE
RoleBasedAccessControl sample does not compile

### ISSUE THREAD

**Issue by eeskildsen** [Azure/azure-service-bus#338]
# Description

The role-based access control sample doesn't compile.

1. `git clone https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.ServiceBus.Messaging/RoleBasedAccessControl`
1. `cd azure-service-bus\samples\DotNet\Microsoft.ServiceBus.Messaging\RoleBasedAccessControl`
1. `msbuild`

## Actual Behavior

Build fails.

Output:

    Build FAILED.

    "<SomePath>\azure-service-bus\samples\DotNet\Microsoft.ServiceBus.Messaging\RoleBasedAccessControl\RoleBasedAccessControl.sln" (default target) (1) ->
    "<SomePath>\azure-service-bus\samples\DotNet\Microsoft.ServiceBus.Messaging\RoleBasedAccessControl\RoleBasedAccessControl.csproj" (default target) (2) ->
    (CoreCompile target) ->
    Program.cs(29,21): error CS0234: The type or namespace name 'Identity' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [<SomePath>\azure-service-bus\samples\DotNet\Microsoft.ServiceBus.Messaging\RoleBasedAccessControl\RoleBasedAccessControl.csproj]
    Program.cs(31,27): error CS0234: The type or namespace name 'ServiceBus' does not exist in the namespace 'Microsoft.Azure' (are you missing an assembly reference?) [<SomePath>\azure-service-bus\samples\DotNet\Microsoft.ServiceBus.Messaging\RoleBasedAccessControl\RoleBasedAccessControl.csproj]
    Program.cs(32,27): error CS0234: The type or namespace name 'ServiceBus' does not exist in the namespace 'Microsoft.Azure' (are you missing an assembly reference?) [<SomePath>\azure-service-bus\samples\DotNet\Microsoft.ServiceBus.Messaging\RoleBasedAccessControl\RoleBasedAccessControl.csproj]
    Program.cs(33,27): error CS0234: The type or namespace name 'ServiceBus' does not exist in the namespace 'Microsoft.Azure' (are you missing an assembly reference?) [<SomePath>\azure-service-bus\samples\DotNet\Microsoft.ServiceBus.Messaging\RoleBasedAccessControl\RoleBasedAccessControl.csproj]
    Program.cs(85,37): error CS0246: The type or namespace name 'QueueClient' could not be found (are you missing a using directive or an assembly reference?) [<SomePath>\azure-service-bus\samples\DotNet\Microsoft.ServiceBus.Messaging\RoleBasedAccessControl\RoleBasedAccessControl.csproj]
    Program.cs(38,9): error CS0246: The type or namespace name 'QueueClient' could not be found (are you missing a using directive or an assembly reference?) [<SomePath>\azure-service-bus\samples\DotNet\Microsoft.ServiceBus.Messaging\RoleBasedAccessControl\RoleBasedAccessControl.csproj]
    Program.cs(39,9): error CS0246: The type or namespace name 'QueueClient' could not be found (are you missing a using directive or an assembly reference?) [<SomePath>\azure-service-bus\samples\DotNet\Microsoft.ServiceBus.Messaging\RoleBasedAccessControl\RoleBasedAccessControl.csproj]

## Expected Behavior

Build succeeds.

**Comment by pihalve** [comment]
I experience the same issue. Would be nice if it was fixed.
