### ISSUE TITLE
The suggested Java Debugger Extension for VS Code is flagged as deprecated

### ISSUE THREAD

**Issue by SandraAhlgrimm** [Azure/azure-service-bus#339]
"Exploring and running the samples
The samples are preconfigured for use with Visual Studio Code and the Red Hat Java language support and Java debugging extensions. " is pointing to https://marketplace.visualstudio.com/items?itemName=donjayamanne.javadebugger which is no longer maintained and therefore, marked as deprecated in VS Code.
Lets advice to use another extension for debugging.

**Comment by SeanFeldman** [comment]
@saadsami this repository is not quite what you're looking for. It's about broker issues (see  [README.md](https://github.com/Azure/azure-service-bus/blob/master/README.md)). Perhaps a better starting point would be the [Java SDKs repo](https://github.com/Azure/azure-sdk-for-java)?
