### ISSUE TITLE
Documentation is currently targeting WindowsAzure.ServiceBus, but not Microsoft.Azure.ServiceBus

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus#34]
As the new client Microsoft.Azure.ServiceBus is progressing, something has to be done with the documentation to address the issue with 2 similar clients, yet different in some APIs and details.

**Comment by SeanFeldman** [comment]
@sethmanheim perhaps PG can share what are the thoughts to tackle this?

**Comment by sethmanheim** [comment]
Some of the documentation has been updated for the new client, and others are in process. We have internal bugs tracking this and will update as soon as possible.

**Comment by SeanFeldman** [comment]
>  will update as soon as possible.

Shouldn't the issue remain opened until then?
Reason to keep it opened is for folks coming to file an issue similar to this one to see that it's a known one and subscribe to it, rather than raise additional issues.
