### ISSUE TITLE
Latency spikes when sending using MessageSender under moderate load

### ISSUE THREAD

**Issue by jstclair** [Azure/azure-service-bus#340]
# Description
ASP.NET Core 3.1 API running on .NET Core / Azure (West Europe) using the latest version of Microsoft.Azure.ServiceBus (4.1.1) seems to have occassional very high latency when sending messages using MessageSender. 

The MessageSender is registered as a singleton:

```csharp
services.AddSingleton<MessageSender>(provider => new MessageSender(connectionString, QueueName));
```
The sending code (in the controller) has been wrapped with some Serilog timing logging:

```csharp
private async Task SendLogEntry(LogEntry logEntry, string label = "Audit")
        {
            var body = JsonSerializer.SerializeToUtf8Bytes(logEntry, SerializerOptions);
            var sw = Stopwatch.StartNew();
            await _messageSender.SendAsync(new Message(body)
            {
                ContentType = "application/json",
                Label = label
            });
            sw.Stop();

            _diagnosticContext.Set("ServiceBusElapsed", sw.ElapsedMilliseconds);
        }
```

## Actual Behavior
1.  We're looking at occasional high latency in both our test and production environments. Each is using ASB Standard. In production, we see saw-tooth latency, with spikes between 10-15 seconds. In addition, the highest latency isn't associated with most messages sent in a period. Here's a chart from our Splunk showing the pattern. The underlying statistics are a little hard to see, but I can follow up with a table if needed.

![SplunkLog](https://user-images.githubusercontent.com/365694/75886817-296e8380-5e29-11ea-8fa3-835e2c651f33.png)

We see similar sawtooth in our test environment, even though load tends to be much lower.

## Expected Behavior
1.  I understand that Standard plan does not guarantee latency - I've opened a case with MS Support (via the Azure portal) but that (as expected) ended with a suggestion to upgrade to Premium. We would expect *some* latency spikes, but this just seems way outside the range of expected behavior - for most of our sends, the average latency is ~1-300 ms

My MS case # is available on request.

**Comment by axisc** [comment]
@jstclair, Thanks for opening this issue.

Since Standard is a shared tenant setup, the resources are being shared with multiple namespaces. The average case looks fine, but some throttling and latency is expected given the shared resources.

The recommendation to move to Premium stands for high throughput systems or in case your application is sensitive to latency and throttling (and need other Enterprise ready features).

If the application is not sensitive to throttling, or you don't anticipate high throughput for now, please feel free to use standard. If your throughput requirements change, there is always an option to move to Premium.

Hope this helps.

**Comment by jstclair** [comment]
So you’re confirming this is SB throttling and not noisy-neighbor? The regularity of the sawtooth kind of argues against the latter, especially given the variability of the # of messaging being sent?

Are the throttling limits documented anywhere? I mean once per 500 messages or per 1000, you will be throttled to 8-12 seconds to complete a send; honestly it’s a bit surprising to me.

We have other APIs that are pushing higher # of messages but haven’t seen similar latency. 

John

**Comment by SeanFeldman** [comment]
@jstclair, yes, it's documented [here](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-throttling).

**Comment by EldertGrootenboer** [comment]
The documentation has since been updated to make this clearer. If more clarity is still needed, please let us know, and we can re-open this issue.
