### ISSUE TITLE
My logic app is not working and throwing below error when I pass session id for queue connector.

### ISSUE THREAD

**Issue by ashuthinks** [Azure/azure-service-bus#343]
My logic app is not working and throwing below error when I pass session id for queue connector.

No session available to complete the message with the lock token
I already have enabled session while create a new queue.

https://i.stack.imgur.com/MrBMe.png

Is there any other settings required to work this?

**Comment by SeanFeldman** [comment]
@ashuthinks , welcome to the repo. Please note this is a broker issue tracker repo, **not LogicApps** (readme.md is [here](https://github.com/Azure/azure-service-bus/blob/master/README.md)).

For LogicApps related questions, use https://github.com/Azure/logicapps
