### ISSUE TITLE
messagReciever.OnMessageAsync() is able to read messages for ~20 min even after the Primary key got regenerated using azure portal

### ISSUE THREAD

**Issue by kannannet** [Azure/azure-service-bus#346]
I am using **WindowsAzure.ServiceBus 4.1.8** created a console application and created message reciver using messaging factory and registered with onMessageAsync().

I was expecting that once the **primary key refresh from the azure portal the program should throw unAuthorized exception** and stops reading message from service bus, but instead it keep recieving message for ~ 20 min and then doesnt recieve any message nor throws any exception. 

_Is this the Actual behaviour? If yes ,  how am i supposed to create a new reciever instance without any expetion which will act as  trigger ?_

This is my main method 

               static void Main(string[] args)
                     {
                       try
                        {

                var factory = MessagingFactory.CreateFromConnectionString("");
                factory.PrefetchCount = 1;
                var queue = factory.CreateMessageReceiver("test");
                var options = new OnMessageOptions()
                {
                    MaxConcurrentCalls = 1,
                    AutoComplete = false

                };
                Console.WriteLine(DateTime.Now);
                queue.OnMessageAsync(HandleMessageReceived, options);
                Console.ReadLine();
            }
            catch (Exception ex)
            {
                Console.WriteLine("exception caught" + ex.Message);
                throw;
            }

        }

and this is the handler method 

                async static Task HandleMessageReceived(BrokeredMessage brokeredMessage)
        {

            try
            {

                await brokeredMessage.CompleteAsync();

                Console.WriteLine("Message Processing completed");
               

            }
            catch (Exception ex)
            {
                Console.WriteLine("Message Handlet exception" + ex.Message);
                Console.WriteLine("has hit the catch of message handler ");
                throw;
            }
        }

## Actual Behavior
1. Receives messages for ~20 min even after key refresh
2. Stops receiving messages after than , doesn't throw any exception nor the execution stops 

## Expected Behavior
1. After Primary key refresh  immediately it should throw unauthorized exception

**Comment by kannannet** [comment]
@SeanFeldman  Do you have any idea on this ?

**Comment by SeanFeldman** [comment]
Regenerating the key does not abort all the established links right away. That explains why you can still retrieve messages for a while.

@nemakam this sounds like something a server could do better.
