### ISSUE TITLE
Socket Timeouts after calling SendAsync on TopicClient

### ISSUE THREAD

**Issue by jmflatt** [Azure/azure-service-bus#348]
# 'System.Net.Sockets.SocketException (110): Connection timed out' when calling SendAsync on TopicClient

We have been having issues trying to emit events onto the service bus via TopicClient. during the SendAsync call on the TopicClient, we are getting socket timeouts on a semi regular basis. This causes the app to sit for about 100 seconds and then eventually timeout. We are using: 
"Microsoft.Azure.ServiceBus" Version="4.1.2" in a dotnet core 2.1 application. the application is running in a docker container on a Linux centos virtual machine. 

 pseudo code below to reflect the process we are using to emit events:

```
public class ServiceBusEventPublisher
{
    private readonly IConfiguration _config;
    private IStorageService _storageService;
    private static ITopicClient _myTopicClient;
    private string serviceBusConnectionString;

    public ServiceBusEventPublisher(IConfiguration config, IStorageService storageService)
    {
        this._config = config;
        this._storageService = storageService;

        serviceBusConnectionString = _config.GetValue("ServiceBusConnectionString", string.Empty);

        _myTopicClient = new TopicClient(serviceBusConnectionString, AppConstants.MyTopicClient);
    }

    public async Task Publish(IMiddlewareEvent middlewareEvent, Int32 timeout)
    {
        Console.WriteLine($"Begin: Publish function with timeout parameter value {timeout} {DateTime.Now}.");

        myTopicClient.OperationTimeout = TimeSpan.FromMilliseconds(timeout);
        myTopicClient.ServiceBusConnection.OperationTimeout = TimeSpan.FromMilliseconds(timeout);
        var bodyString = JsonConvert.SerializeObject(middlewareEvent);
        var potentialPayload = Encoding.UTF8.GetBytes(bodyString);

        var message = new Message
        {
            Body = potentialPayload,
            ContentType = MediaTypeNames.Application.Json,
        };

        await myTopicClient.SendAsync(message);
    }
}  
 ```

below is the error that we are receiving : 

System.Net.Sockets.SocketException (110): Connection timed out
   at Microsoft.Azure.ServiceBus.ServiceBusConnection.CreateConnectionAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.ServiceBus.Amqp.AmqpLinkCreator.CreateAndOpenAmqpLinkAsync()
   at Microsoft.Azure.ServiceBus.Core.MessageSender.CreateLinkAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.ServiceBus.Core.MessageSender.OnSendAsync(IList`1 messageList)

please let me know if there is anything else i should include.

**Comment by Prinsn** [comment]
I can't help you, but I want to just offer support and solidarity as I struggle with a .NET 6 application upgrade from a working .NET Core 3.1 app getting similar issues.

**Comment by EldertGrootenboer** [comment]
If this issue still occurs using the latest SDK, please let us know and we can re-open the issue.
