### ISSUE TITLE
Azure Service Bus Premium Tier - Networking

### ISSUE THREAD

**Issue by srikanthku** [Azure/azure-service-bus#349]
# Description
Firewalls and Networks has been set to Selected Networks and no IP has been white listed, then the behavior is similar to All Networks.
If  at least one IP is added to the list with Selected Networks, then traffic is getting blocked from other IPs, please let me know if this is an issue or working as expected.

**Comment by clemensv** [comment]
That is correct. The feature activates as soon as you configure it for at least one IP.

**Comment by srikanthku** [comment]
I verified Storage Accounts, behavior of Firewall is different, even without white listing one IP Address, it is blocking access.
