### ISSUE TITLE
Receiving each message 10 times despite calling CompleteAsync

### ISSUE THREAD

**Issue by johnknoop** [Azure/azure-service-bus#35]
Hi

I'm just playing around with this new library and I know it's in pre-release. But I thought I'd let you know anyway...

My code is as simple as it gets:

```
        static void Main(string[] args)
        {
            var queueClient =
                new QueueClient("...", "GreetingsQueue");

            if (args.Length > 0 && args[0] == "publish") {
                queueClient.SendAsync(new Message(Encoding.UTF8.GetBytes(args[2])) {
                    SessionId = args[1]
                }).Wait();

                return;
            }

            queueClient.RegisterSessionHandler(async (session, message, cancel) => {
                var greeting = Encoding.UTF8.GetString(message.Body);
                Console.WriteLine(greeting);
                await queueClient.CompleteAsync(message.SystemProperties.LockToken);
            });

            Console.ReadKey(true);
        }
```

First I run on instance of the program without any argument, whichs starts listen for new sessions. Then I run another instans with arguments "publish 5 Hello" which sends the message Hello with statusid 5 to the queue. However, now the first instance prints out "Hello" 10 times, which about a second in between each.

John

**Comment by SeanFeldman** [comment]
@johnknoop If you're talking about Microsoft.Azure.ServiceBus library that is in preview, the proper repo to open this issue under would be https://github.com/Azure/azure-service-bus-dotnet 🙂

**Comment by SeanFeldman** [comment]
BTW, I think you need to use the `session` object to complete your message, not the `queueClient`.
I.e.
```
session.CompleteAsync(message.SystemProperties.LockToken);
```
Reason you get 10 messages is probably because your queue has `MaxDeliveryCount` of 10. After that messages are DLQed.

**Comment by SeanFeldman** [comment]
And this is why we need to have doco on the new client
/cc @sethmanheim

**Comment by johnknoop** [comment]
Oh sorry, I dont know how I ended up at this repo.
