### ISSUE TITLE
Document mixing management and messaging operations in a transaction 

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus#351]
Currently, there's no documentation about mixing management and messaging operations in a transaction. The only [documentation](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-transactions) about transactional processing refers to messaging operations.

**Comment by EldertGrootenboer** [comment]
We have opened a task for this in our backlog, and will update this issue when we have more information.

**Comment by EldertGrootenboer** [comment]
This document has been updated.

**Comment by SeanFeldman** [comment]
2.5 years were worth waiting for this note 😂

> Mixing management and messaging operations in a transaction isn't supported.

Jokes aside, appreciate finally closing this one with an action item followed through. Well done, @EldertGrootenboer 👏
