### ISSUE TITLE
 Unauthorized access. 'Send' claim(s) are required to perform this operation.

### ISSUE THREAD

**Issue by suneeth** [Azure/azure-service-bus#354]
# Description

## Actual Behavior
1. 
2. 

## Expected Behavior
1. 
2.

**Comment by SeanFeldman** [comment]
The issue is right in the title. Did you search the Azure Service Bus documentation for claims?
Here's a starting point: https://docs.microsoft.com/bs-latn-ba/azure/service-bus-messaging/service-bus-sas

Also, this issue tracker is for the server-side problems, not client-side.

**Comment by suneeth** [comment]
@SeanFeldman

**Comment by suneeth** [comment]
oh ok.. thanks! I will post this on the client library.
