### ISSUE TITLE
How to enable verbose logs to be emitted and written to appinsight for service bus dll

### ISSUE THREAD

**Issue by krishnasingh1818** [Azure/azure-service-bus#356]
# Description
Hi, we are noting that there is sometimes seconds taken to finish a send operation. We want to troubleshoot and find out what is consuming those many seconds in the service bus send calls.

Is there any setting that can be made in azure functions so that all logs from azure service bus (verbose) can be sent so that we know which part within your dll is taking most of the time.

Is there any other better way to find the breakup of the time ?

We have standard azure service bus plan and azure functions on consumption plan. I checked service bus metrics and no throttling happening or signs of high usage.

Below is sample image from appinsight.  Some of them taking even 14 to 20 seconds.

![image](https://user-images.githubusercontent.com/10679463/80756834-d3e8e700-8af8-11ea-93ad-288d30a5c1dc.png)

.net core 3.1 azure functions
service bus 4.1.1

**Comment by SeanFeldman** [comment]
> 14 to 20 seconds.

That's abnormal. Do you have the code/repro available to share?

**Comment by krishnasingh1818** [comment]
i have some snippets linked in this issue [355](https://github.com/Azure/azure-service-bus/issues/355). please see if that helps.

**Comment by EldertGrootenboer** [comment]
If this issue still occurs, please let us know and we can re-open the issue.
