### ISSUE TITLE
Client disconnection

### ISSUE THREAD

**Issue by 3d0it** [Azure/azure-service-bus#358]
# Description
Hi,

I've a problem with a unpredictable service bus client disconnection:

        public void DequeuePush<T>()
        {
            InitReceiver();
            PrepareCallback<T>();

            var messageHandlerOptions = new MessageHandlerOptions(ExceptionReceivedHandler)
            {
                MaxConcurrentCalls = 1,
                AutoComplete = false
            };

            _receiver.RegisterMessageHandler(ProcessMessagesAsync<T>, messageHandlerOptions);
        }

        private async Task ProcessMessagesAsync<T>(Message message, CancellationToken token)
        {
            var body = message.Body;
            var payload = MessagePackSerializer.Deserialize<T>(body);
            // OUR WARNING: 1. We assume that an exception at this point can kill in some cases the thread listening on the Service Bus (even if we have the handler for handling the exception).

            // 2. What should be the best way to handle an exception at this point without risking being disconnected from the servize bus?

            // 3. Are there any link retry / refresh methods to avoid losing the handler that receiving the messages ?

            // ATTEMPT TO REPLICATE EXCEPTION IN THIS POINT:
            // The exception is catched any time. But in our production code it happens to us, perhaps even after a some days, 
            // that the process remains active although it is no longer listening on the service bus, 
            // so the queue begins to fill up and we no longer receive any messages on this handler.
            //throw new Exception("Exception Test");

            if (Configuration.ReceiveMode == ReceiveMode.PeekLock)
                await _receiver.CompleteAsync(message.SystemProperties.LockToken);

            if (Callback.Method.IsStatic)
                ((ActionStaticCallback)_caller)(payload);
            else
                ((ActionCallback)_caller)(Callback.Target, payload);
        }

        private Task ExceptionReceivedHandler(ExceptionReceivedEventArgs exceptionReceivedEventArgs)
        {
            Console.WriteLine("Message handler encountered an exception: " + exceptionReceivedEventArgs.Exception);
            var context = exceptionReceivedEventArgs.ExceptionReceivedContext;
            Console.WriteLine($"- Endpoint: {context.Endpoint}");

            return Task.CompletedTask;
        }
		
Like described in ProcessMessagesAsync<T> with a comment, I obeserve a rare exception that kill the event handler, but if I simulate the exception, 
normally this is correctly processed in the ExceptionReceivedHandler method. Nonetheless, we have (one time every two week), a process that lost connection
with service bus without any log. Can you help me to understand this situation?

Demo project is attached.

Regards,
Edoardo

## Actual Behavior
1. Unpredictable disconnection - death of the handler

## Expected Behavior
1. No disconnection / handle exception 
[TestServiceBus.zip](https://github.com/Azure/azure-service-bus/files/4642738/TestServiceBus.zip)

**Comment by NiklasArbin** [comment]
Looks like the problem we're having. Could this be related to [22534](https://github.com/Azure/azure-sdk-for-net/issues/22534)?
