### ISSUE TITLE
Observing Microsoft.Azure.ServiceBus.ServiceBusCommunicationException with Microsoft.Azure.ServiceBus 4.1.3

### ISSUE THREAD

**Issue by rduser** [Azure/azure-service-bus#360]
# Description
Observing many exceptions after upgrading to the new SDK. Is this transient/expected?
I am using AMQP. Same bus with older windowsazure.servicebus did not show these errors

## Actual Behavior
Lots of exceptions 

Type: Microsoft.Azure.ServiceBus.ServiceBusCommunicationException
Message: The link 'b67cd3ee-710b-4b84-9619-71d9add7ea48;1505:1515:1517:source(address:cms-cdn-provision):MessageReceiver34cms-cdn-provision' is force detached. Code: RenewToken. Details: Unauthorized access. 'Listen' claim(s) are required to perform this operation. Resource: 'sb://xxxx.servicebus.windows.net/xxxx'.. TrackingId:f54c67080546400d958893728904d657_G31, SystemTracker:gateway7, Timestamp:2020-05-29T00:05:23Reference: f54c67080546400d958893728904d657_G31, 5/29/2020 12:05:23 AM
StackTrace:    at Microsoft.Azure.ServiceBus.Core.MessageReceiver.<OnReceiveAsync>d__86.MoveNext()
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.<>c__DisplayClass64_0.<<ReceiveAsync>b__0>d.MoveNext()
   at Microsoft.Azure.ServiceBus.RetryPolicy.<RunOperation>d__19.MoveNext()
   at Microsoft.Azure.ServiceBus.RetryPolicy.<RunOperation>d__19.MoveNext()
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.<ReceiveAsync>d__64.MoveNext()
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.<ReceiveAsync>d__62.MoveNext()
   at Microsoft.Azure.ServiceBus.MessageReceivePump.<<MessagePumpTaskAsync>b__11_0>d.MoveNext()
Type: Microsoft.Azure.ServiceBus.ServiceBusException
Message: The link 'b67cd3ee-710b-4b84-9619-71d9add7ea48;1505:1515:1517:source(address:cms-cdn-provision):MessageReceiver34cms-cdn-provision' is force detached. Code: RenewToken. Details: Unauthorized access. 'Listen' claim(s) are required to perform this operation. Resource: 'sb://xxxx.servicebus.windows.net/xxxx'.. TrackingId:f54c67080546400d958893728904d657_G31, SystemTracker:gateway7, Timestamp:2020-05-29T00:05:23
StackTrace:    at Microsoft.Azure.ServiceBus.Core.MessageReceiver.<OnReceiveAsync>d__86.MoveNext()

## Expected Behavior
No exceptions

**Comment by SeletskySergey** [comment]
The same issue, fixed in 4.1.4.

**Comment by pawel-zolty** [comment]
> The same issue, fixed in 4.1.4.

Is this issue officialy fixed in 4.1.1?
