### ISSUE TITLE
 Exception: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, at Microsoft.Azure.ServiceBus.Core.MessageSender.<SendAsync>d__45.MoveNext()

### ISSUE THREAD

**Issue by aarushi-mittal** [Azure/azure-service-bus#361]
Hello Team,

I have been trying a simple send/receive on a service bus topic/subscription since the last week .

However I keep on getting this error ** Exception: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.3.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) :: Stacktrace :    at Microsoft.Azure.ServiceBus.Core.MessageSender.<SendAsync>d__45.MoveNext()**

Kindly suggest.

Regards,
Aarushi

**Comment by snieking** [comment]
Also running into this issue, did you find any solution?

**Comment by SeanFeldman** [comment]
This repository is for broker related issues. Your issue seems to be a client-side with Microsoft.Azure.ServiceBus SDK.
Issues for client-side SDK for .NET are reported here: https://github.com/Azure/azure-sdk-for-net/.
Suggest moving your issue there and providing a repro code reference.
