### ISSUE TITLE
QueueRunTimeInfo.AccessedAt property shows latest timestamp even when there was no read or write 

### ISSUE THREAD

**Issue by amitm20692** [Azure/azure-service-bus#363]
# Description
I am using v4.1.3 dotnet client library.
I am trying to get last accessed time of a specific queue in a servicebus namespace.
I am using management client's GetQueueRuntimeInfoAsync method to get the info and accessing
QueueRunTimeInfo.AccessedAt property.

## Actual Behavior
1.  It's returning the latest access time(The time of calling the method) even if there are no reads and sends

## Expected Behavior
1. It should return last read or send timestamp

**Comment by EldertGrootenboer** [comment]
If this issue still occurs using the latest SDK, please let us know and we can re-open the issue.
