### ISSUE TITLE
Update subscription when processing a message throws 

### ISSUE THREAD

**Issue by topagarwal** [Azure/azure-service-bus#365]
I am using latest Azure service bus .Net core apis (Microsoft.Azure.ServiceBus" Version="4.1.3") to manage subscription in a topic.
I was trying to Update a subscription using UpdateSubscriptionAsync() API to update the defaultMessageTimeToLive and lockDuration.
However when I update the subscription when a message is being processed, I got "SessionLockLostException: Session lock lost. Accept a new session is force detached"

This also happened with non-session enabled subscription as well.

Is that expected? 
I did not see any documentation warning against updating a subscription. Are we suppose to check that there are no messages in subscription before updating it?

**Comment by EldertGrootenboer** [comment]
If this issue still occurs using the latest SDK, please let us know and we can re-open the issue.
