### ISSUE TITLE
ServiceBusActiveMessagesAvailableWithNoListenersEventData Event Grid Data Model is missing SessionId

### ISSUE THREAD

**Issue by mikemarmar** [Azure/azure-service-bus#367]
# Description

Service Bus can be configured to publish an event to Event Grid when a message arrives on a subscription but no receivers are connected and waiting to receive messages. This event contains data of type ServiceBusActiveMessagesAvailableWithNoListenersEventData, which contains the Topic and Subscription that received the message.

This event data model does **not** contain the SessionId of the message. Thus, if sessions are enabled on the Topic, there is no way to specifically request messages from the correct session (such as with SessionClient.AcceptMessageSessionAsync). In this case, the only way to handle the event is to register a session handler and process messages in all sessions. This can be very inefficient if there are many concurrent sessions and most do not currently need to be processed.

**Comment by mikemarmar** [comment]
Closed, as I realized this suggestion should be on the Azure Feedback forum, not here.

**Comment by SeanFeldman** [comment]
Don't waste your time on Azure Feedback. Instead, go straight for an issue tracker. Raise an issue with Azure SDK team that will assign the issue to the service team.
Link: https://github.com/Azure/azure-sdk-for-net/issues?q=is%3Aopen+is%3Aissue+label%3A%22Event+Grid%22

**Comment by SeanFeldman** [comment]
@jfggdl this is exactly why the service should have its own issue tracker.

**Comment by mikemarmar** [comment]
Thanks Sean. Link to issue on azure-sdk-for-net: https://github.com/Azure/azure-sdk-for-net/issues/13080

**Comment by jfggdl** [comment]
@mikemarmar, we do review Azure feedback and we strongly recommend that anything that is not a bug or a question is added to Azure feedback. We do use Azure feedback for our planning purposes and is the primary source of input for any work with respect to features requested by users.
