### ISSUE TITLE
Docs: Message​Session.​Set​State​Async maximum size of state

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus#37]
[Current documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.messagesession.setstateasync) doesn't elaborate what's the maximum allowed size.

@sethmanheim is that something that could be extracted easily? Thanks.

**Comment by SeanFeldman** [comment]
It seems that maximum state size is connected to the maximum message size (256KB/1MB). Even though individual message size is not showing the state size, it's all part of the same envelop. Should be documented to clarify this. Also, the fact that each message transferred on the wire will carry the state (if that's true).

**Comment by sethmanheim** [comment]
@hmlam Eric, can your team make the required updates in the source code?

**Comment by SeanFeldman** [comment]
@sethmanheim @hmlam thank you folks.

@sethmanheim you've read my mind with the label. Hopefully you'll be doing the same for the rest of them 😃

**Comment by sethmanheim** [comment]
Opened PG team bug 2110458.
