### ISSUE TITLE
ForwardTo with scheduled message setup in the subscription rule 

### ISSUE THREAD

**Issue by romankiss** [Azure/azure-service-bus#373]
I have a simple scenario where the message sent on the topic will be forwarded to the queue as a scheduled message.  For this behavior the topic subscription requires to setup the following properties:

 - ForwardTo
         `name of the queue entity`

- $Default Rule
    Filter:
            ` 1=1 `
    Action (example for 10 minutes):

      SET sys.TimeToLive = '00:10:00';
      SET EnqueuedTimeUtc = sys.EnqueuedTimeUtc;
      SET ScheduledEnqueueTimeUtc = sys.ExpiresAtUtc;
      SET sys.ScheduledEnqueueTimeUtc = sys.ExpiresAtUtc;
      SET sys.Label = 'Delay';
      SET sys.TimeToLive = '01:00:00';

              
The above scenario is suitable for publishers without setting the _ScheduledEnqueueTimeUtc_ property, for instance an Azure Event Grid, see the following [usage](https://stackoverflow.com/questions/63933101/how-to-postponed-event-trigger-receive). 

For test purposes, I have used for publishing event on the topic the following:

1. tool Service Bus Explorer (the latest release such as 4.1.112) - using the Microsoft.ServiceBus.dll
2. send message using the REST POST request
3. Azure portal, Service Bus Explorer (preview) (probably underlaying logic is using the REST APIs) 
4. Azure Stream Analytics Job - output to Service Bus Topic (probably underlaying logic is using the REST APIs) 
5. using a BrokeredMessage and Microsoft.ServiceBus.dll

All the above publishers sent the message on the topic and the message is forwarding to the queue as a scheduled message based on the rule action. That's a correct expectable behavior.  

What is the issue?

The issue is when the publisher using the new assembly such as **Microsoft.Azure.ServiceBus.dll**, so the _Azure Event Grid_, _Azure Function_ with ServiceBus output binding, etc. will not correct work at the copy of the message for ForwardTo process.
The reason is that the value of the _ScheduledEnqueueTimeUtc_ is always populated by value 1/1/0001 12:00:00 AM.

My testing shown that the rule action is working well such as setting the _ScheduledEnqueueTimeUtc_ when the ForwardTo property is empty. Once the ForwardTo property is configured, the _ScheduledEnqueueTimeUtc_ is overwritten by default value (1/1/0001 12:00:00 AM).

Based on the above, it looks like this is a bug and any publishers who is using the _Microsoft.Azure.ServiceBus.dll_ assembly will have this issue. 

Note, there is no workaround for this issue for that publishers where their integration is without customizing the system properties of the service bus message, for instance: Azure Event Grid. 

Thanks
Roman

**Comment by SeanFeldman** [comment]
Given this is a client SDK issue, I would suggest moving the issue to https://github.com/Azure/azure-sdk-for-net/issues. That way it will be addressed in the **Microsoft.Azure.ServiceBus** and the future **Azure.Messaging.ServiceBus** SDKs.
