### ISSUE TITLE
Need mechanism to dead letter a deferred message 

### ISSUE THREAD

**Issue by mfaulcon** [Azure/azure-service-bus#376]
Based on a review of the available documentation, there doesn't appear to be an obvious way to move a deferred message to the dead letter queue, since there is no MessageReceiver associated with it at the time it is rehydrated. Our scenario is to ensure that messages are processed in the correct order, but if one of the messages fails a validation check, all messages need to be dead lettered to invoke our logging and tracking mechanisms.

Am I missing someting?

**Comment by SeanFeldman** [comment]
A somewhat related issue as well: https://github.com/Azure/azure-sdk-for-net/issues/15097

**Comment by deepakmohansingh** [comment]
Hi @mfaulcon , just read your issue while I was looking for another similar to this. Isn't moving a deferred message to dead letter queue possible if we know the sequence number? It is already deferred and so, it is ready to be received with its sequence number. To check and identify deferred messages in order, you can use Message browsing capability. Please correct me if this answer is not suiting this issue as I'll take a deeper look. Thanks.

**Comment by EldertGrootenboer** [comment]
As @DeepakMohanSingh mentioned, you can dead-letter a deferred message by retrieving it and calling the deadletter method on it, as shown below.

var message = await receiver.ReceiveDeferredMessageAsync(<sequenceNumber>);
await receiver.DeadLetterMessageAsync(message);
