### ISSUE TITLE
BrokeredMessage 'has been disposed' when call 'Complete' from Asyn method

### ISSUE THREAD

**Issue by muhamad-ahsan** [Azure/azure-service-bus#38]
# Problem
I am using event based message receiving. I have attached my event handler on **OnMessage** event of **MessageReceiver** class. After receiving the message, I need to acknowledge it by calling **Complete** method of **BrokeredMessage** class. I am calling this method in another thread and receiving the exception: **'BrokeredMessage has been disposed'**.
I have verified following points:
1. Lock **has not** been expired
2. Object **has not** been disposed
3. Connection **has not** been closed

**Complete** cannot be called from any other thread? I am not able to find any answer...

## Versions  
- OS platform and version: Windows 10 Pro
- .NET Version: 4.6.1
- NuGet package version or commit ID: 3.4.4 (WindowsAzure.ServiceBus)

# Steps to Reproduce
1. Create **'MessageReceiver'** class from messaging factory with the **'ReceiveMode.PeekLock'**
2. Register the event handler with **'OnMessage'** event of receiver class created in step 1 with auto complete set to false
3. Once any message received, try to acknowledge from other thread (using Task library for example)

```
var messageReceiver = queueClient.MessagingFactory.CreateMessageReceiver("QueueName", ReceiveMode.PeekLock);
// Registering event.
messageReceiver.OnMessage(ReceiveReady, new OnMessageOptions { AutoComplete = false, MaxConcurrentCalls = sbSettings.MaxConcurrentReceiveCallback });

// ReceiveReady Implementation
private async void ReceiveReady(BrokeredMessage brokeredMessage)
{
    try
    {
        if (brokeredMessage != null)
        {
            Console.WriteLine("Received by {0}", Thread.CurrentThread.ManagedThreadId);

            await Task.Delay(TimeSpan.FromSeconds(3)); // To simulate some async work...

            Console.WriteLine("Acknowledged by {0}", Thread.CurrentThread.ManagedThreadId);

            await brokeredMessage.CompleteAsync();
        }
    }
    catch (Exception ex)
    {                
    }
}
```
@jtaubensee can have a look please? It is very urgent kind of issue.

**Comment by SeanFeldman** [comment]
A bit confused by the code snippet as it looks valid 100%.

@muhamad-ahsan you're explicitly completing your message within the callback

```c#
 await brokeredMessage.CompleteAsync();
```

Are you trying to complete it on another thread as well?

**Comment by muhamad-ahsan** [comment]
@SeanFeldman the receiver is configured with **PeekLock** and I am completing it by explicitly calling Complete method. Actually in case of async-await model, when method resumes, it is normally some other thread. So, the scenario is asyn await model.

**Comment by SeanFeldman** [comment]
@muhamad-ahsan async or not, if you've completed a message in the callback and trying to complete it elsewhere, it will throw. You should either not complete it in the handler and let other thread do it (that's what auto-completion is actually doing behind the scenes) or complete within the callback only.

**Comment by muhamad-ahsan** [comment]
@SeanFeldman I am doing in the handler only and it is only called once. It throws **MessageLockLostException** if complete is called again and in my case it is throwing 'has been disposed.' anyway.

**Comment by SeanFeldman** [comment]
> await Task.Delay(TimeSpan.FromSeconds(3)); // To simulate some async work...

How long is your actual work in the handler and what's the `LockDuration` value on the entity?

`MessageLockLostException` is a clear indication of what happens. I.e. the handler is taking longer than the `LockDuration` and when you attempt to complete the message, exception is thrown. If your processing exceeds `LockDuration`, you need to bump it up (default is 60 seconds, max is 5 mins).

**Comment by muhamad-ahsan** [comment]
> How long is your actual work in the handler and what's the LockDuration value on the entity?

@SeanFeldman actual work may take up to few milliseconds to seconds but in aysnc-await pattern. 

> MessageLockLostException is a clear indication of what happens. I.e. the handler is taking longer than the LockDuration and when you attempt to complete the message, exception is thrown. If your processing exceeds LockDuration, you need to bump it up (default is 60 seconds, max is 5 mins).

I am NOT getting **MessageLockLostException** exception, I just mentioned in the above comment that I would be getting this exception if it was the case of multiple calls to Complete method. Lock duration is  2 minutes.

Is it hard for you to reproduce the issue on your side?

**Comment by SeanFeldman** [comment]
I'll run through it. BTW, `async void` is not a good idea. Also, you should probably use `OnMessageAsync` to register your callback.

**Comment by muhamad-ahsan** [comment]
`async void` is common pattern for events because no one awaits on events. I am still trying to understand the scope of received **BrokeredMessage** in the handler. Because I was looking into the issue and stored the **BrokeredMessage** received in the handler into static variable; and I found as soon as it goes out of the handler scope, the **BrokeredMessage** gets disposed.

**Comment by SeanFeldman** [comment]
Which makes sense BTW. If you need to complete a message **outside** of the handler, complete it by using its [`LockToken`](https://docs.microsoft.com/en-ca/dotnet/api/microsoft.servicebus.messaging.queueclient.completeasync?view=azureservicebus-4.0.0).

In regards to `async void` it's a common pattern for UI event handlers, not if you're building a backend/library code. Just be aware.

**Comment by SeanFeldman** [comment]
This is not a bug, works as designed 😃

**Comment by muhamad-ahsan** [comment]
> Which makes sense BTW. If you need to complete a message outside of the handler, complete it by using its LockToken.

I did not know about this method and will try this.

> In regards to async void it's a common pattern for UI event handlers, not if you're building a backend/library code. Just be aware.

Just for understanding, what is better way if you need to make some async call from event handler in backend/library code?

**Comment by SeanFeldman** [comment]
> Just for understanding, what is better way if you need to make some async call from event handler in backend/library code?

Return a `Task`, not `void`. This [article](https://msdn.microsoft.com/en-us/magazine/jj991977.aspx) will help you. Cheers.

**Comment by muhamad-ahsan** [comment]
> This is not a bug, works as designed 😃
:grin: I could not find the info about life cycle of BrokeredMessage received in handler.

**Comment by SeanFeldman** [comment]
That is my friend another issue to raise 😉
