### ISSUE TITLE
Docs: for how long message session state is retained on the server

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus#39]
I've failed to locate any information for how long a session state is kept on the broker.

From my testing it appears that messages for a session can be all consumed, but the session state will continue for some time.`

**Comment by binzywu** [comment]
session state will remain as long as it is not cleared up as null.

**Comment by SeanFeldman** [comment]
Thank you @binzywu.
@sethmanheim this should probably be captured and some guidance around it as there's a chance to flood entities with session state that is not removed.

**Comment by sethmanheim** [comment]
Adding a note to the doc reading:

"Note that session state remains as long as it is not cleared up (returning **null**), even if all messages in a session are consumed."
