### ISSUE TITLE
Increase batch size

### ISSUE THREAD

**Issue by janpieterz** [Azure/azure-service-bus#396]
# Description
We have a lot of use cases where we need to send out a large batch of messages, ideally with strong transactional guarantees. For example, a certain item is added to a group of users, and all users need to be alerted with a notification (push, email, etc).

For each individual user a notification is of high importance, and though a rare double-send of a single message would be ok, sending 50K users a notification twice would really impact the behavior. We can solve this in user-land by adding another "lock" before sending (lock, check if sent, send notification, persist the fact the notification is sent, unlock) but that is not a great mode either as for each business case we'd need to write unique logic just to guarantee this isn't exploding when there's a small issue.

Ideally we'd be able to somehow batch _a lot_ of messages to be sent. I think for our use case the timing isn't that important (so for example they'd not necessarily all need to be delivered to the final queues right away, but having the transaction spanning the incoming and outgoing messages over way more messages would be great.

For reference, we use NServiceBus with Azure Service Bus and were discussing the issue [here](https://discuss.particular.net/t/sending-big-batches-of-messages/2142).

**Comment by EldertGrootenboer** [comment]
We don't have plans to increase the batch size, as this can create other issues.
