### ISSUE TITLE
How can I log subscriptions auto-delete events on the Azure service bus diagnostics logs?

### ISSUE THREAD

**Issue by EnricoMassone** [Azure/azure-service-bus#402]
Hi all,

we have an `ASP.NET core 2.2` application using Azure Service bus **topics and subscriptions**. 

**We have configured the auto delete on idle feature on the subscriptions**. After an idle time of `10` minutes the subscriptions are **automatically deleted** by the Azure infrastructure. 

We have enabled the **diagnostics logs** for our service bus namespace on the Azure portal as explained [here](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-diagnostic-logs). We have verified that we are actually collecting logs and we are able to see them from the Azure portal. So far, so good.

**Our problem is that we are not able to find among the collected logs the auto delete of the subscriptions after the configured idle time.** Based on [this](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-diagnostic-logs) documentation we would expected to see a log entry having an `EventName_s` with the value `AutoDelete Delete Subscription`, but we don't. We are sure that during our test at least one subscription has been deleted by the configured auto delete on idle rule. 

Are the subscription auto delete events actually logged, as stated in the docs ? 

Is there any configuration required to actually see the subscription auto delete events from the service bus diagnostics logs ?

Thanks for helping.

Enrico

**Comment by EldertGrootenboer** [comment]
Please make sure you have operational logs enabled in your diagnostics configuration. You should then be able to see these events, as described in https://docs.microsoft.com/en-us/azure/service-bus-messaging/monitor-service-bus-reference#operational-logs.
