### ISSUE TITLE
Could I build a mocked ServiceBus server locally?

### ISSUE THREAD

**Issue by nanan1993** [Azure/azure-service-bus#403]
Hi, I just wonder if I could test the client by establishing a mock servicebus locally?
I am trying to build a AMQP service, so that client could attach my local listener, send/receive messages.

I find it so hard to build a service that communicate well with client. Do you have some suggestions for local testing?

**Comment by tonto7973** [comment]
Hi @nanan1993 I've been developing a project that can do the very thing you asked for. Kindly find the link [here](https://github.com/tonto7973/xim/wiki/Xim-Amqp-Service-Bus-Simulator).

Regards
