### ISSUE TITLE
Microsoft.Azure.ServiceBus.QuotaExceededException: Cannot allocate more handles. The maximum number of handles is 4999.

### ISSUE THREAD

**Issue by daviegy** [Azure/azure-service-bus#404]
Ever since I implemented Microsoft Azure Service Bus, I have been having this error in my production environment.  
`Microsoft.Azure.ServiceBus.QuotaExceededException: Cannot allocate more handles. The maximum number of handles is 4999.`

I noticed that this error messages come up frequently when processing large numbers of messages but works with fewer.

Just to give you a overview my system processes lots of messages and service bus is core part of our processes. 

Please, find below my code

` public class ServiceBusSender: IServiceBusSender
    {  
        private  IQueueClient _queueClient;
        private readonly ServiceBusConnection _connection;
        
        public ServiceBusSender(ServiceBusConnection connection)
        {  
            _connection = connection;
        }

        public Task Publish<T>(T value, string queueName,string partitionkey = null)
        {          
            try
            {
                var message = new Message
                {
                    Body = Encoding.UTF8.GetBytes(JsonConvert.SerializeObject(value)),
                    PartitionKey = partitionkey
                };
                _queueClient = new QueueClient(_connection, queueName, ReceiveMode.PeekLock, RetryPolicy.Default);
                return _queueClient.SendAsync(message);
            }
            catch(QuotaExceededException ex)
            {
               throw ex;
            }
        }

    }
`
 Please, I will really appreciate if the servicebus team can point me to something I am doing wrong.
thanks

**Comment by xdansmith** [comment]
Each `QueueClient` represents a connection to Service Bus. You're creating a new `QueueClient` every time you send a message.  

Make sure to re-use connections, and close them when you're done.

**Comment by daviegy** [comment]
@xdansmith , thanks I will refactor, monitor and provide appropriate feedback.  Thank you

**Comment by SeanFeldman** [comment]
@daviegy, this is ASB service issue tracker, not the client. The client repository is https://github.com/Azure/azure-sdk-for-net/. Client-specific questions are more suitable for that repository. From looking at the code, you're continuously creating your clients and never close them, hence running into the maximum number of connections that can be made. Cheers.

**Comment by daviegy** [comment]
please is queueclient life cycle singleton or scope? @SeanFeldman

**Comment by SeanFeldman** [comment]
@daviegy, this is really not the right place to continue asking questions about the client SDK.
You literally have a team of Microsoft employees ready to answer your questions at the client repository. Cheers.

**Comment by daviegy** [comment]
Thank you @SeanFeldman
