### ISSUE TITLE
ServiceBusProcessor not receving messages when using Azure.Identity.ClientSecretCredential (TokenCredential))

### ISSUE THREAD

**Issue by fosterbuster** [Azure/azure-service-bus#405]
# Description

_Using Assembly Azure.Messaging.ServiceBus, Version=7.1.0.0_

I have tested the code using a connection string, and the code functions as expected. 

Instantiating a `ServiceBusAdministrationClient` using `Azure.Identity.ClientSecretCredential` also works fine, and allows me to add new subscriptions - So I presume that this is not an authentication issue.

Using the following setup:

1. Instantiate a servicebus client using 

`public ServiceBusClient(string fullyQualifiedNamespace, TokenCredential credential);`

2. Create a ServiceBusProcessor

```
 _processor =  client.CreateProcessor(
                   topicName: "...",
                   subscriptionName: "...",
                   new ServiceBusProcessorOptions { }
                );
```
`_processor.ProcessMessageAsync += ....`

## Actual Behavior
1. Events on ProcessMessageAsync are not fired

## Expected Behavior
1. Events on ProcessMessageAsync are fired

**Comment by SeanFeldman** [comment]
Wrong repo... [readme.md:](https://github.com/Azure/azure-service-bus)

> If you are looking for the code of a specific client library, see the following

you need https://github.com/Azure/azure-sdk-for-net
