### ISSUE TITLE
Distributed application framework (enhancement)

### ISSUE THREAD

**Issue by markgossa** [Azure/azure-service-bus#406]
# Description
There are only a few messaging/distributed application frameworks out there for .NET such as NServiceBus and MassTransit however there's nothing from Microsoft in this space. Would Microsoft be interested in starting something like this?

I've created my own messaging framework [here](https://github.com/markgossa/MessageBus) which I'm willing to donate or I can help start a new framework (with some help!). My framework (MessageBus) has already got the below features:

* Routing messages to message handlers
* Abstractions to plug in any messaging technology however only Service Bus has been developed so far
* Service Bus can connect with Managed Identity or Connection String
* Integration with .NET 5 Dependency Injection
* Message pre-processors and post-processors
* Creates subscription and subscription filters on service start-up (based on the message subscriptions that are configured in the service)
* Sends and receives messages (events and commands)
* Dead letters messages
* Automatic deserialization of messages
* Ability to define your own method of deserializing messages or just send text
* Ability to set custom Service Bus subscription options e.g. MaxDeliveryCount, LockDuration
* Ability to set custom Service Bus Processor options e.g. PrefetchCount
* Ability to send messages with custom message properties
* Message versioning (using attributes on implementations of IMessage)
* Health checks which check login to Azure Service Bus (for use with Kubernetes)

Let me know your thoughts.

## Actual Behavior
1. Developers have to write their own boilerplate code to listen to messages and route them to the correct message handlers which is prone to error and also it is lost time for many businesses

## Expected Behavior
1. Ability to create message handlers and just have the messages route through to the correct handlers (i.e. all the boilerplate code and abstraction is already developed and we just need to pull down a NuGet package)

**Comment by EldertGrootenboer** [comment]
Currently this is not something we want to pursuit. We are happy with the frameworks out there, and as MS ourselves we already have DAPR which will help our customers as well.
