### ISSUE TITLE
Unable to use ARM template to apply CMK

### ISSUE THREAD

**Issue by C-Meinert** [Azure/azure-service-bus#408]
# Description
Getting an error when enabling encryption using customer managed keys on service bus instances.  
I am using the Azure PowerShell cmdlet `New-AzResourceGroupDeployment` to update a service bus instance to use customer managed keys for encryption. This had been working without issues until 2021-03-03. That day we started to have intermittent failures and then eventually all attempts would fail with the same error, "Value cannot be null. Parameter name: key".  
ARM Template used (https://docs.microsoft.com/en-us/azure/service-bus-messaging/configure-customer-managed-key#use-resource-manager-template-to-enable-encryption)
```
{
   "$schema":"https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
   "contentVersion":"1.0.0.0",
   "parameters":{
      "namespaceName":{
         "type":"string",
         "metadata":{
            "description":"Name for the Namespace to be created in cluster."
         }
      },
      "location":{
         "type":"string",
         "defaultValue":"[resourceGroup().location]",
         "metadata":{
            "description":"Specifies the Azure location for all resources."
         }
      },
      "keyVaultUri":{
         "type":"string",
         "metadata":{
            "description":"URI of the KeyVault."
         }
      },
      "keyName":{
         "type":"string",
         "metadata":{
            "description":"KeyName."
         }
      }
   },
   "resources":[
      {
         "type":"Microsoft.ServiceBus/namespaces",
         "apiVersion":"2018-01-01-preview",
         "name":"[parameters('namespaceName')]",
         "location":"[parameters('location')]",
         "identity":{
            "type":"SystemAssigned"
         },
         "sku":{
            "name":"Premium",
            "tier":"Premium",
            "capacity":1
         },
         "properties":{
			"zoneRedundant":true,
            "encryption":{
               "keySource":"Microsoft.KeyVault",
               "keyVaultProperties":[
                  {
                     "keyName":"[parameters('keyName')]",
                     "keyVaultUri":"[parameters('keyVaultUri')]"
                  }
               ]
            }
         }
      }
   ]
}
```
## Actual Behavior
1. Authenticate to Azure using `Connect-AzAccount` 
2. Setup key in key vault
3. Grant service bus instance permission to read key from key vault  
4. Setup Template and Template Parameters files 
5. Run `New-AzResourceGroupDeployment` with arguments Name, ResourceGroupName, TemplateFile, TemplateParameterFile
6. Error message returned  
"The deployment '{DEPLOYMENT NAME}' failed with error(s). Showing 1 out of 1 error(s).
Status Message: Value cannot be null.
Parameter Name: key CorrelationId: {UUID} (Code: BadRequest)"

## Expected Behavior
1. Authenticate to Azure using `Connect-AzAccount` 
2. Setup key in key vault
3. Grant service bus instance permission to read key from key vault  
4. Setup Template and Template Parameters files 
5. Run `New-AzResourceGroupDeployment` with arguments Name, ResourceGroupName, TemplateFile, TemplateParameterFile
6. Success returned.

**Comment by EldertGrootenboer** [comment]
Please let us know if this is still an issue, in which case we can re-open this issue.
