### ISSUE TITLE
The session channel {0} cannot be found in connection {1} exception

### ISSUE THREAD

**Issue by jiripoledna** [Azure/azure-service-bus#409]
# Description
A obtain time to time the following exception  from service bus SDK in my service bus consumer

[{"method":"Microsoft.Azure.ServiceBus.SessionClient+<AcceptMessageSessionAsync>d__37.MoveNext","level":0,"line":0,"assembly":"Microsoft.Azure.ServiceBus, Version=4.1.3.0, Culture=neutral, PublicKeyToken=7e34167dcc6d6d8c"},{"method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":1,"line":0,"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"},{"method":"Microsoft.Azure.ServiceBus.SessionReceivePump+<SessionPumpTaskAsync>d__20.MoveNext","level":2,"line":0,"assembly":"Microsoft.Azure.ServiceBus, Version=4.1.3.0, Culture=neutral, PublicKeyToken=7e34167dcc6d6d8c"}],"outerId":"0","message":"**The session channel '1' cannot be found in connection 'out-connection34'**.","type":"**Microsoft.Azure.ServiceBus.ServiceBusCommunicationException**","id":"5112055"}

I have alerting system on Exception in my aplication and I do not want to disturbe the L2 support to solve such exception.  I did not find so much information if I can ignore this exception because the application will recover from this exception or it is needs some action on my side

I consume hungred thousands messages per day, but sometimes it happens, my subscribtion is set up as require Session

Thank you for help

Jiri Poledna

**Comment by EldertGrootenboer** [comment]
We have retry mechanisms in the SDK that will ensure recovery from these types of transient failures.
