### ISSUE TITLE
MessageAndSessionPump closes the connection on the receipt of SIGTERM.

### ISSUE THREAD

**Issue by vlaguduva** [Azure/azure-service-bus#411]
# Description

## Actual Behavior
1. On receipt of SIGTERM, MessageAndSessionPump closes the connection to service bus even though close/closeAsync is not called on queueClient. 
2.  I have a spring boot application that handles the SIGTERM for graceful shutdown - as part of graceful shutdown, the code calls queueClient.closeAsync to close the connection to Azure Service bus. Unfortunately, MessageAndSessionPump  closes the connection (log: Closing message and session pump on entity 'my_queue') much ahead of queueClient.closeAsync call.

## Expected Behavior
1. MessageAndSessionPump  should not close the connection until the queueClient.closeAsync is called.

**Comment by EldertGrootenboer** [comment]
This is an issue in the SDK, not the service. Please open a new issue in the SDK repository if this still occurs.
