### ISSUE TITLE
Azure.Messaging.ServiceBus Library NOT compatible with messages sent using WindowsAzure.ServiceBus

### ISSUE THREAD

**Issue by saikrishnav** [Azure/azure-service-bus#417]
# Description
I'm using Azure.Messaging.ServiceBus to RECIEVE messages from a Service Bus queue. Client that sends messages to Queue is using "WindowsAzure.ServiceBus". I do not OWN the client part/service, just the Receiver part. 

I'm listening to the queue using the library using "ServiceBusListener" class and getting a message of type "ServiceBusReceivedMessage" as mentioned in public docs here. https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-dotnet-get-started-with-queues

I know there is a bug that exists already which has a workaround here Azure/azure-service-bus-dotnet#239 (comment). But none of the workarounds are working for me. 

"ServiceBusReceivedMessage" is not (not derived or castable) from "Message" class in "Microsoft.Azure.ServiceBus" which I am not using. 

Getting string from body returns Unicode characters with XML namespace.
```
@\u0006string\u00083http://schemas.microsoft.com/2003/10/Serialization/�E\u0002{\r\n \"eventType\": blah blah.....
/u0001'
```

I just want a workaround that works for my receiver in .Net Core. Do I need to use "Microsoft.Azure.ServiceBus" instead of "Azure.Messaging.ServiceBus"?

**Comment by SeanFeldman** [comment]
Have a look at https://github.com/Azure/azure-service-bus-dotnet/issues/239. Specifically, https://github.com/Azure/azure-service-bus-dotnet/issues/239#issuecomment-320820562.

**Comment by saikrishnav** [comment]
@SeanFeldman - Literally mentioned this in my issue. This doesn't work because "GetBody" extension method is on "Message" class of Microsoft.Azure.ServiceBus, and not Azure.Messaging.ServiceBus. 

Also, I tried copying the "GetBody" code and I am not able to deserialize the message. 
It throws this error:
'Expecting element '<MyTypeHere>' from namespace 'http://schemas.datacontract.org/2004/07/somenamespacehere'.. Encountered 'Element'  with name 'string', namespace 'http://schemas.microsoft.com/2003/10/Serialization/'.'

**Comment by RobbBrock** [comment]
@saikrishnav I ran into the very same problem. I have a sender that is using FullDotNet Framework and WindowsAzure.ServiceBus to send messages to a Azure Service Bus Topic (I can't change their code!) My queue receiver is an Azure Function using DotNetCore 3.1 and Azure.Messaging.ServiceBus. I got the same deserialization error on the message.Body.ToString() method.
I know the sender is adding messages as "System.String" in a BrokeredMessage where the string is always JSON for the message body.
This is the code that I found that finally worked to receive those messages:
```
[FunctionName("Command")]
public async Task Command(
	[ServiceBusTrigger("bumpcmd", Connection = "ServiceBusQueueConnectionString")]
	ServiceBusReceivedMessage message
	, ILogger log
)
{
	var messageId = message.MessageId;
	var to = message.To;
	var subject = message.Subject;
	var serializer = DataContractBinarySerializer<string>.Instance;
	var jsonString = serializer.ReadObject(message.Body.ToStream()).ToString();
	var body = JsonConvert.DeserializeObject<dynamic>(jsonString);
	log.LogInformation($"Received {messageId} to {to}: {subject}");
}
```

**Comment by cwithfourplus** [comment]
Well I tried what @RobbBrock has mentioned and it does not work for me. The message body is already a string, so harm is already done before developer can do anything. There should be a flag on trigger that indicates Function/Service bus SDK that such a thing is needed and it is done before message is delivered to function.

**Comment by RobbBrock** [comment]
@cwithfourplus Note, in my sample code above the Azure Function is decorated with the type "ServiceBusReceivedMessage"  instead of "String". You need to receive the message as that type because the FullDotNet used "BrokeredMessage" with an internal serialization. based on type. That is what the `var serializer = DataContractBinarySerializer<string>.Instance;` is doing to deserialize the string out of the BrokeredMessage that was originally added to the ServiceBus.

**Comment by cwithfourplus** [comment]
@RobbBrock I realized that port my message and then I have this that works better:

`public static string GetJsonTextFromMessageText(Microsoft.Azure.ServiceBus.Message message)
{
    string jsonText = null;

    if (message != null && message.Body != null)
    {
        string messageBody = Encoding.UTF8.GetString(message.Body);

        if (messageBody.StartsWith("@"))
        {
            var serializer = DataContractBinarySerializer<string>.Instance;
            jsonText = message.GetBody<string>(serializer);
        }
        else
        {
            jsonText = messageBody;
        }
    }

    return jsonText;
}

public static string GetJsonTextFromMessageText(ServiceBusReceivedMessage message)
{
    string jsonText = null;

    if (message != null && message.Body != null)
    {
        if (message.Body.ToString().StartsWith("@"))
        {
            var serializer = DataContractBinarySerializer<string>.Instance;
            using (var stream = message.Body.ToStream())
            {
                jsonText = serializer.ReadObject(stream).ToString();
            }
        }
        else
        {
            jsonText = message.Body.ToString();
        }
    }

    return jsonText;
}`
