### ISSUE TITLE
NamespaceManager doesn't allow to discover namespace tier / capabilities

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus#42]
Current version of [`NamespaceManager`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.namespacemanager?view=azureservicebus-4.0.0) does not allow to discover namespace capabilities (tier, max entity size, etc).

/cc @djrosanova

**Comment by SeanFeldman** [comment]
I've seen this affecting SB360, Cerebrata Cerulean, SBExplorer - they all require users to provide information about namespace type rather than being able to read it using `NamespaceManager`. From a user (and a developer) point of view that's a usability issue. Would be really nice if this could be addressed.

Cerebrata Cerulean:
![image](https://user-images.githubusercontent.com/1309622/27803386-625a96fa-5fe6-11e7-91a6-6586b93d88dd.png)

SB360:
![image](https://user-images.githubusercontent.com/1309622/27803348-32377484-5fe6-11e7-9f2a-4d1debd95fa3.png)

**Comment by yvesgoeleven** [comment]
💯 Yes please, our tools could be a lot better if we knew what type of namespace we were dealing with

**Comment by paolosalvatori** [comment]
As the author of the Service Bus Explorer, I raised this issue many times in the internal distribution lists. Let me raise this again. It's extremely important that you add a method or a property to retrieve the namespace type as this is important to understand which entities to retrieve at runtime. The tool already provides the ability to specify which entities to retrieve (queues, topics, notification hubs, event hubs, relays), but this is left to the user, while it would be great if this could be automated. Thanks

**Comment by SeanFeldman** [comment]
Thank you for categorizing this feature request.
Would it be possible to assign a milestone to have an idea when it might be available?

**Comment by SeanFeldman** [comment]
This is now possible with the new client and `ManagementClient` (.NET Standard client).

@axisc looks like some old issues might be no longer needed if fixes are deployed.
