### ISSUE TITLE
Prefiltering failed with size exceeding header stream size limit, please don't use this feature for production

### ISSUE THREAD

**Issue by steinmr** [Azure/azure-service-bus#425]
Hi, when using a Azure SB namespace that was created about 4 years ago, and on a topic with a lot of subscriptions, I get this error message, which I'm pretty sure originates from the service itself (and not from the client library):

`Prefiltering failed with size exceeding header stream size limit, please don't use this feature for production. `

This message is pretty unusual, seems like some kind of debug code.

Unfortunately I cannot re-create the namespace without a lot of work, so hopefully this bug can be fixed.

**Comment by SeanFeldman** [comment]
cc @shankarsama

**Comment by patels-ms** [comment]
Please try this solution using the WindowsAzure.ServiceBus nuget package.:
update the topics with the code snippet below 
-------------------- Code -------------------------
                string connectionString = NAMESPACE_MANAGE_CONNECTION_STRING;
                var connectionStringBuilder = new ServiceBusConnectionStringBuilder(connectionString);
                var namespaceManager = new NamespaceManager(
                    "https://<ServiceBusNameSpaceName>.servicebus.windows.net/",
                    new NamespaceManagerSettings 
                    { 
                        TokenProvider = TokenProvider.CreateSharedAccessSignatureTokenProvider(
                            connectionStringBuilder.SharedAccessKeyName, 
                            connectionStringBuilder.SharedAccessKey) 
                    });

                IEnumerable<TopicDescription> topics = namespaceManager.GetTopics();
                foreach (TopicDescription topic in topics)
                {
                    if (topic.EnableFilteringMessagesBeforePublishing)
                    {
                        topic.EnableFilteringMessagesBeforePublishing = false;
                        namespaceManager.UpdateTopic(topic);
                    }
                } 

------------------ Coe End -----------------------

**Comment by steinmr** [comment]
Thanks @patels-ms, I will try this out. 

Is there any way of seeing the current value of this somewhere else? Like exporting the ARM template, or running a PS/az command? I would like you look through all our other namespace to see if there are any other that have the same problem.

**Comment by EldertGrootenboer** [comment]
You can use the code mentioned above to loop through the different entities and get their value.
