### ISSUE TITLE
Not able to update Client ID and Durable from CLI and ARM.

### ISSUE THREAD

**Issue by Ravi-Macha** [Azure/azure-service-bus#426]
# Description

I have created the Azure Service bus, Topic and Subscription. I am not able to update mentioned parameters with CLI OR ARM.

ClientID
Client Scope
Durable
 

## Actual Behavior
1. I am not able to find any CLI command to update
2. I dont have any sample template to update properties.

## Expected Behavior
1. I should have CLI command to update mentioned properties. 
2. I should be able to update those values with ARM template.

**Comment by Saglodha** [comment]
Hi @Ravi-Macha, thanks for reaching out to us. 

I looked at the ARM template and could see the object to be added there: https://docs.microsoft.com/en-us/azure/templates/microsoft.servicebus/namespaces/topics/subscriptions?tabs=json , can you please use ARM template and confirm if it works as expected? 

We would triage internally on CLI cmdlet support and would let you know. Thanks cc @EldertGrootenboer

**Comment by SeanFeldman** [comment]
> I have created the Azure Service bus, Topic and Subscription. I am not able to update mentioned parameters with CLI OR ARM.
> 
> ClientID
> Client Scope
> Durable

I don’t recall these on ASB entities or namespace. @Ravi-Macha share are those?

**Comment by EldertGrootenboer** [comment]
As @SeanFeldman said, these don't seem to be properties on the namespace or it's entities, so the can't be set from ARM or the CLI.
