### ISSUE TITLE
Client: Interference with NUnit over System.Runtime.Remoting.Messaging.CallContext

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus#43]
## Description

Running into some odd behavior with ASB (WindowsAzure.ServiceBus) and NUnit where ASB seems to affect `System.Remoting.Messaging.CallContext` expected by NUnit to be in place. 

- NUnit issue https://github.com/nunit/nunit/issues/2275
- [Repro code](https://github.com/SeanFeldman/NUnitWithASB.TextExecutionContext.Repro/)

## Actual Behavior

NUnit is throwing `NullReferenceException` as it fails to read from `CallContext`. Preliminary execution points at ASB client (no source available) to cause it.

## Expected Behavior

The expected to be found `CallContext` data for NUnit should not be touched and NRE exception should **not** be triggered.

**Comment by hmlam** [comment]
Can you check and see if the new client has the same problem? I expect this to be exclusive to old client, but I want to make sure. Thanks

**Comment by SeanFeldman** [comment]
Have confirmed on a [separate branch](https://github.com/SeanFeldman/NUnitWithASB.TextExecutionContext.Repro/tree/new-client) that the new client doesn't have this problem. I.e. `CallContext` is not affected.

@hmlam so this is definitely something in the old client.

**Comment by SeanFeldman** [comment]
@hmlam any updates on your end? Thanks.

**Comment by EldertGrootenboer** [comment]
If this issue still occurs, please let us know and we can re-open the issue.
