### ISSUE TITLE
Azure service bus

### ISSUE THREAD

**Issue by mukthiarahamad** [Azure/azure-service-bus#430]
Hi ,

I am using Azure.Messaging.ServiceBus "Azure.Messaging.ServiceBus" Version="7.1.1" and we are currently facing an issue.

We have a service bus triggered Azure function . Currently the issue that we are facing is when we have an exception in the azure function the message is getting lost and is not present in the dead letter queue.

Do we need send the message manually to the deal letter queue? like below

    
public async void Run([ServiceBusTrigger("GLS_Event_UWTransformOutbound", "TransformOutbound", Connection = "gls_event_uwtransformoutbound_listen")] MessageReceiver messageReceiver, ILogger log)

and use this message receiver to push the message back to the dead letter queue?

**Comment by EldertGrootenboer** [comment]
Can you check if you have set [autoCompleteMessages](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus?tabs=in-process%2Cextensionv5%2Cextensionv3&pivots=programming-language-csharp#hostjson-settings) in your binding to true? In this case the message will be completed as soon as you receive it, and you are responsible for handling the message in case of exceptions. If you set this to false and don't complete the message, it will be placed back on the queue, and after the maximum number of retries will be automatically deadlettered.
