### ISSUE TITLE
Managed Debugging Assistant 'ContextSwitchDeadlock' 

### ISSUE THREAD

**Issue by xbaha** [Azure/azure-service-bus#433]
# Description

Error:

Managed Debugging Assistant 'ContextSwitchDeadlock' : 'The CLR has been unable to transition from COM context 0xe19c50 to COM context 0xe19b98 for 60 seconds. The thread that owns the destination context/apartment is most likely either doing a non pumping wait or processing a very long running operation without pumping Windows messages. This situation generally has a negative performance impact and may even lead to the application becoming non responsive or memory usage accumulating continually over time. To avoid this problem, all single threaded apartment (STA) threads should use pumping wait primitives (such as CoWaitForMultipleHandles) and routinely pump messages during long running operations.'

Is this normal? i got this error after 1 week
![azsb-error](https://user-images.githubusercontent.com/10267198/123024727-1a3f8a80-d40c-11eb-9cd5-3fdd16c72273.png)

**Comment by EldertGrootenboer** [comment]
Can you please share the code which is causing this issue on egrootenboer@microsoft.com?
We will look into it, and come back when we have more information.

**Comment by EldertGrootenboer** [comment]
Closing this issue as no further communication was received. If this issue still occurs, please feel free to reach out with the code that is causing this issue.
