### ISSUE TITLE
Allow not having RootManageSharedAccessKey

### ISSUE THREAD

**Issue by jesperkristensen** [Azure/azure-service-bus#434]
# Description

I would like to be able to create a Service Bus namespace without a RootManageSharedAccessKey, so I don't have a key I need to regularly regenerate. Similar to how you can set allowSharedKeyAccess: false on a Storage Account.

## Actual Behavior
1. Create a new Service Bus namespace
2. RootManageSharedAccessKey is automatically created

## Expected Behavior
1.  Create a new Service Bus namespace
2. RootManageSharedAccessKey should not be automatically created

**Comment by EldertGrootenboer** [comment]
This is already possible with the [disable local auth feature](https://docs.microsoft.com/eN-US/azure/service-bus-messaging/disable-local-authentication). When enabled we don't allow using SAS keys for authentication, but only allow Azure AD authentication.
