### ISSUE TITLE
AutoDeleteOnIdle is deleting subscriptions even when having an active subscriber looking for messages

### ISSUE THREAD

**Issue by AnQueth** [Azure/azure-service-bus#439]
here is the code. the subscriptionclient will get an error that the subscription is not found after the time of AutoDeleteOnIdle passes.

using Azure.Messaging.ServiceBus;
using Azure.Messaging.ServiceBus.Administration;
using Microsoft.ApplicationInsights;
using Microsoft.Extensions.Hosting;
using System;
using System.Threading;
using System.Threading.Tasks;

 

namespace SearchEngine.ApplicationServices.HostedServices
{
    public class DynamicDataInternalProcessor : IHostedService
    {
        private ServiceBusClient _serviceBusClient;
        private ServiceBusAdministrationClient _administrationClient;
        private ServiceBusSessionProcessor _serviceBusSessionProcessor;
        private readonly TelemetryClient _telemetryClient;

 

        public DynamicDataInternalProcessor(TelemetryClient telemetryClient)
        {
            this._telemetryClient = telemetryClient;
        }

 

        public async Task StartAsync(CancellationToken cancellationToken)
        {
            bool started = false;
            var connectionString = "";
            var topic = "";
            var subscription = "";
            while (!started)
            {
                try
                {

 

                    this._administrationClient = new ServiceBusAdministrationClient(connectionString);

 

                    if (!await this._administrationClient.SubscriptionExistsAsync(topic, subscription, cancellationToken))
                    {
                        await this._administrationClient.CreateSubscriptionAsync(new CreateSubscriptionOptions(topic, subscription)
                        {
                            RequiresSession = true,
                            MaxDeliveryCount = 500,
                            DeadLetteringOnMessageExpiration = true,
                            AutoDeleteOnIdle = TimeSpan.FromMinutes(5)
                        }, cancellationToken);

 

                        this._telemetryClient.TrackTrace($"Created Subscription {subscription} in topic {topic}");
                    }

 

                    this._serviceBusClient = new ServiceBusClient(connectionString);

 

                    this._serviceBusSessionProcessor = this._serviceBusClient.CreateSessionProcessor(topic, subscription, new ServiceBusSessionProcessorOptions
                    {
                        ReceiveMode = ServiceBusReceiveMode.PeekLock,
                        AutoCompleteMessages = false,
                        MaxConcurrentSessions = 100,
                        SessionIdleTimeout = TimeSpan.FromSeconds(1)
                    });

 

                    this._serviceBusSessionProcessor.ProcessMessageAsync += this.ProcessMessageAsync;
                    this._serviceBusSessionProcessor.ProcessErrorAsync += this.ProcessErrorAsync;

 

                    await this._serviceBusSessionProcessor.StartProcessingAsync();

 

                    started = true;
                }
                catch (Exception ex)
                {
                    _telemetryClient.TrackException(ex);
                }
            }
        }

 

        public async Task StopAsync(CancellationToken cancellationToken)
        {

 

        }

 

        private async Task ProcessMessageAsync(ProcessSessionMessageEventArgs args)
        {
           
        }

 

        private Task ProcessErrorAsync(ProcessErrorEventArgs args)
       {
            _telemetryClient.TrackException(args.Exception);

 

            return Task.CompletedTask;
        }
    }
}
 

## Actual Behavior
1. Subscription is deleted when a listener is using it

## Expected Behavior
1.  Idle time should be based on an actual listener not being present. I expect the subscription to live until there is no one listening on it for x amount of time.

**Comment by EldertGrootenboer** [comment]
There actually needs to be traffic for the interval to be reset, just having a connection is not enough. We will update the documentation accordingly (https://docs.microsoft.com/en-us/azure/service-bus-messaging/advanced-features-overview#autodelete-on-idle).

**Comment by SeanFeldman** [comment]
Just a suggestion - it's better to close an issue such as this one when there's either a PR that references the issue or when the documentation is updated (if docs PR is internal). It also eliminates any chances of things accidentally being dropped of w/o the desired outcome.

Would you agree with that @EldertGrootenboer?

**Comment by AnQueth** [comment]
we need to delete subscriptions when the subscriber hasn't been connected in X amount of time. we thought this idle thing would work, but because messages are sent, it won't ever delete them. the self deletion of a subscription is not guaranteed if a process crashes or the delete times out.

**Comment by EldertGrootenboer** [comment]
@SeanFeldman Thanks for the feedback, the PR has been done internally, but indeed is not updated externally yet, I'll re-open until the change has propagated.

**Comment by EldertGrootenboer** [comment]
The documentation has been updated indicating the expected behavior.

> There actually needs to be traffic for the interval to be reset, just having a connection is not enough. We will update the documentation accordingly (https://docs.microsoft.com/en-us/azure/service-bus-messaging/advanced-features-overview#autodelete-on-idle).
