### ISSUE TITLE
No Java sample code for Service Bus topics and subscriptions

### ISSUE THREAD

**Issue by ZhijunZhao** [Azure/azure-service-bus#44]
I can see Java sample code for Service Bus queues. Please provide sample code for topics and subscriptions.

**Comment by mkporwit** [comment]
Ummm, wouldn't this already be handled by https://github.com/Azure/azure-service-bus/blob/master/samples/Java/azure-servicebus/TopicClientQuickstart/src/main/java/com/microsoft/azure/servicebus/samples/topicclientquickstart/TopicClientQuickstart.java and by https://github.com/Azure/azure-service-bus/blob/master/samples/Java/azure-servicebus/ManagingTopicRules/src/main/java/com/microsoft/azure/servicebus/samples/managingtopicrules/ManagingTopicRules.java?

**Comment by binzywu** [comment]
Yeah, the issue should be closed now.
