### ISSUE TITLE
The host is disposed and cannot be used when running process at Service bus 

### ISSUE THREAD

**Issue by sonnn1610** [Azure/azure-service-bus#440]
I have an Azure Function triggered by Service Bus (standard plan). Most of the time it works OK, but when I do a load test with around 100 messages to a topic. the exception is thrown as below,

## Actual Behavior
1. Some processes have been stopped immediately, while some processes are still done.

## Expected Behavior
1.  All processes should be done or move to DLQ if it's failed

Here is a detailed exception logs:
- problemId: 
`DryIoc.ContainerException at DryIoc.Throw.It`
- outerMessage: 
`The host is disposed and cannot be used. Disposed object: 'Microsoft.Azure.WebJobs.Script.WebHost.DependencyInjection.ScopedResolver'; Found IListener in stack trace: 'Microsoft.Azure.WebJobs.ServiceBus.Listeners.ServiceBusListener, Microsoft.Azure.WebJobs.ServiceBus, Version=3.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'`
- innermostMessage: 
`Container is disposed and should not be used: Container is disposed.
You may include Dispose stack-trace into the message via:
container.With(rules => rules.WithCaptureContainerDisposeStackTrace())`

**Comment by EldertGrootenboer** [comment]
As this seems to be an issue in the Functions runtime, please open an issue at https://github.com/Azure/Azure-Functions/issues if this issue still occurs.
