### ISSUE TITLE
Old version of SDK in use??

### ISSUE THREAD

**Issue by maulik-modi** [Azure/azure-service-bus#441]
# Description

## Actual Behavior
1. 
2. 

## Expected Behavior
1. 
2.

**Comment by SeanFeldman** [comment]
@maulik-modi what's the context not your question?
Note that this is **not** the repo for SDK.

**Comment by maulik-modi** [comment]
Azure service bus team recommends using Azure.Messaging Nuget, Is it possible to update code sample to use it?

**Comment by EldertGrootenboer** [comment]
@maulik-modi Are there any particular code samples where you want to see this?

**Comment by maulik-modi** [comment]
@EldertGrootenboer , Deadlettering, sessions and Active-Passive Azure service bus instances

**Comment by SeanFeldman** [comment]
I suspect @maulik-modi  is referring to the samples found at the https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus repository linked from the ASB documentation.

In the past, the ASB team was in charge of the documentation and samples. When the documentation was refreshed from WindowsAzure.ServiceBus to Microsoft.Azure.ServiceBus, those sample were introduced. When the SDK team took over the client for ASB, they've introduced Azure.Messaging.ServiceBus and consolidated the documentation under the GitHub repo https://github.com/Azure/azure-sdk-for-net. That also included _some_ samples (https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/servicebus/Azure.Messaging.ServiceBus#examples) and a migration guide (https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/MigrationGuide.md). The work to update the  [docs site](https://docs.microsoft.com/en-us/azure/service-bus-messaging/) hasn't been completed. I think that's the gist of it, @EldertGrootenboer.

**Comment by EldertGrootenboer** [comment]
We have added migration of all samples which are not there for the latest SDK to the backlog. For follow-up, please use the issue in [the SDK repository](https://github.com/Azure/azure-sdk-for-net/issues/28215).
