### ISSUE TITLE
Can Azure Service Bus support session enabled queue/subs via JMS API?

### ISSUE THREAD

**Issue by yiliuTo** [Azure/azure-service-bus#444]
# Description
From the [unsupported-features-and-restrictions](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-java-how-to-use-jms-api-amqp#unsupported-features-and-restrictions) section for using JMS with Service Bus, it's declared that setting **MessageSelector** via jms is not supported, while MessageSelector results in the filter property of an AMQP frame which is used by Service Bus for session enabled queue/subs, thus does it also mean that I cannot use JMS to receive messages from session enabled queues? 

Here are the details I found, when using [Service Bus sessions](https://docs.microsoft.com/en-us/azure/service-bus-messaging/message-sessions), it requires an AMQP message's [filter](http://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-messaging-v1.0-os.html#type-filter-set) as **com.microsoft:session-filter**, however, when using JMS's selector, the filter has been hard-coded as "[jms-selector](https://github.com/apache/qpid-jms/blob/8113b93fae8bb7f90f31fe0e68fcab46b330348f/qpid-jms-client/src/main/java/org/apache/qpid/jms/provider/amqp/builders/AmqpConsumerBuilder.java#L254)", so seems using JMS cannot receive messages from session enable queues.

Is it possible that the feature can be supported via JMS?

## Actual Behavior
1. When using azure-messaging-servicebus client to for session enabled queues, the related AMQP frame is as below

![image](https://user-images.githubusercontent.com/63028776/127949359-986a5f07-442b-46da-adae-6a6b1520627a.png)

2. However when using JMS and set a selector as "Group-Id = 'test'", the AMQP frame is 

![image](https://user-images.githubusercontent.com/63028776/127949631-f2437557-b9ce-423a-a946-1450126f3baa.png)

which then resulted in the error mentioned in #326.

## Expected Behavior
Message session feature can be supported with JMS selector.

**Comment by vmuthusamy-nlg** [comment]
I'm also running into a similar error while trying to consume messages from session-enabled queues using camel-amqp (2.23.x) component in the spring boot application. Is this feature supported using JMS API ? 

 o.a.q.j.p.a.b.AmqpResourceBuilder - Open of resource:(JmsConsumerInfo: { ID:xxxxxxxxxxxxxxxx-xxxxxxxx:6:1:1, destination = queue-5 }) failed: It is not possible for an entity that requires sessions to create a non-sessionful message receiver.

**Comment by abhikt48** [comment]
+1 

it will be great if we have this feature via JMS APi..

**Comment by clemensv** [comment]
The JMS API does not support our session model, unfortunately. We can only work with what we get as the standard interface.

**Comment by EldertGrootenboer** [comment]
#please-close
