### ISSUE TITLE
[Design flaw?] Replay message from subscriber's DLQ to same subscriber only rather than topic

### ISSUE THREAD

**Issue by Camios** [Azure/azure-service-bus#445]
When a message is sent to a service bus topic it is sent to all of the topic's subscribers. There is a 1:* relationship between topic and subscribers.
I assume each subscriber has their own incoming message queue/box - a 1:1 relationship.
If a subscriber fails to process the message it can end up on the subscriber's specific dead letter queue (DLQ). There is a 1:1 relationship between the subscriber and their DLQ.

Yet when when you want to replay a message from a subscriber-specific DLQ, why does it have to be sent to the topic and distributed to all subscribers. The DLQ is subscriber-specific and the failure could very well be subscriber-specific, so why (wastefully) send to all the other subscribers?
Why isn't there an ability to send from a subscriber's DLQ directly to the subscriber's incoming message box/queue?
This request is seeking for this functionality to be implemented.

If there is a reason it cannot be implemented, is there a alternative (eg pattern)?

**Comment by EldertGrootenboer** [comment]
This is by design, and as such will not be changed. Instead of resubmitting the message to the topic, we recommend to process it after receiving from the DLQ.
