### ISSUE TITLE
[Bug] ServiceBus premium could allow up to 100 MB for the messages

### ISSUE THREAD

**Issue by Scarlettliuyc** [Azure/azure-service-bus#446]
# Description
Hi team, 
We have a feature that allow Service Bus premium send message up to 100 MB. 
However when I test in my environment with this SDK  
but got error :
Microsoft.ServiceBus.Messaging.MessageSizeExceededException: 'A request from the client instance has exceeded the maximum message size, and the underlying channel will be recreated. Validate the content size before retrying..TrackingId:c3a33638-384f-4626-86c5-de2177268cc7, Timestamp:8/18/2021 10:23:32 AM'

Here is my test code. 
//service bus send message to queue
using Microsoft.ServiceBus.Messaging;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SendReceiveQueue
{
    class Program
    {
        static string connectionString = "";
        static string queueName = "";
        static void Main(string[] args)
        {
            MainAsync().GetAwaiter().GetResult();
        }
        static async Task MainAsync()
        {
            var factory = MessagingFactory.CreateFromConnectionString(connectionString);
            //create a receiver on the queue
            var receiver = await factory.CreateMessageReceiverAsync(queueName);
            //create a sender on the queue
            var sender = await factory.CreateMessageSenderAsync(queueName);
            Byte[] bytes = File.ReadAllBytes("C:/Users/yuchliu/OneDrive - Microsoft/Documents/ServiceBus200/question2/SBCert-L200-Lab2-pure/SBCert-L200-Lab2-master/SendReceiveQueue/test.xml");
            String file = Convert.ToBase64String(bytes);

            //start message pump to listen for message on the queue

            //send 3 message to the queue
            Console.WriteLine("Sending Message 1");
            await sender.SendAsync(new BrokeredMessage(file) { MessageId = "deadbeef-dead-beef-dead-beef00000075" });
            Console.WriteLine("Sending Message 2");
            await sender.SendAsync(new BrokeredMessage(file) { MessageId = "deadbeef-dead-beef-dead-beef00000075" });
            Console.WriteLine("Sending Message 3");
            await sender.SendAsync(new BrokeredMessage(file) { MessageId = "deadbeef-dead-beef-dead-beef00000075" });

            await Task.WhenAny(
                Task.Run(() => Console.ReadKey()),
                Task.Delay(TimeSpan.FromSeconds(30))
            );
        }
    }
}

here is my ServiceBus Queue,  I changed the queue max size to **1**00m****

![image](https://user-images.githubusercontent.com/69622329/129883446-7891c2ac-39db-4c00-9be3-8d9141b8d81a.png)

https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-premium-messaging#large-messages-support-preview

the document mentioned it's support for all the SDK 

## Actual Behavior
1. Got error Microsoft.ServiceBus.Messaging.MessageSizeExceededException
2. customer sent from Biztalk server using this SDK so also have error when message above 1MB

## Expected Behavior
1. The message above 1MB should send to Service Bus Queue

Questions:
whether this SDK could support this feature?

**Comment by SeanFeldman** [comment]
@Scarlettliuyc this repo is for the broker, not the client-side SDKs.

It appears you’re using the legacy SDK, SDK that should be updated to the latest. Also, note the following from the article you’ve linked to:

> Supported only when using the AMQP protocol. Not supported when using the SBMP protocol.

The SDK you appear to be using uses SBMP by default.

**Comment by Scarlettliuyc** [comment]
Thanks @SeanFeldman , as I have customer needs to use SBMP, could you please tell me whether we have ETA for this large message function implement in this SDK?
Thank you

**Comment by SeanFeldman** [comment]
@Scarlettliuyc I do not represent Microsoft. Saying that, SBMP is a legacy protocol. The customer should be not using it.

**Comment by EldertGrootenboer** [comment]
@Scarlettliuyc We do not plan to support the large message size feature on our older SDKs. We recommend moving to the latest SDK, as this will provide access to the newest features.
