### ISSUE TITLE
Azure Service Bus Topic metric shows incorrect total of Outgoing messages

### ISSUE THREAD

**Issue by MounicaChette** [Azure/azure-service-bus#447]
# Description
I am having a .net core webjob which will be reading messages from an Azure Topic in batches. I have encoutered a weird scenario while observing the metrics of Incoming VS Outgoing messages. Incoming messages was 10k and Outgoing messages were 64k. I have implemented logging to understand , if the webjob is processing the messages multiple times, but surprisingly the webjob was not processing messages more than once. FYI.. we I am using Microsoft.Azure.ServiceBus.Core.MessageReceiver to read messages from azure topic.

## Actual Behavior
1.  Number of Incoming messages is not equal to number of outgoing messages.

## Expected Behavior
1. Number of Incomng messages is equal to number of outgoing messages.

Adding few screen shots of the issue: 
I have tested under a load of 10k messages. So our job is processing only 10k messages, but the metrics for outgoing messages is 64k

![image](https://user-images.githubusercontent.com/16791909/130021149-f0a37a06-02b6-4538-8315-cbd467adba26.png)

![image](https://user-images.githubusercontent.com/16791909/130021360-c534c141-ae73-4016-9e04-2eb1198abc28.png)

Code:
![image](https://user-images.githubusercontent.com/16791909/130067915-a754c9e9-51a1-4c3c-a536-aa2844512e47.png)

**Comment by EldertGrootenboer** [comment]
@shankarsama Can you look into this issue?

**Comment by EldertGrootenboer** [comment]
We have assigned an engineer to look into this issue.

**Comment by viniciostorres** [comment]
We are suffering the same problem here, but the numbers are higher:

![image](https://user-images.githubusercontent.com/1395631/201338213-7a4f2392-ba4e-4b03-a51a-3d189c3a7dea.png)

Using Azure Function trigger to process the subscriptions:
Microsoft.Azure.WebJobs.Extensions.ServiceBus Version="3.2.0"

Is there any direction to understand this numbers?

**Comment by shankarsama** [comment]
Couple of reasons for this:
1. Azure Functions app is configured with prefetch count or receive-batch and function app is slow in processing messages then the messages will be released/redelivered.
2. Messages will be redelivered if messages are abandoned by the client or the message lock is lost due to service side updates.
3. Client locked many messages but restarted before completing those messages.
