### ISSUE TITLE
Same sessionId multiple times when listing sessions

### ISSUE THREAD

**Issue by Magnus12** [Azure/azure-service-bus#458]
# Description
Just upgraded the service bus to Premium. When I list the sessions using the service bus explorer I now see the same sessionID multiple times. Does this mean that messages that belong to the same session are being processed in parallel? (That would be very bad).
Using standard Service bus this did not happen.
![image](https://user-images.githubusercontent.com/12508860/145410233-598e6972-1ef1-4677-b75d-e330a3176e83.png)

## Actual Behavior
1. When I list the session in Service bus explorer I see the same sessionId multiple times.

## Expected Behavior
1. I only expected to see unique session Ids here.

**Comment by EldertGrootenboer** [comment]
This is an implementation of the Service Bus Explorer tool, and not something related to the service itself.

**Comment by SeanFeldman** [comment]
To add to what was said above, an issue could be raised here: https://github.com/paolosalvatori/ServiceBusExplorer/issues/

Also, @Magnus12, if you're interested in quick resolutions, the repo accepts PRs. It would be very appreciated if you could help.
