### ISSUE TITLE
How and when should I unregister message handler for DQL message receiver?

### ISSUE THREAD

**Issue by alex2430lol** [Azure/azure-service-bus#459]
# Description
[.NET Standard](https://github.com/azure/azure-service-bus-dotnet)

When I post a message to Service bus topic, I also register a message handler call back to get future failed messages from Dead letter queue. May I know:
1. How long does the handler callback will exist? 
2. How should I unregister the message handler call back after all current messages in DLQ are received? Can I call MessageReceiver.UnregisterMessageHandlerAsync(TimeSpan) in the finally block?

PostMessageToServiceBus method:
```
var receiver = new MessageReceiver(connectionString, deadLetterPath, ReceiveMode.PeekLock);
receiver.RegisterMessageHandler(
    async (message, cancellationToken) =>
    {
        // Retry posting message to service bus.

        await receiver.CompleteAsync(message.SystemProperties.LockToken);
    },
    new MessageHandlerOptions(e => LogErrorAsync(e.Exception))
    {
      AutoComplete = false,
      MaxConcurrentCalls = 1
     }
);

try
{
    // create a sender and post message to 
}
catch( Exception ex)
{
    // catch ex
}
finally
{
    **_// Can we unregister the handler here?_**
    **receiver.UnregisterMessageHandlerAsync(TimeSpan.FromSeconds(10));**
}
```

- There are many messages in DLQ. When I post a new message and it goes into DLQ, I need to receive all messages and go over them to find the current message I just sent and retry posting it to service bus.
- If I don't unregister the handler, it will receive all messages in DLQ multiple times. It just don't stop.
- If I unregister the handler in finally block, it will only receive the first message in DLQ, which is not what I want.

Here is question: where should I unregister the message handler to make sure receive all messages in DLQ only one time?

**Comment by EldertGrootenboer** [comment]
@alex2430lol Could you explain your scenario more? The behaviour you see is as expected. When you create a DLQ receiver you will receive all its messages, until you unregister it. Normally you would have your DLQ receiver decoupled from your message sender, and not have this in the same logic. Messages ending up in the DLQ indicate an issue on the receiving side as explained [here](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-dead-letter-queues#moving-messages-to-the-dlq), so just resending the message is not recommended.
