### ISSUE TITLE
UnauthorizedAccessException when reading subscription rules with Listen policy

### ISSUE THREAD

**Issue by lukasz-pyrzyk** [Azure/azure-service-bus#462]
# Description

1. An attempt to read current subscription rules (`ServiceBusAdministrationClient.GetRulesAsync(topic, subscription)`) fails with `UnauthorizedAccessException`. 

```
System.UnauthorizedAccessException
Service request failed.
Status: 401 (SubCode=40100: Unauthorized : Unauthorized access for 'EnumerateRules' operation on endpoint 'sb://XYZ.servicebus.windows.net/XYZ/Subscriptions/XYZ/rules?api-version=2021-05&enrich=False&$skip=0&$top=100'. Tracking Id: a580c38a-3a44-4805-b04c-574d54b1ea65_G6)
Headers:
ETag: 636747576710230000
Server: Microsoft-HTTPAPI/2.0
Strict-Transport-Security: REDACTED
Date: Fri, 28 Jan 2022 13:06:17 GMT
Content-Length: 0
```

According to the table in  https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-sas, a `Listen` policy should be enough. Unfortunately, it looks like it needs `Manage` rights.
![image](https://user-images.githubusercontent.com/5083018/151553518-69188ffb-ce60-4e90-956d-0a476643e906.png)

## Actual Behavior
1. I'm not able to read subscription rules with the `Listen` policy

## Expected Behavior
1. `Listen` policy should be enough to read all rules. It's enough to create them and remove them, so it should be possible to read them all as well.
2. This is a breaking change or a bug that doesn't exist in the `Microsoft.Azure.ServiceBus`

Looks similar to the https://github.com/Azure/azure-service-bus/issues/325

**Comment by ramya-rao-a** [comment]
@lukasz-pyrzyk This repo is used for logging service side feature requests and bugs. What you are observing is a client side issue for which we use the repo https://github.com/Azure/azure-sdk-for-net to track bugs and feature requests. I believe https://github.com/Azure/azure-sdk-for-net/issues/25523 is tracking what you are asking for here. Please subscribe to that issue for updates on our progress here. We plan to work on this in the month of February 2022 and have a release in March

**Comment by SeanFeldman** [comment]
I believe this is by design and it is a service-related issue.
ASB service doesn't allow any management-related operations w/o any policy other than `Manage` policy. 

>'Manage' - Confers the right to manage the topology of the namespace, including creating and deleting entities

[source](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-sas#shared-access-authorization-policies)

**Comment by ramya-rao-a** [comment]
@SeanFeldman You are right regarding all the management related operations that are on the [ServiceBusAdministrationClient in Azure.Messaging.ServiceBus](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.administration.servicebusadministrationclient?view=azure-dotnet)(or the [ManagementClient in Microsoft.Azure.ServiceBus](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.servicebus.management.managementclient?view=azure-dotnet)) which implement the calls to the Service Bus HTTP APIs

What we are trying to do in https://github.com/Azure/azure-sdk-for-net/issues/25523 is to support the [rule management operations that are available on AMQP](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-amqp-request-response#rule-operations).

**Comment by SeanFeldman** [comment]
That explains it a bit more.

**Comment by lukasz-pyrzyk** [comment]
Thank you for the response and clarification. I've subscribed to https://github.com/Azure/azure-sdk-for-net/issues/25523 so I think we can close the issue.
