### ISSUE TITLE
System.OperationCanceledException - The operation was canceled

### ISSUE THREAD

**Issue by kbalakumar1** [Azure/azure-service-bus#463]
# Description
I am using an Azure function with has a ServiceBusTrigger and the function uses Microsoft.Azure.WebJobs.Extensions.ServiceBus version 4.1.0. In the app insights, there are a couple of transient and intermittent exceptions as below:

![image](https://user-images.githubusercontent.com/96314696/152617958-1ff1329d-2fc5-4cda-b5db-bf22596b89f0.png)

There doesn't seem to be a problem with the code, but I am not able to figure out the root cause for this exception. Can this exception be caused due to the version of Service Bus package that I am using? Has a fix already been deployed for this in the new versions?

## Actual Behavior
There are multiple exceptions in the app insights:
![image](https://user-images.githubusercontent.com/96314696/152617967-24ba9d91-8505-4563-9946-eed8522f8d67.png)

## Expected Behavior
The ideal expected behavior is not to see any exception messages.

This is a transient intermittent issue which is logged in the Azure app insights in both production and non-production and we don't have the reproduction steps for it.

**Comment by EldertGrootenboer** [comment]
@kbalakumar1 Intermittent exceptions are to be expected and can be come from a variety of causes. However the internal mechanics should catch these and remedy with mechanisms such as retries. Are you getting any impact of these issues?

**Comment by kbalakumar1** [comment]
@EldertGrootenboer : Let me collect more information and circle back to you at the earliest. Thanks for your patience. Really appreciate it.

**Comment by kbalakumar1** [comment]
@EldertGrootenboer : This transient issue doesn't create a big impact on our systems, but it's a little surprising to see them on a function that is running on premium. Although, It would be helpful to know the source of these cancellation messages.

**Comment by EldertGrootenboer** [comment]
@kbalakumar1 As mentioned, there is a variety of causes that can result in this, such as connection drops, service restarts, and more. As most of these are out of our control, we try to make sure that the impact is minimal, by handling them through the internal mechanics. As you mention you don't see impact from these, will you be okay with closing this issue? Of course, if you run into a scenario where this does impact the system, a new issue can always be opened to investigate on that specific scenario.
