### ISSUE TITLE
[FEATURE REQ] Push message to the back of the queue

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-service-bus#464]
# Issue Transfer

This issue has been transferred from the Azure SDK for .NET repository, [#27118](https://github.com/Azure/azure-sdk-for-net/issues/27118).

### Please describe the feature.

When using the ServiceBusReceiver Peek Message there are the follow options

- Abandon (release lock and put back up for processing)
- Complete (Ack off the Queue)
- Dead Letter (Send to the Dead letter sub queue)
- Defer (defer for processing later and don't re appear on the queue)

Ideally when I have a transient failure what I would like is a way to Say "Go to the Back of the Queue" or "Hide on the queue for x Timespan the re appear as an unprocessed message"

At the moment the best option I have is to use a ServiceBusSender to Post the message as a new message onto the Topic (potentially with a delay) which means

- In my Message Pump I need to provide both a sender and receiver
- I need to give my Message pump Permissions to both Send and Receive (instead of just receive)
- All other subscriptions also receive this new delayed message (Which if there is a wider transient issue is going to cause somewhat of a storm (I do limit my max retries via a custom header))

Please let me know what you think, and I am happy to pitch in a write a PR for this (with any guidance) if this is something you would like

**Comment by EldertGrootenboer** [comment]
Thank you for your feedback! Although this is not something that should be done with either Abandon or Defer, as it would change the semantics of those actions, it is something we want to look into putting on the backlog. I would like to align with you for this, to get the details for your scenario. @preardon could you drop me a message on egrootenboer@microsoft.com, and we can take it from there.

**Comment by preardon** [comment]
@EldertGrootenboer I have emailed you as above and look forward to discussing this with you

**Comment by preardon** [comment]
@EldertGrootenboer do we have any updates on thsi?

**Comment by EldertGrootenboer** [comment]
@preardon It is in our backlog, but no updates beyond that yet.

**Comment by EldertGrootenboer** [comment]
This is very similar to the ask in https://github.com/Azure/azure-service-bus/issues/454, we will track progress there, and close this issue to have a single place for communication.
