### ISSUE TITLE
Unable to find root cause for Server Errors

### ISSUE THREAD

**Issue by bartbovendeerdt** [Azure/azure-service-bus#472]
We are having a fair amount of server errors that occur of which we are not able to track down the root cause. There does not seem any impact on application behavior but I would still like to understand if there is something we can do, or how to investigate why they are occurring. I have enabled diagnostic logs but they do not show any exceptions.

Screenshot shows the Completed Messages vs the Server Error sum across last 30 days.

![image](https://user-images.githubusercontent.com/7485108/170027011-df547014-5159-4b44-9f39-fd58f1433d4e.png)

Is there a way to find the root cause?

Example exception (one of many):

``` 
TrackingId:879e550fdd1c4c6b91d00e06baeba1e2_G55
Timestamp:2022-05-24T06:54:33

A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 TrackingId:879e550fdd1c4c6b91d00e06baeba1e2_G55, SystemTracker:gateway7, Timestamp:2022-05-24T06:54:33 
```

similar to [#unable to track server](https://github.com/MicrosoftDocs/azure-docs/issues/60696)

**Comment by shankarsama** [comment]
@bartbovendeerdt Internal Server Errors happen for different reasons (https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-messaging-exceptions#messagingexception). Those are transient most of the time. We recommend you enable retries in your application.

You can enable client side insights to capture all those errors. Please refer to this documentation: https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-end-to-end-tracing?tabs=net-standard-sdk-2

After you capture the errors, please open a Azure Support ticket if those errors happening frequently and disrupting your application’s functionality.
