### ISSUE TITLE
AutoDeleteOnIdle and ForwardTo

### ISSUE THREAD

**Issue by jtaubensee** [Azure/azure-service-bus#5]
# Description
Per @seanfeldman:
We need to update our code documentation to show that we automatically set AutoDeleteOnIdle to the maximum value when you set the ForwardTo. We do this so that there will always be a listener to forward the message (when the property is set). We decided to set this value to the max, rather than throwing an exception, as we didn’t want to break previous customers’ implementation.

**Comment by sethmanheim** [comment]
Filed https://msazure.visualstudio.com/One/_workitems?id=2079421&_a=edit

**Comment by axisc** [comment]
made the doc change to this.
