### ISSUE TITLE
Create a sample that uses SendVia

### ISSUE THREAD

**Issue by binzywu** [Azure/azure-service-bus#50]
# Description
SendVia doesn't have corresponding sample.

## Actual Behavior
N/A 

## Expected Behavior
A sample should be created.

**Comment by SeanFeldman** [comment]
Isn't SendVia covered by the [AtomicTransactions sample](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.ServiceBus.Messaging/AtomicTransactions)?

**Comment by binzywu** [comment]
Yes, it is.
