### ISSUE TITLE
Update samples to Use the release version of library, also make sure it can use latest

### ISSUE THREAD

**Issue by vinaysurya** [Azure/azure-service-bus#54]
Samples are using a preview version of the library. Update the samples to use the release version of the library and when making the change, see if the change can be made such that it always uses the latest version of the library.

**Comment by SeanFeldman** [comment]
Good to close @vinaysurya ?

**Comment by vinaysurya** [comment]
@SeanFeldman , now its good to Close :-)

**Comment by SeanFeldman** [comment]
😃
