### ISSUE TITLE
Queue stopped receiving messages on separate hosts at the same time

### ISSUE THREAD

**Issue by NiklasArbin** [Azure/azure-service-bus#549]
# Description

Our message receiver deployed on multiple host, stopped receiving messages from a specific queue all at the same time. 
AspNet 6.0 docker image on AKS K8s. No excpetions, no logs. This has happened multiple times over the last 24 months, but rarely, once every other month.

Azure.Messaging.ServiceBus  Version="7.7.0" SDK

Azure Support #2206290050000625

## Actual Behavior
1. Stopped processing messages for queue x, queues y and z worked as normal
2. Queue x overflowed capacity

## Expected Behavior
1. Client / Server detects connectivity loss
2.  Reconnects / throws / logs

**Comment by EldertGrootenboer** [comment]
As this is a specific issue to your namespace, which is already being handled by support, we will close this issue. If a new issue needs to be opened, please make sure to include information such as scenario, code, and reproduction steps, so we can better help with these type of issues.
