### ISSUE TITLE
Docs: maximum number of SAS-based rules

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus#55]
[Documentation](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-sas#configuration-for-shared-access-signature-authentication) says:

> A maximum of 12 such rules can be configured on a Service Bus namespace, queue, or topic. Rules that are configured on a Service Bus namespace apply to all entities in that namespace.

Does it mean that 12 rules in total or 12 rules per entity/global?

The sample in the documentation has 6 rules allocated. Does it mean another 6 rules are available and that's it? Or for the namespace another 9 rules are available, for the topic `T1` another 11 rules are available, and for the queue `Q1` another 10 rules can be used? Thank you.

**Comment by SeanFeldman** [comment]
@sethmanheim do you think it would be possible to update the article with clarification?

**Comment by sethmanheim** [comment]
@SeanFeldman I can, but I'd need that information from the engineering team.

**Comment by SeanFeldman** [comment]
I'm sure you folks can hash it out internally 🙂

**Comment by SeanFeldman** [comment]
This issue was a question, asking to clarify the documentation, not an issue with the service. Please reopen and consider updating the documentation link above.

**Comment by EldertGrootenboer** [comment]
We have opened a task for this in our backlog, and will update this issue when we have more information.

**Comment by EldertGrootenboer** [comment]
We have updated the documentation to indicate this is on a per-entity level.
