### ISSUE TITLE
Topic Support Ordering and partition in subscription

### ISSUE THREAD

**Issue by bandishankar** [Azure/azure-service-bus#562]
# Description

My question is more specific to a scenario.
I need my message published to topic and received in subscription in FIFO order .
Now since there is an option in topic "SupportOrdering " .

My question is , **If I make "SupportOrdering" true in topic , and "enable partition" false in subscription . Does this means that my message are delivered in FIFO order as it published in topic.**

**Comment by EldertGrootenboer** [comment]
Correct, if you have a non-partitioned topic, setting [SupportOrdering](https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.administration.topicproperties.supportordering?view=azure-dotnet) to true will ensure that messages are sent to subscriptions in the same order as they came in on the topic. Beware, if you have multiple consumers on a subscription, and you want your messages to be processed in absolute order, you should also have a look at [sessions](https://learn.microsoft.com/en-us/azure/service-bus-messaging/message-sessions).

**Comment by bandishankar** [comment]
@EldertGrootenboer  , I need to do message forwarding from subscription to queue . Since service bus does not allow message forwarding in session enabled subscriptions . So I want to be sure that if I make "SupportOrdering" true in topic and no partition in subscription and use message forwarding to non partitioned queue than I will receive message in FIFO order ?

**Comment by EldertGrootenboer** [comment]
Correct, they will be sent to the queue in order.
