### ISSUE TITLE
Delivery count stuck at 0

### ISSUE THREAD

**Issue by ljammala** [Azure/azure-service-bus#563]
# Description
I am using Azure Servicebus and have registered handlers in my C# code. For one particular message, the message Delivery Count is set as 0 on azure service bus explorer view when I try to do a receive, I am getting a message that "There are no messages to receive". Purging the queue also does not work, because it says there are 0 messages to purge. But I can see that as an active message. Other messages that I send to the queue are being received correctly expect this one message.

## Actual Behavior
1. 
2. 

## Expected Behavior
1. 
2.

**Comment by EldertGrootenboer** [comment]
Can you please open a support ticket for this, as this will give us all the information needed to help troubleshoot this issue.
