### ISSUE TITLE
Could not find any samples with ASP.NET Core

### ISSUE THREAD

**Issue by ahmad-bs** [Azure/azure-service-bus#564]
I'm trying to use ServiceBus in an ASP.NET Core project but I cannot find any "official" sample in this repo or in [this other repo](https://github.com/azure/azure-sdk-for-net/tree/main/sdk/servicebus/Azure.Messaging.ServiceBus/samples). The best sample I could find is [this one](https://damienbod.com/2019/04/23/using-azure-service-bus-queues-with-asp-net-core-services/) and it dates back to 2019 and uses `GetAwaiter().GetResult()` to await the ServiceBusProcessor.

Would you please provide us with a publisher/consumer sample projects ?

**Comment by SeanFeldman** [comment]
All the samples in https://github.com/azure/azure-sdk-for-net/tree/main/sdk/servicebus/Azure.Messaging.ServiceBus/samples are for .NET Core/5/6 and target the latest SDK.

**Comment by ahmad-bs** [comment]
I've seen these samples and they're not targeting ASP.NET Core. I need to see how to register the consumer in the DI container and how to create and configure the Processor at startup and such stuff. 
[This sample](https://github.com/damienbod/AspNetCoreServiceBus/blob/main/AspNetCoreServiceBusApi2/WorkerServiceBus.cs) uses `IHostedService` to host the consumer. Is this the best practice?

Thanks.

**Comment by SeanFeldman** [comment]
This repo is for the server-side (broker) and demonstrates feature usage. If you're looking for ASP.NET as a host example and how to register a processor in the DI container, you are probably looking at asking the question at the repo associated with ASP.NET. `IHostedService` is a fine solution if you run ASP.NET and need to process messages using a hosted service.

**Comment by EldertGrootenboer** [comment]
As mentioned by Sean, this sounds more like an ASP.NET specific ask, so we would recommend asking there, as they will be better suited to handle these types of questions.
