### ISSUE TITLE
Docs: client/version selection is confusing

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus#57]
This is very confusing as there's only 1 option in the client drop down,
![image](https://user-images.githubusercontent.com/1309622/28840440-2bf64a52-76b4-11e7-86fb-665257aaf017.png)

 but versions (not the latest) that belong to both.

![image](https://user-images.githubusercontent.com/1309622/28840355-f3cdf4c2-76b3-11e7-98fe-5efc8411990c.png)

**Comment by sethmanheim** [comment]
Thank you @SeanFeldman, I think we do have a problem here. I have the right folks looking into this...

**Comment by sethmanheim** [comment]
Turns out the version picker is designed to show that a type/namespace/member is available in more than one place, which is not the case here.

**Comment by SeanFeldman** [comment]
@sethmanheim please convey to whoever works on this selector that UX is completely broken.
First, it's not clear what it's supposed to do. Hence this issue 🙂 
Second, what's selected is the client / version, not a framework.
Third, it's not intuitive because only old client is showed, yet versions are for old and the new client.

Hopefully this feedback helps.

**Comment by sethmanheim** [comment]
@SeanFeldman Yes it is very helpful. I do have people working on it -- it's still not quite right.
