### ISSUE TITLE
Portal: SAS policy with no permissions creation freezes and never completes

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus#59]
Steps to repro:

**1**

![image](https://user-images.githubusercontent.com/1309622/28849936-cf778e12-76d6-11e7-882e-f345829b47dc.png)

**2**

![image](https://user-images.githubusercontent.com/1309622/28849951-e1a921d6-76d6-11e7-84c0-81dbabf9f1aa.png)

**3**

![image](https://user-images.githubusercontent.com/1309622/28849960-f3f7d0da-76d6-11e7-8340-03acef8590ae.png)

**4**

![image](https://user-images.githubusercontent.com/1309622/28849974-0cfbc712-76d7-11e7-9341-8a94d5b7c699.png)

Never completes. 
If refreshed, nothing appears to be created or running.

![image](https://user-images.githubusercontent.com/1309622/28849991-3015847c-76d7-11e7-87e6-8f2e4c014948.png)

![image](https://user-images.githubusercontent.com/1309622/28850018-4d8357fa-76d7-11e7-97c8-b88a76d22b3b.png)

**Comment by EldertGrootenboer** [comment]
If this issue still occurs, please let us know and we can re-open the issue.
