### ISSUE TITLE
Increase the length of topic names

### ISSUE THREAD

**Issue by aanttila** [Azure/azure-service-bus#6]
Topic names are currently limited to 50 characters, which causes issues when using client frameworks like NServiceBus.  While this can be addressed by the NServiceBus team by generating a hash or a deterministic GUID, both of those options result in unfriendly topic names.  Therefore, I would prefer to have the current 50 character restriction on topic names increased.

I've had this issue in the past, and based on the links below, it seems that others are having similar problems.

[https://feedback.azure.com/forums/216926-service-bus/suggestions/18552391-increase-the-maximum-length-of-the-name-of-a-topic](https://feedback.azure.com/forums/216926-service-bus/suggestions/18552391-increase-the-maximum-length-of-the-name-of-a-topic)

[https://github.com/Particular/NServiceBus.Azure/issues/19#issuecomment-285057088](https://github.com/Particular/NServiceBus.Azure/issues/19#issuecomment-285057088)

**Comment by axisc** [comment]
closing this because it's a duplicate. will track #257
