### ISSUE TITLE
Native GeoDR for data plane

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus#646]
This is a feature request for GeoDR for **data** plane.

Currently, the only recovered aspect is the control panel. This means, in production, entities are recovered but not the messages. While the system can continue working, the loss of messages is a significant business and operational impact, potentially leading to disastrous state of systems.

While possible a are [documented](https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-federation-overview) it is not the same as the native data plane GeoDR.

**Comment by EldertGrootenboer** [comment]
We are currently working on a full GeoDR feature, which will include full replication of the namespace, including message data. There is no specific timelines to share yet, but will keep this issue updated as we go forward.

**Comment by EldertGrootenboer** [comment]
We are currently working on a new GeoDR feature, where this will be taken into account. The current planning is to bring this in public preview in the first half of 2024.

**Comment by EldertGrootenboer** [comment]
We are currently doing active development on this feature, and expect to have more to share around its release in the next couple of weeks.

**Comment by EldertGrootenboer** [comment]
We have recently released a new Geo-Replication feature, which addresses this. The Geo-Replication feature implements metadata and data replication in a primary-secondary replication model. It works with a single namespace, and at a given time there’s only one primary region, which is serving both producers and consumers. There is a single hostname used to connect to the namespace, which always points to the current primary region. After promoting a secondary region, the hostname points to the new primary region, and the old primary region is demoted to secondary region. After the new secondary has been re-initialized, it is possible to promote this region again to primary at any moment. There are two replication modes, synchronous and asynchronous. For more information, check the [announcement](https://techcommunity.microsoft.com/t5/messaging-on-azure-blog/announcing-public-preview-of-geo-replication-for-azure-service/bc-p/4184203#M278) and the [documentation](https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-geo-replication).

**Comment by mario-d-s** [comment]
@EldertGrootenboer currently, this new Geo-Replication feature is only supported on **new** namespaces. Would it be possible to tell us if the plan is to support it on **existing** namespaces once the feature is promoted to General Availability?

**Comment by EldertGrootenboer** [comment]
> [@EldertGrootenboer](https://github.com/EldertGrootenboer) currently, this new Geo-Replication feature is only supported on **new** namespaces. Would it be possible to tell us if the plan is to support it on **existing** namespaces once the feature is promoted to General Availability?

Yes, existing namespaces will be supported.
