### ISSUE TITLE
How does sessionId map to partitions

### ISSUE THREAD

**Issue by jfloodnet** [Azure/azure-service-bus#65]
Hi,

I know that this is a general service bus question, but I can't find this information anywhere, and I have a feeling you will know.

I want to ensure that my sessions are evenly distributed across partitions in service bus. We currently have messages that are being sent with a sessionId set to id.ToString() where Id is an integer. However, I am wondering, if this would be sufficient to distribute sessions well enough. As far as I can tell, there's no way to confirm how sessions are being distributed, so have no way to test this.

I can see in this sample that you are prefixing the session Ids with "session" https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/BasicSessionSendReceiveUsingQueueClient

Is this something coincidental to my question? Or is this something I should do If my sessionId will be derived from an integer?

Thanks,

**Comment by SeanFeldman** [comment]
@jfloodnet this would be a great question to be posted on [StackOverlow](https://stackoverflow.com/questions/tagged/azureservicebus).

**Comment by jfloodnet** [comment]
You're right.. sorry thanks

**Comment by jfloodnet** [comment]
done -> https://stackoverflow.com/questions/45582763/how-does-sessionid-map-to-partitions
