### ISSUE TITLE
Negative Scheduled Message Count

### ISSUE THREAD

**Issue by fil-at-werma** [Azure/azure-service-bus#653]
# Description

During research I found this closed Issue, that should have fixed this:
https://github.com/Azure/azure-service-bus/issues/254 

But nontheless, we are encountering a Scheduled Message Count of "-1".
It never goes below -1 (as far as we could see).

UPDATE 2023-05-26 : Meanwhile, we did have observed values below -1.

What we do is schedule a message for delayed delivery: 
```
var sequenceNumber = await _serviceBusSender.ScheduleMessageAsync(messageToSchedule, scheduledEnqueueDateTime, cancellationToken);
```
Where the delay is < 24h and > 0.

If a state in the system changes before that delay is up, we cancel the message by their sequenceNumber:

```
await _serviceBusSender.CancelScheduledMessageAsync(sequenceNumber, cancellationToken);
```

## Actual Behavior
"Scheduled Message Count" shows "-1" Messages.

![grafik](https://user-images.githubusercontent.com/81744889/216289997-69dd8fb0-1937-4296-b2ca-f8d0e81d0137.png)

## Expected Behavior
"Scheduled Message Count" shows at least "0" Messages.

We are on .Net 6.0, using Azure.Messaging.ServiceBus 7.10.0
Pricing Tier is Standard

**Comment by EldertGrootenboer** [comment]
We have opened an investigation task for this in our backlog, and will update this issue when we have more information.

**Comment by perfectphase** [comment]
Just to add, the issue is still there and not limited to showing -1

![image](https://user-images.githubusercontent.com/2489508/225584294-4cefc85d-7165-4933-a56a-6f7950d7e0f9.png)

For me this happened when we used the too Queue Explorer to move schedule messages back to the queue at the same time azure tired to move them back.

**Comment by JSCProjects** [comment]
This is also happening within our subscriptions. Our sagas depend on scheduled messages and our ops team is complaining that they can't rely on this number.

**Comment by anth12** [comment]
I'm seeing this when cancelling scheduled messages.

When a message is scheduled and once the scheduled message is cancelled, the `scheduledMessageCount` is accurate. However, when cancelling the message expiration date has passed, the `scheduledMessageCount` goes to a negative value with the cancelled message becoming active.

**Comment by EldertGrootenboer** [comment]
We have recently released a fix which should address this. If this does happen again in the future, please open a support case, as that will provide us with the information needed to troubleshoot this further.

**Comment by jrgcubano** [comment]
@EldertGrootenboer Hello. Where is the fix? Client library or do you mean on Azure side?

**Comment by EldertGrootenboer** [comment]
This has been implemented on the service side. If you still see this behavior, please open a support ticket, with all the details about your namespace, so this can be investigated further.

**Comment by RickGarnerBHR** [comment]
Us too - also used QueueExplorer to purge scheduled messages. Have raised a support ticket 2602120050003944
