### ISSUE TITLE
AutoDelete logs do not contain subscription and topic information

### ISSUE THREAD

**Issue by dldldlepl** [Azure/azure-service-bus#654]
# Description
The azure diagnostic logs with EventName_s "AutoDelete Delete Subscription" do not contain an information about the deleted subscription and on which topic this subscription was.

The column "_ResourceId" which should contain this information contains only the full namespace id.

## Actual Behavior
1. Diagnostic Logs need to be enabled
2. Have a subscription in a topic which was automatically deleted by the service bus
3. In the logs you can see that the event log for EventName_s = AutoDelete Delete Subscription does not contain any information about what was deleted.

## Expected Behavior
3. The log should contain information about what has been deleted. Knowing that something has been deleted but not knowing what is not very helpful. According to the documentation _ResourceId should contain this information.

https://learn.microsoft.com/en-us/azure/service-bus-messaging/monitor-service-bus#sample-kusto-queries

**Comment by EldertGrootenboer** [comment]
We have opened an investigation task for this in our backlog, and will update this issue when we have more information.

**Comment by EldertGrootenboer** [comment]
The work for this has been done, and will roll out within the next couple of weeks. Closing this issue as completed.

**Comment by dldldlepl** [comment]
@EldertGrootenboer I would have assumed that after 13 weeks the fix would have been rolled out, but I still can not find any information about the Topic or Subscription which has been automatically deleted in the logs.
