### ISSUE TITLE
Inquiry on Transactional Request-Response over AMQP

### ISSUE THREAD

**Issue by minghuaw** [Azure/azure-service-bus#657]
# Description

There currently is no official protocol that defines how transaction works on an AMQP management link (ie. the request-response link). What is the frame exchange model that Service Bus uses for transactional request-response operations?

I have taken a look at the .net sdk where it seems like it is composed of a transactional posting on the sender and then a non-transactional receive on the receiver. However, the disposition frame sent back by Service Bus after the transactional posting message transfer does not seem to be compliant to the AMQP core spec.

## Actual Behavior

1. A `Disposition` frame carried a non-transactional delivery state. For example

```
Transaction Controller                  Transactional Resource
===============================================================================

TRANSFER(handle=1,           --------->
         delivery-id=1,
         state=
           TransactionalState(
             txn-id=0) )
{ ... payload ... }

                             <--------- DISPOSITION(first=1, last=1, state=Accepted())
-------------------------------------------------------------------------------
```

## Expected Behavior

1. The disposition frame, to my understanding, should carry a transactional delivery state as the quote below is stated in the [core spec](http://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-transactions-v1.0-os.html#section-txn-work)

> When traveling in the other direction, from resource to controller, the [transfer](http://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-transport-v1.0-os.html#type-transfer) and [disposition](http://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-transport-v1.0-os.html#type-disposition) frames indicate work performed, and the txn-ids included MUST correctly indicate with which (if any) transaction this work is associated.

So I was expecting the following

```
Transaction Controller                  Transactional Resource
===============================================================================

TRANSFER(handle=1,           --------->
         delivery-id=1,
         state=
           TransactionalState(
             txn-id=0) )
{ ... payload ... }

                             <--------- DISPOSITION(first=1, last=1,
                                                    state=TransactionalState(
                                                            txn-id=0,
                                                            outcome=Accepted())
                                                   )
-------------------------------------------------------------------------------
```

**Comment by yvgopal** [comment]
Request-Response link is not part of the official AMQP spec. So it currently doesn't participate in transactions. And we don't have any plans of adding that support.
As far as discrepancies w.r.t the spec itself in the current implementation, we will track this item and see what we can do about it.

**Comment by minghuaw** [comment]
@yvgopal Can you verify that the disposition indeed carries a transactional state as defined in the spec (http://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-transactions-v1.0-os.html#type-transactional-state)? I don't remember what exactly was received given that this issue has been over 6 months, but I think what happened was that a non-transactional state was sent instead of transactional state
