### ISSUE TITLE
Feature: message counts on entity list page in the Portal

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus#663]
# Description

When inspecting a namespace with multiple entities, having an idea about number of active and dead-lettered messages helps perform tasks quicker. Consider adding an option to reflect message counts while allowing to chose what counts to show. As of today, the portal shows nothing.

<img width="933" alt="image" src="https://github.com/Azure/azure-service-bus/assets/1309622/caf46718-c8de-4da5-b633-83781cd3afbf">

**Comment by EldertGrootenboer** [comment]
Thank you for suggesting this feature. The work for this has been done, you will now see counts on the overview for the total number of messages, the number active messages, and the number of dead-lettered messages in an entity. Closing this issue as completed.
