### ISSUE TITLE
startswith in filter expression returns bad request

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-service-bus#667]
# Issue Transfer

This issue has been transferred from the Azure SDK for .NET repository, [#18786](https://github.com/Azure/azure-sdk-for-net/issues/18786).

## Details

The example filter shown causes the service bus to return "(400) Bad Request. Invalid Filter. StartsWith is not allowed in the filter expression"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3dc0f0b-ef56-7ffd-a0a4-70ec75ac8c30
* Version Independent ID: 125cff6f-a5ec-b488-3b82-907e0aff1834
* Content: [NamespaceManager.GetSubscriptions Method (Microsoft.ServiceBus)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.namespacemanager.getsubscriptions?view=azure-dotnet)
* Content Source: [xml/Microsoft.ServiceBus/NamespaceManager.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.ServiceBus/NamespaceManager.xml)
* Service: **service-bus**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by EldertGrootenboer** [comment]
This documentation gets generated from the live sources, and as such would require creating a new version of the package. We don't make any non-critical changes to this package anymore, instead we advice to move to the [latest Service Bus SDK](https://www.nuget.org/packages/Azure.Messaging.ServiceBus/).
