### ISSUE TITLE
Feature request: configuration-aware filters

### ISSUE THREAD

**Issue by TWolversonReply** [Azure/azure-service-bus#679]
# Description
It would be great if subscription filters could be made aware of configuration as with the integration of App Configuration Service with dotnet configuration providers. When developing cloud-native applications, I can use App Configuration to feature flag particular functionality that is not ready for users. What I can't do is stop the flow of messages to particular consumers using the same solution-wide configuration store that App Configuration provides. To 'switch on' broadcast of messages to a new subscriber on a particular date, I need to manually edit the filter criteria to match my desired subset of messages; I can't set this up to activate at a future time from the same configuration UI that I use for the rest of my application.

## Actual Behavior
1. SQL filter criteria for subscriptions are local to the subscription and can be edited, but are static and cannot react to any external configuration changes
2. 

## Expected Behavior
1. SQL filters to be able to use values loaded from configuration to be able to pass or not-pass messages, perhaps using %wildcard% syntax
2.

**Comment by SeanFeldman** [comment]
I understand the desire, but the use would be problematic. A SQL filter is processed by the broker and needs to be provisioned, and shouldn't change too often. If it does, it's an application/system concern, not the broker.

**Comment by EldertGrootenboer** [comment]
Thank you for suggesting this feature. However, we are not considering implementing this. As explained by Sean, SQL filter are processed by the broker and needs to be provisioned, which we cannot do dynamically.
