### ISSUE TITLE
Azure Service Bus is sending messages very slowly, resulting in a message being delivered when the message lock has already expired. 

### ISSUE THREAD

**Issue by s17b2-voroneckij** [Azure/azure-service-bus#681]
# Description
When I am using an Azure Service Bus queue deployed in UK South region and try to deliver large messages over the queue (of size 17 MB and more), the delivery of the message to a VM or my dev laptop in Middle East takes a very long time (more than a minute). As a result, by the time a message is received, the lock has already expired and removing the message from the queue or dead-lettering or deferring it is impossible. 
The issue can be reproduced with Azure Python SDK, Azure Java SDK, and the JMS-compliant Java client, so it is not SDK-related. 

## Actual Behavior
1. Receiving a message of size 17Mb or higher takes over a minute
2. This results in lock being expired by the time I attempt to complete a message. 

## Expected Behavior
1. ASB should be delivering messages of such size in seconds, not minutes.
3. Ideally, in such cases, there should be a way for a client to do something in such a situation.

I understand that this issue can be partly solved by increasing lock timeout, but this doesn`t in any way solve the situation of messages taking very long to be delivered. 
Somehow, at least with Python SDK, the issue is partly solved when AMQP is used over websockets - messages are delivered faster. 
The VMs in question for testing were created by me in Azure UAE region and AWS Bahrain region. 

Please see related issues in the SDKs issue that have code examples and some discussions: https://github.com/Azure/azure-sdk-for-java/issues/37497#issuecomment-1795169054
https://github.com/Azure/azure-sdk-for-python/issues/32943#issuecomment-1792600249

**Comment by EldertGrootenboer** [comment]
Please open a support ticket for this, as this will give us all the information needed to help troubleshoot this issue.

**Comment by s17b2-voroneckij** [comment]
@EldertGrootenboer, I am afraid that I am not able to create a support ticket for this as I don`t have the required level of support in Azure. 
Or do you mean some other form of support tickets?

**Comment by EldertGrootenboer** [comment]
@s17b2-voroneckij If you don't have any level of support, you can first try going through [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/tags/73/azure-service-bus?orderby=createdat).
