### ISSUE TITLE
Overflowing queue takes down the entire namespace

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus#683]
# Description

When a single queue exceeds its maximum size, any attempt to send another message queue will result in exception.

```
The maximum entity size has been reached or exceeded for 
Queue: '<namespace>:<entity>:<name>'. Size of entity in bytes:5368728747, 
Max entity size in bytes: 5368709120. 
For more information please see https://aka.ms/ServiceBusExceptions .  
QuotaType: EntitySize Reference:85752742-6758-42be-8079-1f3963762236, TrackingId:011eb4e10000001d087f55d5656249a6_Gxx_Bxx, SystemTracker:xxxx, Timestamp:xxxx (QuotaExceeded). 

For troubleshooting information, see https://aka.ms/azsdk/net/servicebus/exceptions/troubleshoot.
```

In addition to that, the namespace is rendered unusable.

## Expected Behavior

At minimum, the namespace should be still usable despite a single queue reaching its maximum.

Ideally, the namespace should have a total size quota, shared among the entities. So if there are 10 queues and each is 5GB, the namespace quota to be 25GB. And if a single queue goes beyond the size but the overall size is less than the namespace size, avoid `QuotaExceeded` exceptions that potentially lead to production outages.

**Comment by EldertGrootenboer** [comment]
Thank you for your feedback. We have opened an investigation task for this in our backlog, and will update this issue when we have more information.

**Comment by yvgopal** [comment]
@SeanFeldman That is not expected. Is that premium or standard namespace? This is a service side issue. It would be good if you can create a support ticket with the details. If you can't create a ticket, please provide the namespace name, queue name and the time the issue occurred.

**Comment by SeanFeldman** [comment]
@yvgopal, this was a standard namespace. I'll refer a client of mine to this issue and ask them to raise a support case referencing this issue.

**Comment by EldertGrootenboer** [comment]
Closing this issue, as it was a specific instance of this issue which should be tracked through a support request.
