### ISSUE TITLE
Review how Peek is working

### ISSUE THREAD

**Issue by jtaubensee** [Azure/azure-service-bus#7]
_From @SeanFeldman on February 23, 2017 6:38_

There are 3 types of messages that can be found on a queue
1. Ready for processing
2. Delayed (`ScheduleEnqueueTimeUtc` set in future)
3. Deferred (only can be received by `SequenceNumber`)

When messages are enqueued in the future, they cannot be received.
When messages are peeked, future messages are fully returned (headers & body).
For scenarios when there are many future messages, peek becomes too heavy of an operation.

When peeking for messages, I should be able to choose what am I interested in. If I need to evaluate all, then current behavior is fine. But otherwise, I'm not sure the current behavior is good. 

**Question**: Should the default behavior be only to return what's ready for processing?

An override could then return what's ready for processing and enqueued for the future.

Note: this potentially might require some changed on the broker side. I'll raise a separate issue for that.

_Copied from original issue: Azure/azure-service-bus-dotnet#89_

**Comment by jtaubensee** [comment]
Hey Sean - I think the default behavior is probably correct. In most cases, users just want the next message that is available for processing, and that's also what we recommend. I realize that there are other types of messages that can be stored (deferred or scheduled), but it is costly for us to return messages by the SequenceId. We are essentially doing a scan of a table for that, which does have performance implications.

Can you be more specific in what you are asking? Are you suggesting a peek mode for different types of messages?

**Comment by jtaubensee** [comment]
_From @SeanFeldman on March 10, 2017 4:36_

>  Are you suggesting a peek mode for different types of messages?

That is correct. jtaubensee. An ability to peek for messages w/o deffered and scheduled in the future messages coming back.

**Comment by jtaubensee** [comment]
_From @SeanFeldman on March 10, 2017 4:37_

I wonder if this should be raised in https://github.com/Azure/azure-service-bus/ as well to have the support on the server side.

**Comment by stefanmoser** [comment]
I'd like to add my thoughts here because we were just bitten by this too. The problem to me is that `Peek` and `Receive` differ not only by _how_ the returned message is treated, but they also differ in _what messages_ will be returned at all. `Receive` will not return a message that has been scheduled for future delivery, but `Peek` will. This functionality makes `Peek` very costly and difficult to use if there are many future scheduled messages on the queue.

I believe that `Peek` and `Receive` should both return the same set of messages.
