### ISSUE TITLE
Azure Service Bus - Topic - Standard SKU - Networking issues

### ISSUE THREAD

**Issue by jonmikeli** [Azure/azure-service-bus#709]
Context:
   - Azure Service Bus Namespace
   - Azure Topics
   - Standard SKU
   - Location: North Europe
   - Azure Service Bus created through Bicep or manually (same behavior)
 - Azure Portal: Networking menu not available (I do not know if this is the normal behavior with the Standard SKU)
 - Local authentication: enabled

## Actual Behavior
1. Go to a Topic
2. Open the Service Bus Explorer (Azure Portal)
3. Error: "This namespace has public network access disabled ......" (see screenshot)
![image](https://github.com/Azure/azure-service-bus/assets/22737122/5030cd39-2002-40c6-98fd-ad42951c2dc9)

No way to change the Networking settings from the Azure Portal (the menu is not available).

![image](https://github.com/Azure/azure-service-bus/assets/22737122/7799b263-f412-4002-9e44-5d7f081f4e3b)

## Expected Behavior
1. Go to a Topic
2. Open the Service Bus Explorer (Azure Portal)
3. Be allowed to consume or generate messages since networking is only available for the Premium SKU (the Standard SKU is expected to be "public").

**Comment by EldertGrootenboer** [comment]
Virtual networks are only available for Service Bus Premium, however the other SKUs do allow for other networking restrrictions, as described at https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-ip-filtering#important-points. We are aware that currently there is no network blade for these other SKUs, this is something that we will work on in the future.
