### ISSUE TITLE
Scheduling a large number of messages for the same time overloads the queue and causes throttling

### ISSUE THREAD

**Issue by ericleigh007** [Azure/azure-service-bus#715]
# Description

## Actual Behavior
1.   one user, or several users of the queue schedule messages for specific time (let's say the time a store should start processing orders)
2.  Service bus releases all the scheduled messages at the same instant, seems to do no throttling itself, and then causes any other user send attempts to throttle.

![image](https://github.com/user-attachments/assets/6711c0e3-8136-4b02-9bd5-14aeed47b267)

## Expected Behavior
1.   Users all schedule messages for the same instant.
2.  Service bus releases the messages, but does so in a manner that prevents the queue from overloading, so that user send attempts don't have to throttle 

Now we will have to work around this behavior by spreading the times out, but in the case of many different senders, this is only a guessing game, which might have to rely on the entropy of a random number generator to spread messages out. What's more the senders might all have to be aware of each other's operation, which somewhat breaks some isolatoin cloud principles that are reasons to use the Service Bus in the first place.

**Comment by EldertGrootenboer** [comment]
This is expected behavior, when you schedule a large number of messages that all become available at the same time, our background job then picks up all these messages, and makes them active? That said, for the standard SKU scheduling messages from our background does not consume credits, and would not cause throttling for activation.

**Comment by SeanFeldman** [comment]
@eldert, are you saying a maximum number of messages can transition from the scheduled state to the active state simultaneously? What's the number, and where can I find the documentation? Thank you.

**Comment by ericleigh007** [comment]
Sorry I didn't indicate that this premium service bus.
I also must disagree with the assertion that Service Bus does not throttle based on this happening.  We can see the memory and CPU peak out before our Service Bus scale up rules took hold.  The throttling then ensued, so that our user code in azure functions couldn't send any messages on the queues.

This seemed to be a problem, at least for the default timeout/retry policy of the SDK, to cope with.   Of course, we didn't lose any data, because it wasn't committed to the queue, but our system is event driven, so data comes from a change feed that won't "trigger" again unless "primed" again, therefore the failure to commit to the queue did cause extreme angst by our customer.

We've since changed the code to spread the schedules out, but, as I mentioned, this kind of operation will interfere with non-cooperating apps that might want to send messages to the queue by scheduling, when they don't have any knowledge of each other's operation.

I think it is worth taking a bit of a closer look at, and not immediately saying "yeah, it works that way, but it doesn't cause any problems."

I would expect a deeper, more technically detailed conversation about such things, as they are the kinds of things that surprise customers -- and not in a good way.

-thanks
