### ISSUE TITLE
Help: Understanding the Network Security provided by Azure

### ISSUE THREAD

**Issue by m-amaresh** [Azure/azure-service-bus#718]
For a client discussion I need to understand the Network Security provided by Azure for service bus, I am unable to find relevant document/information in internet, It will be very helpful if you can redirect me to some of the official references.

When we deploy a service bus namespace with public network access enabled we get an URL like `my-servicebus-namespace.servicebus.windows.net`.
How secure is this URL, Does it protect against DDOS attack? How Azure handles the security of the URL (apart form authentication) Does it protect against OWASP

Of course we can have private endpoints, IP filtering etc.

I am inclined to use a Application Gateway with WAF V2 in-front of all my Azure service bus, event hub etc. which I need to make available over public internet. If you can help me understand the base security offered by Azure and point me to right reference documentation it will be very helpful.

**Comment by EldertGrootenboer** [comment]
Azure Service Bus, and Azure in general, is covered by a extensive set of security certifications as shown on [Azure compliance documentation](https://learn.microsoft.com/en-us/azure/compliance/). Azure Service Bus has their own endpoints, firewall, and network integration, and is subject to same standards as the application firewall service, which is, as the name suggests, for applications and not for Azure provided services.

I would recommend going through the [Azure security baseline for Service Bus](https://learn.microsoft.com/en-us/security/benchmark/azure/baselines/service-bus-security-baseline) to understand how you can further secure your Service Bus instances. For network specific security, you can check [Network security for Azure Service Bus](https://learn.microsoft.com/en-us/azure/service-bus-messaging/network-security).
