### ISSUE TITLE
Queue client  need receives messages continuously

### ISSUE THREAD

**Issue by meomeo0110** [Azure/azure-service-bus#75]
Hi everyone;

I registered a IMessageHandler for Queue like that:  
`queueClient.registerMessageHandler(new MessageHandler(), new MessageHandlerOptions(1, true, 5min))`. 
I try to send some messages to queue. The receiver only worked in the first message. On next message, the connection seem to be closed and the queue client could not receive message anymore.

I also try to re-register after processed message but it;s thew AlreadyRegisteredException. 
Do I need create new QueueClient for every message or set a high value to maxConcurrentCalls of MessageHandlerOptions?

My expectation is: A QueueClient instance observers a queue and start processing when new message arrive.

Thanks

**Comment by SeanFeldman** [comment]
That a correct expectation.

Could you share your code or provide a repro to see what's happening?

**Comment by meomeo0110** [comment]
Here is Push to queue application:

I upload 2 application: PullApp and PushApp. I used PushApp to send many message but there is only 1 received message.
Here my code: https://goo.gl/2ujEe5.

Thanks.

**Comment by SeanFeldman** [comment]
When you register a handler, it's running as a different thread. Your main application should not end. If it does (like in the sample), handler will be terminated. Which explains the behavior you see. Put a console readline equivalent in Java after handler is registered to see all messages arrive.

**Comment by nemakam** [comment]
Closing this issue. If this is not resolved with the above solution, please open a new issue in the java repo (https://github.com/Azure/azure-service-bus-java) and link to this issue for context.

**Comment by meomeo0110** [comment]
Thanks all;

I find the solution:
I use: ` return CompletableFuture.supplyAsync(() -> {...})` instead of ` {...} ; return new CompletableFuture<>()` in IMessageHandler.onMessageAsync(). Then the QueueClient can receives messages continuously

This problem seem is using blocking code in non-blocking code. I'm not sure about it.
