### ISSUE TITLE
Exception when receive message in PeekLock. "Delivery not found on the receive link."

### ISSUE THREAD

**Issue by meomeo0110** [Azure/azure-service-bus#77]
Hi everyone;

I followed the code in the example. Created QueueClient in PeekLock mode and implemented IMessageHandler:
`new QueueClient(new ConnectionStringBuilder("host", "queueName"), ReceiveMode.PEEKLOCK)`
`onMessageAsync(IMessage iMessage) {return queueClient.complete(UUIDToken);}`

The queueClient can receive messages but it always throws exception: 
**Delivery not found for delivery tag. Receive link to 'queueName' closed with a transient error and reopened
Completing message with sequence number '{number}' failed
java.lang.IllegalArgumentException: Delivery not found on the receive link.**

Can you explain why situation happen?

**Comment by SeanFeldman** [comment]
@meomeo0110 as this is a Java client related question, wouldn't it better to ask in https://github.com/Azure/azure-service-bus-java/issues ?

**Comment by meomeo0110** [comment]
Thanks SeanFeldman ;

I did not notice it. I close and move this issue.
