### ISSUE TITLE
Azure Service Bus message retry on TaskCancelationException

### ISSUE THREAD

**Issue by PiotrTecza** [Azure/azure-service-bus#83]
# Description
I'm using QueueClient message pump with AutoComplete option. When there is an exception thrown from the callback the message is retried and finally deadlettered.

Unfortunately when TaskCancelationException or OperationCanceledException is thrown from the callback this is not the case. The message gets autocompleted and never retried. Also OptionsOnExceptionReceived event handler is not called.

`_queueClient = QueueClient.CreateFromConnectionString(connectionString, queueName, ReceiveMode.PeekLock);`
...
`
var options = new OnMessageOptions
{
  MaxConcurrentCalls = _maxConcurrentCalls,
  AutoRenewTimeout = TimeSpan.FromMinutes(_autoRenewTimeoutInMinutes),
  AutoComplete = true
};
`
`
options.ExceptionReceived += OptionsOnExceptionReceived;
`
`_queueClient.OnMessageAsync(callback, options);
`

## Actual Behavior
1. Message is completed when TaskCancelationException or OperationCanceledException is thrown from the callback
2. Message is retried when any other exception is thrown from the callback

## Expected Behavior
1. Message is retried when any exception is thrown from the callback

**Comment by ChristianWolf42** [comment]
We will take a look and get back
