### ISSUE TITLE
Disabled Azure Service Bus Topic Subscription is receiving messages. Is it a bug?

### ISSUE THREAD

**Issue by gmantri** [Azure/azure-service-bus#84]
It is my understanding that if a `Subscription` in an Azure Service Bus `Topic` is disabled, it shouldn't receive any messages sent to the topic. I can vouch that I have seen this functionality working properly.

However today I am noticing a weird behavior. What I am noticing is that even if I send a message to a topic, it is getting delivered to disabled subscriptions as well.

Using Service Bus Explorer (4.0.103), I created a topic and then I created 3 subscriptions in there. All 3 subscriptions have True SQL Filter rule (no other rules). I then disabled one of the subscription. When I send a message to the topic, I am noticing that active messages count is getting increased in all 3 subscriptions. It should have increased in only 2 subscriptions.

Is it a bug at the service level or am I misunderstanding the functionality?

**Comment by SeanFeldman** [comment]
If a queue is disabled, a message won't be delivered to it.
If a topic is disabled, should behave in a similar way.
Feels like a 🐛

**Comment by gmantri** [comment]
Thanks Sean. I would appreciate if you can try to reproduce it on your end so that I know I am not losing my mind :)

**Comment by SeanFeldman** [comment]
Reproduced on my end using the same setup.

**Comment by binzywu** [comment]
Nope, it is currently the current behavior. For subscription, it can only be disabled for receive (disable will be same effect). The messages still will be pumped into subscription. If you want the subscription stop receiving messages, then add a false filter to it is the way to go.

**Comment by gmantri** [comment]
@binzywu ... Thanks! As I said in my original thread, I can vouch that this was **not** the behavior a few weeks ago. If I disable a subscription, then that subscription stops receiving messages. Can you please confirm that it has been like this always? For the sake of argument, let's assume that it has been like this always. Then, can you explain what purpose does "Disabling" a subscription does?

**Comment by SeanFeldman** [comment]
I'm operating in a different mode, so when someone "unsubscribes", a subscription is physically removed.
Saying that, I agree with @gmantri that inconsistent behavior between entity disabling outcome is very confusing and feels like a wrong behavior 🙂

**Comment by binzywu** [comment]
@gmantri actually it is always the behavior. I have been telling people the same answer for the past few years. 

Let me see whether we can put some document around this.

**Comment by SeanFeldman** [comment]
@binzywu the difference is that now it's publicly available on GitHub 😃 
If this behavior is to stay, can I suggest to label it as [`documentation`](https://github.com/Azure/azure-service-bus/issues?q=is%3Aissue+is%3Aopen+label%3Adocumentation) and add to the doco?

**Comment by sethmanheim** [comment]
Filed PG bug 2110704. Would be good to add this note to the Disabled field of EntityStatus: https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.entitystatus?view=azure-dotnet.

**Comment by SeanFeldman** [comment]
If it's a bug, it shouldn't be added to the doco, but rather fixed.
Otherwise, agreed.

**Comment by sethmanheim** [comment]
@SeanFeldman One question that's been bugging me. What is a "doco"? :-)

**Comment by SeanFeldman** [comment]
My bad. "Doco" Aussie version for "documentation" that I picked up by working with some. Doc-o 😃

**Comment by sethmanheim** [comment]
Haha good one! :-)

**Comment by taylora3** [comment]
Has this been confirmed. Is this a bug or a feature? The way that it currently works is how I want it to work e.g when the subscription is disabled it still receives messages which are then processed when the subscription is re-enabled. I just want to know in case it changes in the future. The docs seem to say that when it is disabled it shouldn't send or receive any messages https://docs.microsoft.com/en-us/azure/service-bus-messaging/entity-suspend

**Comment by SeanFeldman** [comment]
Pinging the mighty @adhishchugh

**Comment by euangordon** [comment]
Agree with earlier comments that it would be nice to be able to update a Subscription to stop it receiving messages. The docs suggest that this is how it should work but it doesn't. 

This doc is still no clearer:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.entitystatus?view=azure-dotnet. 

Is there any actual difference between: 
Disabled
ReceiveDisabled
SendDisabled

**Comment by g-guth** [comment]
I´m getting the same behaviour. I think it would be nice if you have the option to disable a subscription to make it stop receiving messages. For example, when you want to resend a deadletter message on the topic which failed in just one subscription, so you dont want to the other subscriptions reprocess the same message.

**Comment by SeanFeldman** [comment]
Despite "[works as designed](https://github.com/Azure/azure-service-bus/issues/84#issuecomment-331530825)" it feels like a bug from a user/customer perspective.
@axisc any chance to review the stance on this issue and relabel it accordingly?

**Comment by chaseWillden** [comment]
This does feel like a bug. Disabled shouldn't cause any errors or exceptions, it should silently not take any messages

**Comment by nagarajdev** [comment]
**When Topic is disabled:** 
No messages will received as when the message sent to topic it will throw an error - "Messaging entity 'TOPICNAME' is currently disabled"

**When Topic is enabled but subscription is disabled:**
you will still get the messaged into subscription queue but it **won't process** until the subscription  is enabled,

**Comment by MelbourneDeveloper** [comment]
@gmantri I tried to disable a whole bus just now. After I set the status to disabled, it is now jammed on Active and I cannot change it at all. The service is jammed on.

![image](https://user-images.githubusercontent.com/16697547/98482568-6ca1b180-2256-11eb-97fb-e9ed913121f6.png)

**Comment by ericsampson** [comment]
In the end, I'd like there to be a way to make it so that messages aren't lost when the delivery of messages to a subscriber is paused.

**Comment by onerob2000** [comment]
Any update on this? To add to the confusion, I have a Disabled Subscription. In my .NET Core code, when I check the SubscriptionDescription's Status property, it's saying it's Active.... Now, this would make sense given the current functionality where a Subscription still _receives_ messages although it's disabled (hence, it's still 'Active'), but this is very deceiving, just as I would expect a Subscription to stop receiving messages if it's disabled...

![image](https://user-images.githubusercontent.com/6371570/135684672-e26ab30d-098c-47a5-94ba-8a1ca999321c.png)

![image](https://user-images.githubusercontent.com/6371570/135684616-146fab34-45b6-45a9-8d3d-3791f9935d16.png)

**Comment by sethmanheim** [comment]
cc @spelluru

**Comment by EldertGrootenboer** [comment]
The [documentation indicates](https://docs.microsoft.com/en-us/azure/service-bus-messaging/entity-suspend#subscription-status) the different states which a subscription will adhere to. As can be seen, if messages are sent to a topic, it will be sent to the underlying subscriptions as well, we don't allow disabling this. This is working as designed, and we believe the linked documentation describes this well enough, so we are closing this issue.
