### ISSUE TITLE
Handling dead letter queues with the new client

### ISSUE THREAD

**Issue by cecilphillip** [Azure/azure-service-bus#87]
Could you add a sample showing how to handle dead letter queues in the new .NET Standard client to the samples directory?

**Comment by SeanFeldman** [comment]
You can get the DLQ path using `EntityNameHelper.FormatDeadLetterPath()`.

Here's a snippet to get a message from DLQ using the new client (one of the possible ways):

```c#
var receiver = new MessageReceiver(connectionString, EntityNameHelper.FormatDeadLetterPath(queueName), ReceiveMode.PeekLock);
var msg = await receiver.ReceiveAsync();
await receiver.CompleteAsync(msg.SystemProperties.LockToken);
```

Hope this helps. Perhaps you'll submit a sample 😉

**Comment by cecilphillip** [comment]
That's not a bad idea :)
The previous client also you to set EnableDeadLetteringOnMessageExpiration. Does something similar exist?

**Comment by SeanFeldman** [comment]
That aspect is a bit of a... mess. The client itself [doesn't provide](https://github.com/Azure/azure-service-bus-dotnet#can-i-manage-service-bus-entities-with-this-library) management operations. The suggested management library is not idea. But I am trying to promote the idea of making `NamespaceManager` alternative to re-surface as, potentially, an OSS separate project that would allow developers save the time and not re-invent the management operations wheel. Just like you'll be doing 😉 If you agree, [chime in here](https://github.com/Azure/azure-service-bus-dotnet/issues/65#issuecomment-328322126).

**Comment by clemensv** [comment]
The whole set of NETFX samples is being ported to NETStd right now

**Comment by ChristianWolf42** [comment]
@cecilphillip and @clemensv I think the original question is answered. Closing. Please shout if not ok

**Comment by cecilphillip** [comment]
Good to close. I saw the PR from @clemensv with the updated samples.
