### ISSUE TITLE
ForwardTo as part of ARM

### ISSUE THREAD

**Issue by hgjura** [Azure/azure-service-bus#88]
The ForwardTo is currently not being able to be set as part of the ARM.

With ForwardTo part of ARM, it will allow my team to make a 100% deployment of SB via ARM.

**Comment by binzywu** [comment]
We should have this soon. Thanks to @arundsouza!

**Comment by clemensv** [comment]
Delay here was caused by the necessary checks to ensure that a user has proper ARM permissions on both entities. Code for this is already deployed, the swagger spec is going to be updated within the next couple of days and that then trickles into clients.

**Comment by niemyjski** [comment]
@barkhashah I subscribed to this issue. Is there anything else that is missing? I thought there were a few properties missing.

**Comment by shahbarkha** [comment]
@niemyjski @SeanFeldman  We are missing these things:
1) ForwardDeadLetteredMessagesTo
2) UserMetadata
3) ForwardTo
4) EnableDeadLetteringOnFilterEvaluationExceptions
5) IsAnonymousAccessible
6) EnableFilteringMessagesBeforePublishing

**Comment by flafonta** [comment]
The forwardTo property seems to work now. However, it now takes several minutes to deploy a single topic or subscription (previously, it was taking less than a minute). Is it normal or it is a new issue?

**Comment by alexeyzimarev** [comment]
@flafonta What do you mean? The property is still not available in the .NET Standard configuration library.

**Comment by alexeyzimarev** [comment]
@flafonta What do you mean? The property is still not available in the .NET Standard configuration library.

**Comment by flafonta** [comment]
If I specify a value for the property "forwardTo" of a subscription in my arm template, it works and I now see the expected value of my forwardTo property in my "ServiceBusExplorer" tool.

However, as I said, it now takes several minutes to deploy my template, when earlier for the same template (with or without the forwardTo property) was taking 30-40 sec max to deploy

**Comment by alexeyzimarev** [comment]
@flafonta it might be available in the API but it is not available in the SDK.

**Comment by flafonta** [comment]
Ok, but since this update (probably in the api), it is now taking several minutes to deploy a single topic/subscription. Is it the expected behavior or is it a bug?

In our case, it now takes 15-20 minutes to deploy all topics/subscriptions associated with one application. I was expecting very less than that. Could you comment on this?

**Comment by ChristianWolf42** [comment]
1. ForwardDeadLetteredMessagesTo
2. UserMetadata
3. ForwardTo
4. EnableDeadLetteringOnFilterEvaluationExceptions
5. IsAnonymousAccessible - not used in ASB
6. EnableFilteringMessagesBeforePublishing - is a dev feature and should not be used in production
7. EnableBatchedOperations 
8. SupportOrdering 

We look into enabling the remaining points.

**Comment by tomerps** [comment]
"forwardTo" works provided in ARM template provided you have topic or queue already created. 

In case your "ForwardTo" topic or queue does not exist in the namespace, ARM template 's restful API blow up and does not return any error and keep running for ever.  On portal against the resource group I was trying to deploy I got following error.
"{
  "error": {
    "message": "The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101. TrackingId:b6323410-67a0-41ae-b369-5f8ca734c686_M5SN1_M5SN1_G36, SystemTracker:asos230-test-eun-cmc-orders-history-bus:Topic:bundle-1, Timestamp:2/9/2018 3:21:05 PM CorrelationId: 0313f303-071f-44d1-95f4-5d2d6c6df629",
    "code": "InternalServerError"
  }
}
"
________________________ARM template working_____________________________________
"{
 "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
 "contentVersion": "1.0.0.0",
 "parameters": {
   "serviceBusNamespaceName": {
     "type": "string",
     "defaultValue": "test-bus"
   },
   "serviceBusTopicName": {
     "type": "string",
     "defaultValue": "bundle-1"
   },
   "serviceBusSubscriptionName": {
     "type": "string",
     "defaultValue": "buyersremorse"
   }
 },
 "variables": {
   "subscriptionName": "[concat(parameters('serviceBusNamespaceName'), '/', parameters('serviceBusTopicName'), '/', parameters('serviceBusSubscriptionName'))]"
 },
 "resources": [
   {
     "apiVersion": "2017-04-01",
     "name": "[variables('subscriptionName')]",
     "type": "Microsoft.ServiceBus/namespaces/Topics/Subscriptions",
     "properties": {
       "forwardTo": "error"
     }
   }
 ],
 "outputs": {}
}
"

**Comment by Mart-Bogdan** [comment]
@tomerps perhaps topic to be forwarded to shoudl be added as dependecy?

**Comment by Mart-Bogdan** [comment]
I mean
```javascript
    {
              "apiVersion": "[variables('sbVersion')]",
              "name": "combine-messages",
              "type": "Subscriptions",
              "dependsOn": [
                "op-inbound","messages-combined"
              ],
              "properties": {
                "forwardTo": "messages-combined",
                "enableBatchedOperations": true
              },
              "resources": [
              ]
            }
```

**Comment by Mart-Bogdan** [comment]
Issue can be closed, docs are here https://docs.microsoft.com/en-us/azure/templates/microsoft.servicebus/namespaces/topics/subscriptions/rules

Had to use    "sbVersion": "2017-04-01"
and "apiVersion": "2016-09-01"

and latest version of v1 azure-cli
