### ISSUE TITLE
Not receiving messages

### ISSUE THREAD

**Issue by cwisking** [Azure/azure-service-bus#89]
Hi guys, 

I'm running the default samples using the BasicSendReceiveUsingQueueClient (samples/DotNet/Microsoft.Azure.ServiceBus/BasicSendReceiveUsingQueueClient). 

I have set it all up connecting to a SB on azure and I can successfully send messages. For some reason I never receive any messages.

I can see the messages in the azure portal.

Note I haven't changed any code from the sample except for the connection string and queue name.

Is there something that I'm missing here?

**Comment by nemakam** [comment]
@cwisking 
1. In that sample, we print out exceptions on console. Do you see any exceptions?
1. Ensure that your queue does NOT have sessions enabled. You could use some tool like `ServiceBusExplorer` to check these settings. 
1. Try doing a receive from this tool as well and check if it works.

**Comment by cwisking** [comment]
Hi, There are no exceptions in the console.

So my console output looks like
![image](https://user-images.githubusercontent.com/14339362/30997049-995db59e-a521-11e7-8bfa-db514d7ca9cf.png)

I'm using the ServiceBusExplorer and can view messages and create a queue listener, and it looks like sessions are disabled. 
![image](https://user-images.githubusercontent.com/14339362/30997101-f4c5e668-a521-11e7-87e6-33fcadc3c7f8.png)

**Comment by cwisking** [comment]
I can see that RegisterOnMessageHandlerAndReceiveMessages is called however ProcessMessagesAsync is never fired.

**Comment by SeanFeldman** [comment]
That's odd. Runs on my machine.
![image](https://user-images.githubusercontent.com/1309622/31002603-f1e48ce8-a4a8-11e7-9f89-8dd1586a2f3a.png)

What are the properties on your queue? Did you try another namespace?

**Comment by nemakam** [comment]
@cwisking 
One thing i can think of on top of my mind is that the client receives the message, but the message is already lost by the time this happens. Extreme scenario is that the system clock of your machine and the Azure machine differs by more than your lock duration that you set on your queue. So client will receive it but discard immediately since it assumes it has already expired. 
What is the lock duration on your queue?

**Comment by nemakam** [comment]
@cwisking , meanwhile while we update the samples to use latest code, could you update it on your end and take a reference to Azure.Service.Bus 2.0.0 version and see if it resolves the issue.

**Comment by nemakam** [comment]
After confirmation on https://github.com/Azure/azure-service-bus-dotnet/issues/348, I'm closing this issue. Reopen if not resolved.

**Comment by VijayaMalla** [comment]
> That's odd. Runs on my machine.
> ![image](https://user-images.githubusercontent.com/1309622/31002603-f1e48ce8-a4a8-11e7-9f89-8dd1586a2f3a.png)
> 
> What are the properties on your queue? Did you try another namespace?

I have the same problem with the same sample on docs.microsoft.com Service Bus sample.
if i remove "Console.ReadKey()" from Subscriber, then it fails, if i add that then this particular MessageHandler method is called. Please advice, because i cant keep the ReadKey() in my code right ? or do i need it.?

**Comment by SeanFeldman** [comment]
The handler needs to be executed. If you remove `Console.ReadKey()` the process terminates and you won't receive anything.

**Comment by AmiTimA** [comment]
> The handler needs to be executed. If you remove `Console.ReadKey()` the process terminates and you won't receive anything.

Is there a way to close console application after all the messages received?

**Comment by SeanFeldman** [comment]
You need to understand the concept of the handler here. It's a loop that is running as along as the process is running. When process ends, the handler will be terminated. If you have a continues stream of messages, handler (aka message pump) is a suitable option. If you just need to receive one message and exit, then there's na blocking option of Message received.ReceiveAsync().
You control the console app. App to you when to close it.

**Comment by AmiTimA** [comment]
MessageReceiver.ReceiveAsync()
That's what I was looking for, thanks.
