### ISSUE TITLE
Correlation Filter Samples

### ISSUE THREAD

**Issue by jeremiahjordanisaacson** [Azure/azure-service-bus#92]
# Description

## Actual Behavior
1.  No way documented on how to set a Correlation Filter on Message Custom Properties (a. Need an example. b. Also, an AND condition sample would be an ideal). Developers require examples of these top performance Correlation Filters in C# and PowerShell. Furthermore, these need to be added to the Azure Portal (CRUD scenarios).
2. No way to view the applied Correlation Filter after it is set/applied to the subscription.
3. No way to change the Correlation Filter on the subscription without deleting the queued data.

## Expected Behavior
1.  A documented on how to set a Correlation Filter on Message Custom Properties (AND condition sample would be ideal. Developers require examples of these top performance Correlation Filters in C# and PowerShell. Furthermore, these need to be added to the Azure Portal (CRUD scenarios).
2. A documented way to view the applied Correlation Filter set in the subscription.
3. A documented way to change the Correlation Filter on the subscription without deleting the queued data in the subscription.

**Comment by tmbalun17** [comment]
I could not find any samples either for ARM templates as mentioned abpve in point 1, A documented on how to set a Correlation Filter on Message Custom Properties (AND condition sample would be ideal. Developers require examples of these top performance Correlation Filters in C# and PowerShell. Furthermore, these need to be added to the Azure Portal (CRUD scenarios).

**Comment by ChristianWolf42** [comment]
1. @jeremiahjordanisaacson @tmbalun17 please find a sample here: https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/TopicSubscriptionWithRuleOperationsSample 
2. You can use getRules on the .Net Standard client. We may need to add it for the old client though.
3.@jeremiahjordanisaacson  Currently you would need to delete and then re add the correlation filter. Wouldn't that be sufficient?

**Comment by tmbalun17** [comment]
@ChristianWolf42  is there a ARM template sample, that is what i was after as C# based deployments are something most people will not do ...

**Comment by jeremiahjordanisaacson** [comment]
1. @ChristianWolf42 Thanks for the sample. I appreciate that you were able to provide a more clear example.
2. @ChristianWolf42 We **still** need an example on **how to set a Correlation Filter on Custom Properties of a Message** in a Topic-Subscription. One use case is that when Dynamics 365 sends messages to the Service Bus (using the Web Service Endpoint from Plugin Registration Tool), it uses Custom Properties so we need to filter based off of those. I want the C# example of that so that I can create tooling for Correlation Filters.
3. @ChristianWolf42 I agree with @tmbalun17 that most users will likely be using the JSON ARM templates so an example for him/her would be ideal. Since the build up of Subscriptions is a computation heavy operation, it is not recommended to build up and tear them down. That said, we do need the full CRUD operations of the Correlation Filter without disrupting the Subscription.
4. @ChristianWolf42 I've noticed that recent updates to Microsoft.ServiceBus Nuget package (4.1.6) broke the C# setup of Correlation Filters in my app. I have to stay with version 4.1.3. Can you look into what changed and whether this change is a bug.

**Comment by ChristianWolf42** [comment]
@jeremiahjordanisaacson and @tmbalun17 I will try to get back to you post the holiday and see what I can provide.

**Comment by jeremiahjordanisaacson** [comment]
@ChristianWolf42 Hope you had a great holiday. Looking forward to a response.

**Comment by ChristianWolf42** [comment]
@jeremiahjordanisaacson sorry for the late response. I looked a little bit into it today but didn't get the right string from code.
Here we just show the sql expression
https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-resource-manager-namespace-topic-with-rule
Trying to find the right correlation filter expression and will update you then.

**Comment by jeremiahjordanisaacson** [comment]
@ChristianWolf42 I appreciate the SQL example but we're really only interested in using Correlation Filters due to the performance increase. Looking forward to a C# example of how to set a **Correlation Filter on Custom Properties** of a Message in a Topic-**Subscription**.

**Comment by jeremiahjordanisaacson** [comment]
@ChristianWolf42 Checking in for a status update. Thanks!

**Comment by ChristianWolf42** [comment]
@jeremiahjordanisaacson here the sample to get the correlation filters to work with ARM. The **_bold / italic_** is the important part:
{
                      "apiVersion": "2017-04-01",
                      "name": "[parameters('serviceBusTopicCorrelationFilterSubscriptionName')]",
                      "type": "subscriptions",
                      "dependsOn": [
                          "[parameters('serviceBusTopicName')]"
                      ],
                      "properties": {
                      },
                      "resources": [{
                          "apiVersion": "2017-04-01",
                          **_"name": "[concat(parameters('serviceBusTopicCorrelationFilterSubscriptionName'), '-correlationRule')]",_**
                          "type": "Rules",
                          "dependsOn": [
                              "[parameters('serviceBusTopicCorrelationFilterSubscriptionName')]"
                          ],
                          "properties": {
                                **_"filterType": "CorrelationFilter",
                              "correlationFilter": {
                                "label": "Red",
                                  "correlationId" : "important"_**                                                                                                                    
                              }
                          }
                      }]
                  }
Sorry it took a while but we are a bit overloaded right now. Please let me know if this works for you.

**Comment by jeremiahjordanisaacson** [comment]
Again thank you but I’m really more interested in the C# example.

**Comment by ChristianWolf42** [comment]
@jeremiahjordanisaacson I am sorry but I won't be able to provide that this year. :( We are unfortunately having only half the people and around twice the requests right now due to end of year business. Can you give it a shot with above data it should be possible to derive the calls?

**Comment by jeremiahjordanisaacson** [comment]
@ChristianWolf42 We have tried extensively. Looking forward to a response when you have time.

**Comment by jeremiahjordanisaacson** [comment]
@ChristianWolf42 Checking in to see if there are any updates on this ask. Thanks!

**Comment by ChristianWolf42** [comment]
@jeremiahjordanisaacson have you looked at SubscriptionClientTests.cs method CorrelationFilterTestCase? It shows how to create a new CorrelationFilter using 
await subscriptionClient.AddRuleAsync(new RuleDescription
                {
                    Filter = new CorrelationFilter { Label = "Red" },
                    Name = "RedCorrelation"
                });

It also shows how to remove it later on.

Then gives a sample on sending a little later. Is that code sufficient?

**Comment by jeremiahjordanisaacson** [comment]
@ChristianWolf42 I think there is some miscommunication happening here. I'm asking how to set a correlation filter for a **Custom** property on the message. All of the examples you have provided only work for **System** properties. I'm trying to do something like:

await subscriptionClient.AddRuleAsync(new RuleDescription
{
Filter = new CorrelationFilter { http://contoso.dynamics.crm.com/2011/api/org = "contoso201" },
http://contoso.dynamics.crm.com/2011/api/entity= "account"
http://contoso.dynamics.crm.com/2011/api/messagetype= "create"
});

When I try to do this in C# it doesn't compile because "http://contoso.dynamics.crm.com/2011/api/org " isn't a System property, it's a custom property being passed in so it isn't "known" until the message arrives in the Topic. Anyone who will want to use Dynamics 365's web service endpoint feature will experience this issue since the Dynamics 365 PG sends Custom properties to the Topic to describe the message. Any suggestions on how to get this to work in C#?

**Comment by nemakam** [comment]
@jeremiahjordanisaacson 
In `CorrelationFilter`, there is a public property `Properties` which can be used for using this filter on custom properties.
Its a key-value property bag where in you can add your keys and values to get the desired effect.

**Comment by nemakam** [comment]
@jeremiahjordanisaacson 

> No way documented on how to set a Correlation Filter on Message Custom Properties (a. Need an example. b. Also, an AND condition sample would be an ideal). Developers require examples of these top performance Correlation Filters in C# and PowerShell. Furthermore, these need to be added to the Azure Portal (CRUD scenarios).

Take a look at `CorrelationFilter.Properties`

> No way to view the applied Correlation Filter after it is set/applied to the subscription.

`SubscriptionClient.GetRulesAsync()`

> No way to change the Correlation Filter on the subscription without deleting the queued data.

You can do `SubscriptionClient.RemoveRulesAsync()` and then do `SubscriptionClient.AddRulesAsync()` to add the updated rule.

**Comment by jeremiahjordanisaacson** [comment]
@nemakam Thank you for the response! I will try this and get back to you. Appreciate it. @ChristianWolf42 @nemakam

**Comment by nemakam** [comment]
@jeremiahjordanisaacson 
Btw, there would be slight difference depending on which library are you using?

Do you use the new dotnet standard Microsoft.Azure.ServiceBus library or the older full dotnet library?

**Comment by jeremiahjordanisaacson** [comment]
@nemakam I'm using:

    using System;
    using System.Windows.Forms;
    using System.Collections.Generic;
    using Microsoft.ServiceBus;
    using Microsoft.ServiceBus.Messaging;

What is the recommended approach?

**Comment by nemakam** [comment]
That would be the older full framework library. 
You can find similar methods in `NamespaceManager` of that library.
You can create namespace manager using `NamespaceManager.CreateFromConnectionString()`

The way to use `CorrelationFilter.Properties` remain the same across both the libraries

**Comment by jeremiahjordanisaacson** [comment]
@nemakam Thanks will give that a try and share results.

**Comment by ChristianWolf42** [comment]
@jeremiahjordanisaacson I know it is not documented anywhere we will fix it. here the code sample which should allow to filter custom correlation filter:
 CorrelationFilter customerPropertyFilter = new CorrelationFilter();
            customerPropertyFilter.Properties.Add("http://contoso.dynamics.crm.com/2011/api/org", "contoso201");

            await subscriptionClient.AddRuleAsync(new RuleDescription
            {
                Filter = customerPropertyFilter,
                Name = "CustomProp"
            });

Then when you send the message:
message.UserProperties.Add("http://contoso.dynamics.crm.com/2011/api/org", "contoso201");

Hope that solves the problem.
There is a few things missing around filtering in our doucmentation and I took note on how to fix it.
Adding @nemakam for his info

**Comment by ChristianWolf42** [comment]
@jeremiahjordanisaacson one more quick thing, it would be awesome if we could get a little code sample right away next time. You are obviously right in the lack of documentation but I think if I would have had your code snipped I would have been able to answer your actual question way faster.

**Comment by sethmanheim** [comment]
Filed doc bug 1182786.

**Comment by SeanFeldman** [comment]
I've posted a short [blog post](https://twitter.com/sfeldman/status/980475177636052992) about correlation filters that could help with a sample/doco.

**Comment by EldertGrootenboer** [comment]
If this issue still occurs, please let us know and we can re-open the issue.
