### ISSUE TITLE
GeoDR sample is missing packages.config files

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus#98]
Both, [SBGeoDR2](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.ServiceBus.Messaging/GeoDR/SBGeoDR2/SBGeoDR2) and [TestGeoDR](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.ServiceBus.Messaging/GeoDR/TestGeoDR/ConsoleApp1) are missing `packages.config` file. W/o the files, projects can't be executed.

![image](https://user-images.githubusercontent.com/1309622/31532556-3acd44f6-afab-11e7-8f72-b27b82fe0e25.png)

Files got removed in this commit 092c7ddd24edda684a52258774253e3fa5b79ddb

**Comment by ChristianWolf42** [comment]
Added the packages.config, thanks a lot for catching that one!
