### ISSUE TITLE
Subscribe on all subscribtions of topic

### ISSUE THREAD

**Issue by Marusyk** [Azure/azure-service-bus#99]
Is there possibility to subscribe on all subscriptions of the topic? I have one topic and many subscriptions (1 per service). Then I need to create another service that should susbcribe on all events in the topic. Is that possible? I didn't find any information so, write here. Thank you in advance

**Comment by SeanFeldman** [comment]
@Marusyk would a subscription with a default rule (`1=1`) work for you? You'll receive any message sent to the topic.

**Comment by nemakam** [comment]
@Marusyk ,
@SeanFeldman is right. You could just create another subscription with the default rule (`1=1`). As long as you don't provide your custom rule, the subscription receives all the messages from the topic.

**Comment by Marusyk** [comment]
Thanks for advices. One more silly question, how to set default rule?

**Comment by SeanFeldman** [comment]
@Marusyk https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-dotnet-how-to-use-topics-subscriptions 😉

**Comment by Marusyk** [comment]
@SeanFeldman Hello, could you please suggest if there are any possibility to subscribe on all events in all topics? I'm going to use one topic per microservice and then I want to create something like EventStore microservice to save all events to the database. So, I need to subscribe on all events from Service Bus. Is that possible?

**Comment by clemensv** [comment]
Yes. That is possible. Create a queue. Give it a name. You can then create a subscription on each topic that uses the TrueFilter (which is the default) and then sets ForwardTo to the name of that queue. The queue then receives all messages sent to all topics and you can retrieve them.

**Comment by SeanFeldman** [comment]
@Marusyk programmatically you _could_ iterate over all topics and create a "catch all" (1=1) subscriptio" for each topic. Challenge with that is that you'd need periodically refresh topics to add subscription to belly added topics.

OOTB there's nothing as far as I know.

**Comment by Marusyk** [comment]
Thanks a lot. @clemensv Can I set ForwardTo on the portal when creating subscription? I can't find that place.

**Comment by clemensv** [comment]
No. This is supported in ARM templates. See https://github.com/clemensv/azure-service-bus/blob/netstdsamples/samples/DotNet/Microsoft.Azure.ServiceBus/scripts/azuredeploy.json#L541
